### PR TITLE
Release - 1.2.8

### PR DESCRIPTION
**Pull request by ryanio**
## Description

This PR introduces `web3.js` version `1.2.8` beginning with `1.2.8-rc.0`.

### Features

Alongside some Typescript improvements and patches for the Websocket Provider reconnection logic introduced in 1.2.7, this release contains two larger changes:

+ **Ethers ABI Coder** has received a full version increment, from 4.0.0-beta.3 to 5.0.0-beta.153. Since 2018, Web3 has relied on @ricmoo's great [Ethers project][4] to manage encoding and decoding data passed between Web3 and the EVM. This update should allow Web3 to absorb the latest work at Ethers going forward. 
+ The ENS module now supports **ENS's `contenthash`** feature ([EIP 1577][2]), which allows you to associate an IPFS or Swarm hash with an ENS domain. There's a nice introduction to content hashes [in this ENS medium post][1]. Docs for the newly added methods [can be found here][3]. 

[1]: https://medium.com/the-ethereum-name-service/the-new-ens-manager-now-supports-eip1577-contenthash-82e2d6724fae
[2]: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1577.md
[3]: https://web3js.readthedocs.io/en/v1.2.8-rc.0/web3-eth-ens.html#getcontenthash
[4]: https://docs.ethers.io/ethers.js/html/

### Added

- Introduce review and release guidelines. (#3460)
- Add EIP-1193 compatible provider to `AbstractProvider` interface. (#3499)
- Add Typescript definitions for contract `methods` and `call`. (#3454)
- Add support for ENS contenthash methods (#3392, #2782)

### Changed

- Change CI provider from Travis to Github Actions. (#3468)
- Update `web3-eth-abi` ABICoder dependency. (#3490)
- Improve code clarity of HttpProvider keepAlive option setting. (#3463)
- Updated type definitions for Web3 HTTP Provider. (#3482)
- Improve code clarity of HttpProvider keepAlive value. (#3463)
- Fix indentation of web3-eth documentation (#3478)

### Fixed

- Fix intermittent CI build issues with `dtslint`. (#3479)
- Fix WSS credentials Base64 encoding (for browser) (#3508)
- Fire provider "error" and/or "end" events when Websocket provider disconnects (#3485)
- Remove web3-eth revert error return types to squash TS compilation errors (#3496)
- Backfill event subscriptions when WS connection dropped across multiple blocks (#3491)
- Stop swallowing errors when WS connection has died after exhausting reconnection attempts (#3492)

## Type of change

- [x] Release

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [x] I ran `npm run test:unit` with success.
- [x] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [x] I ran `npm run build-all` and tested the resulting files from `dist` folder in a browser.
- [x] I have updated the `CHANGELOG.md` file in the root folder.
- [x] I have tested my code on the live network.

### CODE REVIEW

**Comment by cgewecke** [comment]
As part of the RC process, am doing some test installations in other projects and running their tests to see if everything.  
+ installs properly
+ builds
+ tests pass

This list will be actively edited: 

| Project | Desc | Status | 
| ------ | ----- | ----- |
| [oz-test-helpers][1] | Test utils. Subset of their suite is web3 contracts | ✅  |
| [gnosis/dex-react][3] | TS React app ~200 tests + webpack build + jest | ✅    |
| [synthetix (buidler branch)][2] | ~1000 units (check ABICoder change) | ✅  |

**Implementation notes for future reference:**
+ Synthetix yarn resolutions required for:
  + nomiclabs/
  + openzeppelin-solidity-2.3.0
  + chainlink/
  + truffle/
+ oz-test-helpers
  + truffle/
  + openzeppelin/
+ gnosis/dex-react
  + walletconnect
  + gnosis/pm

[1]: https://github.com/OpenZeppelin/openzeppelin-test-helpers
[2]: https://github.com/Synthetixio/synthetix/tree/gas-reports-for-buidler
[3]: https://github.com/gnosis/dex-react

**Comment by cgewecke** [comment]
Found a behavioral difference in the new abi decoder while running the [synthetix][1] unit tests, 

Negative numbers passed as `uint` params are now flagged as "out of bounds". They used to be allowed. 

The new behavior seems safer - perhaps we can just mention the difference in the release notes? 

[EDIT] One case where this change might be problematic is for testing underflow logic itself, as [here at openzeppelin/math][2]. Wouldn't immediately impact them because they're on @truffle/contract and Web3@1.2.1 fwiw.

[1]: https://github.com/Synthetixio/synthetix/tree/gas-reports-for-buidler
[2]: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/test/math/SignedSafeMath.test.js

**JS test**
```js
it('should revert when owner set the Target threshold to negative', async () => {
  const thresholdPercent = -1;
  await assert.revert(feePool.setTargetThreshold(thresholdPercent, { from: owner }));
});
```

**Solidity**
NB: the test above throws: `Threshold too high`, e.g. -1 is an underflow
```solidity
function setTargetThreshold(uint _percent) external optionalProxy_onlyOwner {
        require(_percent >= 0, "Threshold should be positive"); 
        require(_percent <= 50, "Threshold too high");
        targetThreshold = _percent.mul(SafeDecimalMath.unit()).div(100);
}
```

**Error**
```
  1) Contract: FeePool
       when integrating with modern contracts
         FeeClaimablePenaltyThreshold
           should revert when owner set the Target threshold to negative:
     AssertionError: expected 'value out-of-bounds (argument="_percent", value=-1, code=INVALID_ARGUMENT, version=abi/5.0.0-beta.153)' to include 'revert'
      at Object.assertRevert [as revert] (test/utils/index.js:402:11)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by cgewecke** [comment]
Looks like the some of the types changes might be breaking....  

[gnosis/dex-react][1] tsc fails with:
```
ERROR in /Users/cgewecke/code/ef/synII/dex-react/src/api/deposit/DepositApi.ts
ERROR in /Users/cgewecke/code/ef/synII/dex-react/src/api/deposit/DepositApi.ts(70,31):
TS2352: Conversion of type 'Contract' to type 'ExtendedContract<BatchExchange>' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type 'Contract' is not comparable to type 'Pick<BatchExchange, "methods" | "defaultAccount" | "defaultBlock" | "defaultCommon" | "defaultHardfork" | "defaultChain" | "transactionPollingTimeout" | "transactionConfirmationBlocks" | ... 4 more ... | "getPastEvents">'.
    Types of property 'methods' are incompatible.
      Type '{ [key: string]: ContractSendMethod; }' is missing the following properties from type '{ IMPROVEMENT_DENOMINATOR(): TransactionObject<string>; getSecondsRemainingInBatch(): TransactionObject<string>; requestWithdraw(token: string, amount: string | number): TransactionObject<...>; ... 37 more ...; getCurrentObjectiveValue(): TransactionObject<...>; }': IMPROVEMENT_DENOMINATOR, getSecondsRemainingInBatch, requestWithdraw, FEE_FOR_LISTING_TOKEN_IN_OWL, and 37 more.

ERROR in /Users/cgewecke/code/ef/synII/dex-react/src/api/erc20/Erc20Api.ts
ERROR in /Users/cgewecke/code/ef/synII/dex-react/src/api/erc20/Erc20Api.ts(106,31):
TS2352: Conversion of type 'Contract' to type 'ExtendedContract<Erc20>' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type 'Contract' is not comparable to type 'Pick<Erc20, "methods" | "defaultAccount" | "defaultBlock" | "defaultCommon" | "defaultHardfork" | "defaultChain" | "transactionPollingTimeout" | "transactionConfirmationBlocks" | ... 4 more ... | "getPastEvents">'.
    Types of property 'methods' are incompatible.
      Type '{ [key: string]: ContractSendMethod; }' is missing the following properties from type '{ name(): TransactionObject<string>; approve(_spender: string, _value: string | number): TransactionObject<boolean>; totalSupply(): TransactionObject<...>; ... 5 more ...; allowance(_owner: string, _spender: string): TransactionObject<...>; }': name, approve, totalSupply, transferFrom, and 5 more.

ERROR in /Users/cgewecke/code/ef/synII/dex-react/src/api/tcr/MultiTcrApi.ts
ERROR in /Users/cgewecke/code/ef/synII/dex-react/src/api/tcr/MultiTcrApi.ts(37,31):
TS2352: Conversion of type 'Contract' to type 'ExtendedContract<Tcr>' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type 'Contract' is not comparable to type 'Pick<Tcr, "methods" | "defaultAccount" | "defaultBlock" | "defaultCommon" | "defaultHardfork" | "defaultChain" | "transactionPollingTimeout" | "transactionConfirmationBlocks" | ... 4 more ... | "getPastEvents">'.
    Types of property 'methods' are incompatible.
      Property 'getTokens' is missing in type '{ [key: string]: ContractSendMethod; }' but required in type '{ getTokens(_listId: string | number): TransactionObject<string[]>; }'.

ERROR in /Users/cgewecke/code/ef/synII/dex-react/src/api/wallet/WalletApi.ts
ERROR in /Users/cgewecke/code/ef/synII/dex-react/src/api/wallet/WalletApi.ts(184,27):
TS2339: Property 'connected' does not exist on type 'HttpProvider | IpcProvider | WebsocketProvider | AbstractProvider'.
  Property 'connected' does not exist on type 'AbstractProvider'.
Child HtmlWebpackCompiler:
     1 asset
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/html/index.html 1.74 KiB {0} [built]
Child favicons-webpack-plugin:
     1 asset
    Entrypoint logo.svg = 58d2a652c3e9d3d2d6b3
    [0] ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"/Users/cgewecke/code/ef/synII/dex-react/node_modules/.cache/favicons-webpack-plugin"}!./node_modules/favicons-webpack-plugin/src/loader.js?{"prefix":"assets/","options":{"appName":"Mesa - Gnosis Protocol DApp","appDescription":"Mesa - Gnosis Protocol DApp","developerName":"Mesa - Gnosis Protocol DApp","developerURL":null,"background":"#dfe6ef","themeColor":"#476481","icons":{"coast":false,"yandex":false},"version":"0.11.1"},"path":""}!./src/assets/img/logo.svg 3.34 MiB {0} [built]
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

----------

Can be tricked into passing by:

+ Adding an optional `connected` property to AbstractProvider here:

https://github.com/ethereum/web3.js/blob/d6eda4df04214fb2441b92fa56b856190e3629e5/packages/web3-core/types/index.d.ts#L419-L423

+ Appending `| any` to the contract.methods re-definition here:

https://github.com/ethereum/web3.js/blob/137ca7ba2167f5f022d18025ed3135c69476652e/packages/web3-eth-contract/types/index.d.ts#L49-L51
 
[1]: https://github.com/gnosis/dex-react

**Comment by ricmoo** [comment]
I think the version of the ABI coder Web3 was previously using was quite old, so there may be other important differences to try out.

- bit widths; passing 257 in a uint8 should fail
- bytesXX must be exactly the correct length; the older ethers coder may have automatically padded, depending on what version (e.g. bytes2 should be “0x1234”, not “0x12”)

**Comment by alcuadrado** [comment]
I think it's worth reconsidering the option of vendoring that part of ethers v4. Otherwise, the risk of accidentally introducing a breaking change is high.

**Comment by cgewecke** [comment]
@alcuadrado 

Are there any precautions which could be taken which would make you feel more at ease with this? 

The case for upgrading (e.g. *not* vendoring) is to make encoding/decoding here more closely aligned with ongoing work at Ethers and and inherit improvements there. 

In two cases identified so far, web3 is accepting invalid inputs and a behavior change might be reasonable to consider as bug fixes:
+ throw when passing negative numbers as unsigned ints
+ throw when passing numbers outside allowable bit ranges for params

A third change is automatic padding for byte values - it looks like efforts here to address that might be incomplete (but could be fixed).

We've run the Synthetix and [mosaicdao/mosaic][1] unit tests (~1300) with 1.2.8-rc.0 and they're (basically) passing...

Definitely agree that there's risk and some unknowns here. But am wondering how you would upgrade this dependency at all given the versioning constraints here. Do you think on balance this is not worth doing?   

[1]: https://github.com/mosaicdao/mosaic-1

**Comment by alcuadrado** [comment]
I'm ok with the upgrade @cgewecke. It will have to happen eventually. 

I was just putting the other alternative on the table again, in case the upgrade path isn't complete fast enough. This was in the context of web3's future uncertainty and the npm stats issue. Otherwise, I wouldn't care about the time it takes to ship this change and just upgrade.

**Comment by cgewecke** [comment]
@ricmoo 

From memory, does this seem like a complete list of the input validation changes between ABI Coder V4 / V5?

+ byte lengths enforced for `bytesX` and variants 
+ bit widths enforced for `uintX` and variants
+ positive number enforced for uint

It looks like the approach we'd take here to minimize breaks is to pad bytes where possible and treat the additional strictness elsewhere as bug fixes.

**Comment by ryanio** [comment]
Thanks everyone. I have released [`1.2.8-rc.1`](https://github.com/ethereum/web3.js/releases/tag/v1.2.8-rc.1) with the following:

- Update AbiCoder param formatting ([#3522](https://github.com/ethereum/web3.js/pull/3522))
- Update AbstractProvider and contract.methods TS definitions ([#3521](https://github.com/ethereum/web3.js/pull/3521))
- Fix setContenthash docs formatting ([#3511](https://github.com/ethereum/web3.js/pull/3511))

**Review by cgewecke — APPROVED** [review]
Re-ran synthetix and gnosis/dex-react outside tests with 1.2.8-rc.1 and they're both good.

LGTM.

**Pull request merged**
