### PR TITLE
Release - 1.2.2

### PR DESCRIPTION
**Pull request by nivida**
## Description

This release contains mostly back-ports from 2.x and some other improvements.

### Added

- localStorage support detection added (#3031)
- getNetworkType method extended with Görli testnet (#3095)
- supportsSubscriptions method added to providers (#3116)
- Add `eth.getChainId` method (#3113)
- Minified file added to web3 package (#3131)
- The transaction confirmation workflow can now be configured (#3130)
- Additional parameters for accounts.signTransaction added [(docs)](https://web3js.readthedocs.io/en/v1.2.2/web3-eth-accounts.html#signtransaction) (#3141)
- Emit `connected` event on subscription creation (#3028)
- TypeScript type definitions added for all modules (#3132)
- Bloom filters added to web3.utils (#3137)

### Fixed

- Fix allow `0` as a valid `fromBlock` or `toBlock` filter param (#1100)
- Fix randomHex returning inconsistent string lengths (#1490)
- Fix make isBN minification safe (#1777)
- Fix incorrect references to BigNumber in utils.fromWei and utils.toWei error messages (#2468)
- Fix error incorrectly thrown when receipt.status is `null` (#2183)
- Fix incorrectly populating chainId param with `net_version` when signing txs (#2378)
- regeneratorRuntime error fixed (#3058)
- Fix accessing event.name where event is undefined (#3014)
- fixed Web3Utils toHex() for Buffer input (#3021)
- Fix bubbling up tx signing errors (#2063, #3105)
- HttpProvider: CORS issue with Firefox and Safari (#2978)
- Ensure the immutability of the `tx` object passed to function `signTransaction` (#2190)
- Gas check fixed (#2381)
- Signing issues #1998, #2033, and #1074 fixed (#3125)
- Fix hexToNumber and hexToNumberString prefix validation (#3086)
- The receipt will now returned on a EVM error (this got removed on beta.18) (#3129)
- Fixes transaction confirmations with the HttpProvider (#3140)
### Compare View

[v1.2.1 -> v1.2.2](https://github.com/ethereum/web3.js/compare/v1.2.1...a2027aa)

## Type of change

- [X] Release

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code. 
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no warnings.
- [x] I have updated or added types for all modules I've changed
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I executed all the tests with success and extended the tests to cover all changes.
- [x] I ran ```npm run build``` in the root folder and tested it in the browser and with node.
- [x] I have tested all changes with an ethereum test network.

### CODE REVIEW

**Comment by nivida** [comment]
@cgewecke It would be great if you could check the draft release notes I've created. I have written some phrases about all important additions and improvements.

**Comment by joshstevens19** [comment]
Looks good, just a thought for next time, it probably would of been better to of merged every PR into the `release/1.2.2` branch rather then directly into `1.x`. Then this PR would of showed all the changes with the release notes. 

Anyway looks good to merge :+1:

**Review by cgewecke — APPROVED** [review]
Sweet! Release notes LGTM.

**Review by michaelsbradleyjr — APPROVED** [review]

**Comment by alcuadrado** [comment]
Thanks for the work you all put into this :)

I just left two small comments on #3131 and #3116

**Pull request merged**
