### PR TITLE
chore(deps): bump util from 0.12.0 to 0.12.5

### PR DESCRIPTION
**Pull request by wobsoriano**
## Description

Bumps `web3-core-requestmanager` [util](https://github.com/browserify/node-util) dependency from v0.12.0 to v0.12.5. Mostly bug and security fixes happened from 0.12.0 to 0.12.5 and should not have any breaking changes. This could also fix the issue https://github.com/web3/web3.js/issues/4992.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist for 1.x:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` with success.
- [ ] I have tested the built `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

### CODE REVIEW

**Comment by luu-alex** [comment]
Hi there @wobsoriano thanks for the PR it looks good. Can you remove the package-lock.json and dist folder changes? those shouldn't be included

**Comment by wobsoriano** [comment]
Done @luu-alex!

**Comment by luu-alex** [comment]
👍

**Review by nikoulai — APPROVED** [review]

**Comment by luu-alex** [comment]
Thank you for the contribution, it has been merged :) https://github.com/web3/web3.js/pull/5700

**Pull request closed without merging**
