### PR TITLE
fix: send tx for injected providers

### LINKED ISSUE #5591: [4.x] Transaction sending does not work with Ganache's EthereumProvider
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Runtime error about missing method
```
/home/mpetrunic/Projects/ChainSafe/@web3.js/repro/ganache-provider/node_modules/web3-eth/dist/utils/reject_if_block_timeout.js:5
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
                                                         ^
TypeError: provider.supportsSubscriptions is not a function
    at /home/mpetrunic/Projects/ChainSafe/@web3.js/repro/ganache-provider/node_modules/web3-eth/src/utils/reject_if_block_timeout.ts:169:12
    at Generator.next (<anonymous>)
    at fulfilled (/home/mpetrunic/Projects/ChainSafe/@web3.js/repro/ganache-provider/node_modules/web3-eth/dist/utils/reject_if_block_timeout.js:5:58)
```

### Expected Behavior

Should work.
Probably this: https://github.com/web3/web3.js/blob/4.x/packages/web3-eth/src/utils/reject_if_block_timeout.ts#L169
should not expect every provider to have this method.

### Steps to Reproduce

```typescript
import Web3 from "web3"
import {LegacySendProvider} from "web3-types"
import ganache from "ganache";

(async function() {
    const LOCAL_PREFUNDED_MNEMONIC =
  "pioneer casual canoe gorilla embrace width fiction bounce spy exhibit another dog";
    
    const server = ganache.server({
        wallet: {
            mnemonic: LOCAL_PREFUNDED_MNEMONIC,
            defaultBalance: 100,
        },
    });
    const provider = server.provider;

    const web3 = new Web3(provider as LegacySendProvider)

    const accounts = await web3.eth.getAccounts();

    await web3.eth.sendTransaction({to: accounts[1], from: accounts[0], value: "100000"})
})()
```

### Web3.js Version

4.0.1-alpha.1

### Environment

- Operating System: 
- Browser: 
- Node.js Version: 
- NPM Version: 

### Anything Else?

#5309 would detect those things.

### PR DESCRIPTION
**Pull request by mpetrunic**
## Description

Please include a summary of the changes and be sure to follow our [Contribution Guidelines](../blob/1.x/CONTRIBUTIONS.md).

Implementation wrongly assumes every provider has `supportsSubscriptions` method which is not true for injected providers.

No idea how to write test for that.

Fixes #5591 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist for 1.x:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` with success.
- [ ] I have tested the built `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

## Checklist for 4.x:

- [ ] I have selected the correct 4.x base branch.
- [ ] Within the description, the feature or issue is discussed in detail or an issue is linked.   
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added any required tests for the changes I made 
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `yarn` successfully
- [ ] I ran `yarn lint` successfully
- [ ] I ran `yarn build:web` successfully
- [ ] I ran `yarn test:unit` successfully
- [ ] I ran `yarn test:integration` successfully
- [ ] I ran `compile:contracts` successfully
- [ ] I have tested my code.
- [ ] I have updated the corresponding `CHANGELOG.md` file in the packages I have edited.

### CODE REVIEW

**Review by jdevcs — APPROVED** [review]

**Comment by Muhammad-Altabba** [comment]
Thanks for your contribution.
And I think this could be tested by initializing a provider and then assigning `undefined` to its `supportsSubscriptions` method. And then if sending a transaction did not throw, this means that the code works well.
Or what do you think?

**Comment by mpetrunic** [comment]
> Thanks for your contribution. And I think this could be tested by initializing a provider and then assigning `undefined` to its `supportsSubscriptions` method. And then if sending a transaction did not throw, this means that the code works well. Or what do you think?

~~I'm having trouble running integration tests in web3-eth package and I cannot figure out if they are being executed in CI~~

Tried this, but tests are timing out :(
```typescript
const provider = new HttpProvider(getSystemTestProvider())
const injectedProvider: EIP1193Provider<EthExecutionAPI> =  {
	request: provider.request.bind(provider),
}
web3Eth = new Web3Eth(injectedProvider);
```

**Review by avkos — APPROVED** [review]

**Comment by Muhammad-Altabba** [comment]
> > Thanks for your contribution. And I think this could be tested by initializing a provider and then assigning `undefined` to its `supportsSubscriptions` method. And then if sending a transaction did not throw, this means that the code works well. Or what do you think?
> 
> ~I'm having trouble running integration tests in web3-eth package and I cannot figure out if they are being executed in CI~
> 
> Tried this, but tests are timing out :(
> 
> ```ts
> const provider = new HttpProvider(getSystemTestProvider())
> const injectedProvider: EIP1193Provider<EthExecutionAPI> =  {
> 	request: provider.request.bind(provider),
> }
> web3Eth = new Web3Eth(injectedProvider);
> ```

This is interesting. It could be another issue that we need to take care of :smile: .
I would suggest pushing the full code that contains the test case, and then I would probably debug it locally. 
Or you may open another issue to investigate this matter. And probably merge this MR if you could test it locally at another project, for example.
Or what do you suggest?

**Comment by mpetrunic** [comment]
> > > Thanks for your contribution. And I think this could be tested by initializing a provider and then assigning `undefined` to its `supportsSubscriptions` method. And then if sending a transaction did not throw, this means that the code works well. Or what do you think?
> > 
> > 
> > ~I'm having trouble running integration tests in web3-eth package and I cannot figure out if they are being executed in CI~
> > Tried this, but tests are timing out :(
> > ```ts
> > const provider = new HttpProvider(getSystemTestProvider())
> > const injectedProvider: EIP1193Provider<EthExecutionAPI> =  {
> > 	request: provider.request.bind(provider),
> > }
> > web3Eth = new Web3Eth(injectedProvider);
> > ```
> 
> This is interesting. It could be another issue that we need to take care of smile . I would suggest pushing the full code that contains the test case, and then I would probably debug it locally. Or you may open another issue to investigate this matter. And probably merge this MR if you could test it locally at another project, for example. Or what do you suggest?

I tested locally, and it did send transaction. Will open another PR with just test case.

**Comment by Muhammad-Altabba** [comment]
Dear @mpetrunic 
I think this MR is all great and just needs to be merged.  Or does it pending for something?
Thanks,

**Review by Muhammad-Altabba — APPROVED** [review]

**Comment by mpetrunic** [comment]
> Dear @mpetrunic I think this MR is all great and just needs to be merged. Or does it pending for something? Thanks,

Seems like I stopped signing commits on my new laptop. Fixed and replaced with signed commit.

Also wasn't sure if we are waiting on #5309

**Comment by Muhammad-Altabba** [comment]
> > Dear @mpetrunic I think this MR is all great and just needs to be merged. Or does it pending for something? Thanks,
> 
> Seems like I stopped signing commits on my new laptop. Fixed and replaced with signed commit.
> 
> Also wasn't sure if we are waiting on #5309

Here is an [MR ](https://github.com/web3/web3.js/pull/5652) for #5309. It contains tests for both `ganache` and `in3`. I also merged your commit from this MR into my MR. 

(By the way, I could not cherry-pick this commit because it is on a private branch. So, I made a small MR from your private branch to my branch and then merged it)

**Comment by mpetrunic** [comment]
Superseded by https://github.com/web3/web3.js/pull/5652

> Here is an [MR ](https://github.com/web3/web3.js/pull/5652) for #5309. It contains tests for both `ganache` and `in3`. I also merged your commit from this MR into my MR.
> 
> (By the way, I could not cherry-pick this commit because it is on a private branch. So, I made a small MR from your private branch to my branch and then merged it)

No worries, I don't care about that 😛 
Just for info in the future, to do that, you have to add the contributors fork as remote and fetch his branch^^

**Pull request closed without merging**
