### PR TITLE
Use prettier to get consistent code styles

### PR DESCRIPTION
**Pull request by levino**
This PR runs prettier in a basic configuration over the whole codebase. It also includes a check whether or not prettier would create no changes to the linter step.

Part of #1865

### CODE REVIEW

**Comment by levino** [comment]
This is just prettier running over the code. Please note that it does not change the AST. It does not change any logic. All tests will still pass. All interfaces look the same.

**Comment by levino** [comment]
Keep in mind that all PRs that are open will most probably have conflicts when this gets merged.

**Comment by levino** [comment]
And the fact that coveralls reports that coverage has increased shows how pointless that shit tool is.

**Comment by nivida** [comment]
Hay I'll close this issue because I already added prettier in the ethereumProvider branch but thanks for submitting this PR!

**Pull request closed without merging**
