### PR TITLE
v1.5.0

### PR DESCRIPTION
**Pull request by Spacesai1or**
### Added

- London transaction support (#4155)
- RPC support `eth_feehistory` call (#4191)

### Changed

 - Grammar fix (#4088) and updated Swarm (#4151)and Whisper doc links (#4170)
 - Removed deprecation notice for HttpProvider (#4008)
 - Nonce added to send options in documentation and types (#4052)
 - Updated Solidity example to modern syntax (#4147)
 - Changing web3 connection example from lets to const (#3967)
 - Updated the documentation for the transaction object to include EIP-2718 and EIP-1559 options (#4188)

---

An example of signing an EIP-1559 transaction with `web3-eth-accounts`

```javascript
import Web3 from 'web3';

const web3 = new Web3(Web3.givenProvider || 'http://localhost:8545');

const txObject = {
    to: '0x...',
    value: web3.utils.toHex(web3.utils.toWei('0.1', 'ether')),
    gas: web3.utils.toHex(21000),
    maxFeePerGas: web3.utils.toHex(web3.utils.toWei('1.5', 'gwei')),
    maxPriorityFeePerGas: web3.utils.toHex(web3.utils.toWei('.5', 'gwei'))
 };

 web3.eth.accounts.signTransaction(txObject, privateKey, (err, signed) => {...});
```

### CODE REVIEW

**Comment by corymsmith** [comment]
@spacesailor24 Shouldn't we also add support for the eth_feeHistory call?

**Comment by Spacesai1or** [comment]
> @spacesailor24 Shouldn't we also add support for the eth_feeHistory call?

Yes, you're correct. This slipped through, I'll work on getting this added today

Thank you!

**Comment by Spacesai1or** [comment]
> @spacesailor24 Shouldn't we also add support for the eth_feeHistory call?

@corymsmith [v1.5.0-rc.1](https://github.com/ChainSafe/web3.js/releases/tag/v1.5.0-rc.1) has been released, and contains `getFeeHistory` method within the `web3-eth` package

**Comment by luu-alex** [comment]
<p style="box-sizing: border-box; margin-bottom: 16px; margin-top: 0px !important; color: rgb(36, 41, 46); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Replicating the steps mentioned in<span> </span><a href="https://github.com/ethereum/web3.js/pull/3633#issuecomment-656217052" data-hovercard-type="pull_request" data-hovercard-url="/ChainSafe/web3.js/pull/3633/hovercard" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;">previous releases</a></p><p style="box-sizing: border-box; margin-bottom: 16px; margin-top: 0px; color: rgb(36, 41, 46); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">As part of the RC process, am doing some test installations in other projects and running their tests to see if everything.</p><ul style="box-sizing: border-box; margin-bottom: 16px; margin-top: 0px; padding-left: 2em; color: rgb(36, 41, 46); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box; margin-left: 0px;">installs properly</li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;">builds</li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;">tests pass</li></ul><p style="box-sizing: border-box; margin-bottom: 16px; margin-top: 0px; color: rgb(36, 41, 46); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">(This list will be actively edited)</p>

Project | Desc | Status
-- | -- | --
oz-test-helpers | Test utils. Subset of their suite is web3 contracts | ✔️
synthetix | ~1000 units | x

Running synthetix with rc 1.5.0 gives us 6 errors.

https://github.com/Synthetixio/synthetix/tree/v2.45.0
Synthetix version `2.45.0` there already exists 5 failing testcases which can be found here. https://app.circleci.com/pipelines/github/Synthetixio/synthetix/7056/workflows/dbe8bb5b-1634-49f9-b188-6361d3e1814f/jobs/64364

**Comment by Spacesai1or** [comment]
Failing Synthetix tests appear to be unrelated to web3.js, moving forward with release

**Review by luu-alex — DISMISSED** [review]

**Review by GregTheGreek — DISMISSED** [review]

**Review by luu-alex — APPROVED** [review]

**Review by GregTheGreek — APPROVED** [review]
🚀

**Pull request merged**
