### PR TITLE
Release/1.8.1

### PR DESCRIPTION
**Pull request by jdevcs**
### Fixed

-  Fixed types for getPastEvents (#4955) (#5260)
-  Fix Log type by adding missing `removed` property (#4877)

### Changed

- Updated dependencies (#5529)

### CODE REVIEW

**Comment by jdevcs** [comment]
As part of the RC process, following test installations are performed in other projects and running their tests to see if everything.  
+ installs properly
+ builds
+ tests pass

(This list will be actively edited) 

| Project | Desc | Status | 
| ------ | ----- | ----- |
| [oz-test-helpers][1] | Test utils. Subset of their suite is web3 contracts |   |
| [synthetix][2] | ~1000 units |    |


[1]: https://github.com/OpenZeppelin/openzeppelin-test-helpers
[2]: https://github.com/Synthetixio/synthetix

**Comment by jdevcs** [comment]
@Muhammad-Altabba and @luu-alex ,  Could you check Synthetix & OZ  tests and update table above. Thanks

**Comment by luu-alex** [comment]
| Project | Desc | Status | 
| ------ | ----- | ----- |
| [oz-test-helpers][1] | Test utils. Subset of their suite is web3 contracts |  ✅  |
| [synthetix][2] | ~1000 units |   ✅  |

oz-test-helpers passed with no errors, synthetix tests had no new errors.
looks good

**Review by luu-alex — APPROVED** [review]

**Review by nikoulai — APPROVED** [review]

**Comment by Muhammad-Altabba** [comment]
> @Muhammad-Altabba and @luu-alex , Could you check Synthetix & OZ tests and update table above. Thanks

Cloning oz-test-helpers and linking to this version of web3 produced the following new error: 

```
  1) Contract: balance
       current
         returns the current balance of an account as a BN in a specified unit:
     Error: Invalid character
      at assert (/home/maltabba/repos/web3v1.x/node_modules/bn.js/lib/bn.js:6:21)
      at parseBase (/home/maltabba/repos/web3v1.x/node_modules/bn.js/lib/bn.js:274:7)
      at BN._parseBase (/home/maltabba/repos/web3v1.x/node_modules/bn.js/lib/bn.js:298:14)
      at BN.init [as _init] (/home/maltabba/repos/web3v1.x/node_modules/bn.js/lib/bn.js:105:14)
      at new BN (/home/maltabba/repos/web3v1.x/node_modules/bn.js/lib/bn.js:39:12)
      at new BNwrapped (/home/maltabba/repos/web3v1.x/packages/web3-utils/lib/utils.js:480:16)
      at Object.balanceCurrent [as current] (src/balance.js:40:10)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Context.<anonymous> (test/src/balance.test.js:17:14)
```

However, there are other 2 errors that are shown with both this RC and the previous versions (checked with 1.8.0 and 1.2.5). Those errors are:

```
  2) expectRevert
       assertion
         rejects an outOfGas:
     AssertionError: expect.fail()
      at assertFailure (test/helpers/assertFailure.js:9:10)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Context.<anonymous> (test/src/expectRevert.test.js:123:7)

  3) expectRevert
       outOfGas
         accepts an outOfGas:

      Wrong kind of exception received
      + expected - actual

      -Transaction: 0xafa2b1b036c974b23e8c76ce348a4e17eca272f767490372ae9df5c634823e57 exited with an error (status 0) after consuming all gas.
      -     Please check that the transaction:
      -     - satisfies all conditions set by Solidity `assert` statements.
      -     - has enough gas to execute the full transaction.
      -     - does not trigger an invalid opcode by other means (ex: accessing an array out of bounds).
      +out of gas
      
      at expectException (src/expectRevert.js:20:30)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Context.<anonymous> (test/src/expectRevert.test.js:153:7)
``` 

I am using the last version of Ganache.

@luu-alex Did you face similar issues

**Comment by luu-alex** [comment]
@Muhammad-Altabba I believe its similar, the contract: balance failing test persists `1.8.0` and `1.8.1 rc` and might need investigation next update

Running against openzeppelin tests with 1.8.1 rc:
```

  253 passing (2m)
  2 failing

  1) Contract: balance
       current
         returns the current balance of an account as a BN in a specified unit:
     Error: Invalid character
      at assert (node_modules/web3-utils/node_modules/bn.js/lib/bn.js:6:21)
      at parseBase (node_modules/web3-utils/node_modules/bn.js/lib/bn.js:274:7)
      at BN._parseBase (node_modules/web3-utils/node_modules/bn.js/lib/bn.js:298:14)
      at BN.init [as _init] (node_modules/web3-utils/node_modules/bn.js/lib/bn.js:105:14)
      at new BN (node_modules/web3-utils/node_modules/bn.js/lib/bn.js:39:12)
      at new BNwrapped (node_modules/web3-utils/lib/utils.js:480:16)
      at Object.balanceCurrent [as current] (src/balance.js:33:10)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Context.<anonymous> (test/src/balance.test.js:20:19)

  2) expectRevert
       "before each" hook for "rejects if no revert occurs":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/alexluu/openzeppelin-test-helpers/test/src/expectRevert.test.js)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)
```

Running against 1.8.0 open zeppelin
```
 274 passing (1m)
  1 failing

  1) Contract: balance
       current
         returns the current balance of an account as a BN in a specified unit:
     Error: Invalid character
      at assert (node_modules/web3-utils/node_modules/bn.js/lib/bn.js:6:21)
      at parseBase (node_modules/web3-utils/node_modules/bn.js/lib/bn.js:274:7)
      at BN._parseBase (node_modules/web3-utils/node_modules/bn.js/lib/bn.js:298:14)
      at BN.init [as _init] (node_modules/web3-utils/node_modules/bn.js/lib/bn.js:105:14)
      at new BN (node_modules/web3-utils/node_modules/bn.js/lib/bn.js:39:12)
      at new BNwrapped (node_modules/web3-utils/lib/utils.js:480:16)
      at Object.balanceCurrent [as current] (src/balance.js:33:10)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Context.<anonymous> (test/src/balance.test.js:20:19)
```

**Comment by jdevcs** [comment]
> @Muhammad-Altabba I believe its similar, the contract: balance failing test persists `1.8.0` and `1.8.1 rc` and might need investigation next update
> 
These tests should be investigated in next release https://github.com/web3/web3.js/issues/5609

**Pull request merged**
