### PR TITLE
Add function compareBlockNumbers(a, b)

### PR DESCRIPTION
**Pull request by wbt**
## Description
Sometimes it is useful to be able to compare block numbers, which is slightly more complicated than usual because of the option for predefined string block numbers.
This PR offers a starting point for a new function which can help with that.
I located it near other functions that seem logically related.

Collaborative development is invited to address any edge case/logical errors missed in the first draft, the following shortcomings, and unchecked boxes below:
- [ ] Tests should be included.
- [ ] BigNumber parameters should probably be considered.

Until such time as this is merged in with web3, the code may be used in a repository that uses web3 under the same license.

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build-all` and tested the resulting files from `dist` folder in a browser.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [ ] I have tested my code on the live network.

### CODE REVIEW

**Comment by cgewecke** [comment]
This is cool! Can see how it would be really useful. Thanks @wbt.

**Comment by GregTheGreek** [comment]
@wbt any plans to further this?

**Comment by wbt** [comment]
@GregTheGreek I think it would be good for someone else more familiar with the codebase and build process to pick it up from here.  (For example, I don't know how to unjam the required stuck tests.)  I think this is a useful contribution toward a collaborative development effort, but I don't have the bandwidth to do it all myself at present.  Would you like to pick it up?

**Comment by GregTheGreek** [comment]
This has been superseded by #3682

**Pull request closed without merging**
