### PR TITLE
Rewrite web3 eth iban

### PR DESCRIPTION
**Pull request by loredanacirstea**
## Description

fixes https://github.com/ChainSafe/web3.js/issues/3932

- Start with `web3-eth-iban` v. 1.3.5
- use .ts files
- remove `dtslint`, generate types from .ts files, add `eslint` rules ; Note - `dtslint` was left as a package.json command, for consistency with other packages
- move unit tests inside package 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

No errors when running the following from package root.
```
npm run compile
npm run dtslint
```

No errors when running the following from monorepo root:
```
lerna run --scope web3-eth-iban test:unit
```

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [x] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [x] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

### CODE REVIEW

**Comment by loredanacirstea** [comment]
@frankiebee , ready for a first review.

**Comment by loredanacirstea** [comment]
@frankiebee, is the web3 team open to external contributions for this refactoring or have I lost my time?

**Comment by GregTheGreek** [comment]
@loredanacirstea sorry for the delay, we've been focusing on a 3.x (no bzz and shh) and 4.x (typescript) release while trying to LTS 1.x. 

We've abandoned our effort to add typescript to 1.x since we want to fully gut the code of its mess.

**Comment by GregTheGreek** [comment]
@spacesailor24 Lets change the base branch to 4.x and use it in the rewrite!

**Comment by loredanacirstea** [comment]
closing in favor of https://github.com/ChainSafe/web3.js/pull/4071

**Pull request closed without merging**
