### PR TITLE
Added a simple DApp to the examples folder.

### PR DESCRIPTION
**Pull request by MoreHotSauce**
I added a example decentralized application example. The code should be pretty simple and easy to understand. The contract has two simple functions, one that adds data and one that can retrieve it. I made this to give beginners a head start in making there own Dapps. I also provided information as to how to run this code in the READme.md

### CODE REVIEW

**Comment by frozeman** [comment]
The dapp looks good but the contract code is not deployed, and i cant merge that without seeing the contract code with source code on etherscan.

Also the develop branch will soon be replaced by the 1.0 one

**Comment by niketp03** [comment]
@frozeman Thanks, I just added the source code onto etherscan(https://ropsten.etherscan.io/address/0xecb2ea404cb3226781500d655140063e20da07c6) and updated the READme.md.

**Comment by SVDotsenko** [comment]
can you rewrite this sample to intaract with contract deployed into Ropsten, espeacially intresting how to run change state methods (setters) from js (front-end). Thank you in advance.

**Comment by niketp03** [comment]
@SVDotsenko not sure what you mean by that. This contract currently is deployed on ropsten and the js does include both getters and setters.

**Comment by nivida** [comment]
@MoreHotSauce hay could you please create a separate repository for this? and maybe with version 1.0 of web3? I've closed this PR because I don't think this should be a part of this repo and also because it is not created with 1.0 :)

**Pull request closed without merging**
