### PR TITLE
Fix: BSC - get transaction with gasLimit over 53 bits

### LINKED ISSUE #3745: Error while decode transaction gas: "Number can only safely store up to 53 bits"
I tried decode transaction from block but got a error 

```
Number can only safely store up to 53 bits
	at assert ./node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:6
	at BN.toNumber ./node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:506
	at Object.hexToNumber ./node_modules/web3-core-helpers/node_modules/web3-utils/lib/utils.js:208
	at Method.outputTransactionFormatter [as outputFormatter] ./node_modules/web3-core-helpers/lib/formatters.js:204
	at Method.formatOutput ./node_modules/web3-core-method/lib/index.js:147
	at sendTxCallback ./node_modules/web3-core-method/lib/index.js:523
	at ./node_modules/web3-core-requestmanager/lib/index.js:293
	at XMLHttpRequest.request.onreadystatechange ./node_modules/web3-providers-http/lib/index.js:98
	at XMLHttpRequestEventTarget.dispatchEvent ./node_modules/xhr2-cookies/xml-http-request-event-target.ts:44
	at XMLHttpRequest._setReadyState ./node_modules/xhr2-cookies/xml-http-request.ts:219
	at XMLHttpRequest._onHttpResponseEnd ./node_modules/xhr2-cookies/xml-http-request.ts:345
	at IncomingMessage.<anonymous> ./node_modules/xhr2-cookies/xml-http-request.ts:311
	at IncomingMessage.emit events.js:326
	at endReadableNT _stream_readable.js:1252
	at processTicksAndRejections internal/process/task_queues.js:80
```

error occur with tx id `0xe0db32759810271eec05326a4c96fbb42a185139134e16b4581f77456df226a9`

if look closely on https://bscscan.com/tx/0xe0db32759810271eec05326a4c96fbb42a185139134e16b4581f77456df226a9

we can see that gas equal `9,223,372,036,854,775,807`, so web3 js can't convert this string to number 

Anyone has idea how resolve this problem? 

```
import Web3 from 'web3';

async function main() {
  const web3 = new Web3('https://bsc-dataseed1.binance.org:443');

  const res = await web3.eth.getBlock(1365710);

  await Promise.all(
    res.transactions.map(async (txId) => {
      try {
        const tx = await web3.eth.getTransaction(txId);

        console.log(`decode ${txId}`);
      } catch (error) {
        console.error(`error decode ${txId}`);
      }
    }),
  );
}

main();
```

### LINKED ISSUE #3912: web3.eth.getBlock() throw Error: Number can only safely store up to 53 bits
#### Expected behavior

Call function `web3.eth.getBlock(number, true)` without error.

#### Actual behavior

Call function `web3.eth.getBlock(number, true)` throw error `Error: Number can only safely store up to 53 bits`.

#### Steps to reproduce the behavior

```js
let provider = new Web3.providers.WebsocketProvider('ws://somewhere.com')
let web3 = new Web3(provider)
let block = await web3.eth.getBlock(595091, true)
```
#### Logs

```bash
Error: Number can only safely store up to 53 bits
    at assert (/home/kevin/package/bsc-txs-crawler/node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:6:21)
    at BN.toNumber (/home/kevin/package/bsc-txs-crawler/node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:506:7)
    at Object.hexToNumber (/home/kevin/package/bsc-txs-crawler/node_modules/web3-utils/lib/utils.js:208:24)
    at outputTransactionFormatter (/home/kevin/package/bsc-txs-crawler/node_modules/web3-core-helpers/lib/formatters.js:205:20)
    at /home/kevin/package/bsc-txs-crawler/node_modules/web3-core-helpers/lib/formatters.js:269:24
    at Array.forEach (<anonymous>)
    at Method.outputBlockFormatter [as outputFormatter] (/home/kevin/package/bsc-txs-crawler/node_modules/web3-core-helpers/lib/formatters.js:267:28)
    at Method.formatOutput (/home/kevin/package/bsc-txs-crawler/node_modules/web3-core-method/lib/index.js:147:54)
    at sendTxCallback (/home/kevin/package/bsc-txs-crawler/node_modules/web3-core-method/lib/index.js:523:33)
    at Object.callback (/home/kevin/package/bsc-txs-crawler/node_modules/web3-core-requestmanager/lib/index.js:308:9)
    at /home/kevin/package/bsc-txs-crawler/node_modules/web3-providers-ws/lib/index.js:114:45
    at Array.forEach (<anonymous>)
    at WebsocketProvider._onMessage (/home/kevin/package/bsc-txs-crawler/node_modules/web3-providers-ws/lib/index.js:102:69)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/kevin/package/bsc-txs-crawler/node_modules/yaeti/lib/EventTarget.js:115:12)
    at W3CWebSocket.onMessage (/home/kevin/package/bsc-txs-crawler/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/home/kevin/package/bsc-txs-crawler/node_modules/websocket/lib/W3CWebSocket.js:205:19)
```

#### Environment

* Ubuntu 18.04.5 LTS
* Node.js v14
* web3js v1.3.4, also tried with versions v1.3.1 and v1.3.2.

### LINKED ISSUE #3936: BSC - certain tx values break web3
#### Expected behavior

this tx: https://bscscan.com/vmtrace?txhash=0xea6d2f025d6c2135b93d2c74a2a992c2ed80aac780298c1288b1addc2b6eb4d2&type=gethtrace2

i expect no errors when calling web3.eth.getTransaction(txhash)

#### Actual behavior

```
> web3.eth.getTransaction('0xea6d2f025d6c2135b93d2c74a2a992c2ed80aac780298c1288b1addc2b6eb4d2')
Promise { <pending> }
> (node:1992) UnhandledPromiseRejectionWarning: Error: Number can only safely store up to 53 bits
    at assert (/home/user/doodoocrap/node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:7:21)
    at BN.toNumber (/home/user/doodoocrap/node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:508:7)
    at Object.hexToNumber (/home/user/doodoocrap/node_modules/web3-utils/lib/utils.js:209:24)
    at Method.outputTransactionFormatter [as outputFormatter] (/home/user/doodoocrap/node_modules/web3-core-helpers/lib/formatters.js:204:20)
    at Method.formatOutput (/home/user/doodoocrap/node_modules/web3-core-method/lib/index.js:147:54)
    at sendTxCallback (/home/user/doodoocrap/node_modules/web3-core-method/lib/index.js:523:33)
    at Object.callback (/home/user/doodoocrap/node_modules/web3-core-requestmanager/lib/index.js:308:9)
    at /home/user/doodoocrap/node_modules/web3-providers-ws/lib/index.js:114:45
    at Array.forEach (<anonymous>)
    at WebsocketProvider._onMessage (/home/user/doodoocrap/node_modules/web3-providers-ws/lib/index.js:102:69)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/user/doodoocrap/node_modules/yaeti/lib/EventTarget.js:115:12)
    at W3CWebSocket.onMessage (/home/user/doodoocrap/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/home/user/doodoocrap/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:315:20)
    at WebSocketConnection.EventEmitter.emit (domain.js:529:15)
    at WebSocketConnection.processFrame (/home/user/doodoocrap/node_modules/websocket/lib/WebSocketConnection.js:554:26)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1992) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1992) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

#### Steps to reproduce the behavior

try to run the getTransaction() listed above

#### Logs

the number-to-bn lib has this func

```
  BN.prototype.toNumber = function toNumber () {
    //console.log(this)
    var ret = this.words[0];
    if (this.length === 2) {
      ret += this.words[1] * 0x4000000;
    } else if (this.length === 3 && this.words[2] === 0x01) {
      // NOTE: at this stage it is known that the top bit is set
      ret += 0x10000000000000 + (this.words[1] * 0x4000000);
    } else if (this.length > 2) {
      assert(false, 'Number can only safely store up to 53 bits');
    }
    return (this.negative !== 0) ? -ret : ret;
  };
```

which is called in some utils.js from web3

```
var hexToNumber = function (value) {
    //console.log(toBN(value).toNumber())
    if (!value) {
        return value;
    }
    if (_.isString(value) && !isHexStrict(value)) {
        throw new Error('Given value "' + value + '" is not a valid hex string.');
    }
    return toBN(value).toNumber();
};
```

that tx value returns a len of 3

```
> numberToBN(0x1db4679213a080)
BN {
  negative: 0,
  words: [ 34840704, 57481700, 1, <1 empty item> ],
  length: 3,
  red: null
}
```

so that error gets throw and web3 ignores that tx

#### Environment

ubuntu 18
node 14
latest web3

### PR DESCRIPTION
**Pull request by alstjd0921**
## Description

Fix outputTransactionFormatter to format gas limit hex string to decimal string.

There are a lot of transactions in the BSC network that have set gas limit by 9,223,372,036,854,775,807 and I think it is necessary to switch to string format for look up these transactions.

The links below are examples of such transactions.
[0xb48fbbab4feee817b18efdbde134dba83ba47ea479ab85a2b3ff068bf7c8f5d8](https://bscscan.com/tx/0xb48fbbab4feee817b18efdbde134dba83ba47ea479ab85a2b3ff068bf7c8f5d8)
[0x02a3e52e32d1433f2d356ddf1408c3d9fb916c0a244f18e8a90ba742f45ae32a](https://bscscan.com/tx/0x02a3e52e32d1433f2d356ddf1408c3d9fb916c0a244f18e8a90ba742f45ae32a)
[0x65f46d95e70b1906694dbaaccaad12c2ffa9ae5c2a6513719837f50c9f97940a](https://bscscan.com/tx/0x65f46d95e70b1906694dbaaccaad12c2ffa9ae5c2a6513719837f50c9f97940a)

Fixes #3936
Fixes #3912
Fixes #3745

## Type of change

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Review by Spacesai1or — CHANGES_REQUESTED** [review]
Hi there, thank you for submitting this PR!
Our team has discussed fixing this in a subsequent major release, but we greatly appreciate the work that you did!

Additionally, if you wouldn't mind updating the `CHANGELOG.md` since we can't do it for you

Thank you again for your contributions!

**Comment by Spacesai1or** [comment]
@frankiebee @koraykoska moving the discussion to here:

We previously discussed returning a hex string, but this PR uses an [included method](https://github.com/ChainSafe/web3.js/blob/334c039ca53e7a47488e2c3ef75d0876d09e33b6/packages/web3-core-helpers/src/formatters.js#L70) to format to a number string. Do we prefer a hex string over using existing util functions?

**Comment by alstjd0921** [comment]
> Hi there, thank you for submitting this PR!
> Our team has discussed fixing this in a subsequent major release, but we greatly appreciate the work that you did!
> 
> Additionally, if you wouldn't mind updating the `CHANGELOG.md` since we can't do it for you
> 
> Thank you again for your contributions!

@spacesailor24 `CHANGELOG.md` updated!

**Comment by Spacesai1or** [comment]
Thanks for updating it so quickly!
Unfortunately we'd need to include it in a separate major version, but I'm not sure if this will be 3.x or something else. So, you can hold off on updating `CHANGELOG.md` again till we can clarify what version this will be included in

**Comment by alstjd0921** [comment]
@spacesailor24 I see. However, many users are complaining about this issue. I hope this changes included in the release version ASAP.

**Comment by aslvrstn** [comment]
I think there are a number of other formatters that need this change as well. Notably `outputBlockFormatter` at https://github.com/ChainSafe/web3.js/blob/1.x/packages/web3-core-helpers/src/formatters.js#L302 and `outputTransactionReceiptFormatter` at https://github.com/ChainSafe/web3.js/blob/1.x/packages/web3-core-helpers/src/formatters.js#L274

As-is, I don't think this fixes https://github.com/ChainSafe/web3.js/issues/3912 for instance.

Thanks for the change! This has been driving me crazy.

**Comment by Spacesai1or** [comment]
@aslvrstn oof, thank you for bringing this to our attention, should've looked around for more instances of this bug
I think we should bundle these all in the same major release, but that shouldn't slow things down - probably

**Comment by alstjd0921** [comment]
@aslvrstn Thanks for review.
In my analysis, the abnormally high gasLimit value is specified only in the transaction, and the gasLimit aggregated from the block does not add up this value. Its weird but, this change can fix #3912 i think.
Also, transactions with these abnormal gasLimit values were all zero-fee transactions. `outputTransactionReceiptFormatter` will not cause an error because the transactionReceipt does not contain abnormal gasLimit value.

**Comment by aslvrstn** [comment]
The gas limit aggregated in the block might not be added up, but when called with `returnTransactionObjects=true` it still seemed broken to me .. do the transactions returned in the getBlock call use a different formatter?

Anyway, I only noticed because I actually tried installing from your branch and re-running the failed call, and it still seemed to fail, so unless I botched the install, I think at least one other location needs to be updated.

Thanks for turning that patch around so quickly, btw! I would have been going insane otherwise.

**Comment by alstjd0921** [comment]
https://github.com/ChainSafe/web3.js/blob/1.x/packages/web3-core-helpers/src/formatters.js#L314
Transactions returned in the getBlock call use a same formatter

Following captures are the results of call 'web3.eth.getBlock (5591908, true)'
Please make sure you have built the right branch. I'm glad it helped!

image
image

**Comment by alstjd0921** [comment]
@aslvrstn  https://github.com/ChainSafe/web3.js/blob/1.x/packages/web3-core-helpers/src/formatters.js#L314
Transactions returned in the getBlock call use a same formatter

Following captures are the result of call 'web3.eth.getBlock (5591908, true)' using modified formatter. (BSC Network)
Please make sure you have built the right branch. I'm glad it helped!

image
image

**Comment by tima-t** [comment]
Is it fine, If I create a fork of web3 with this change and deploy new npm package called something like  web3-bsc. 
Does the license allow it? 

I just need this modification for one of our projects that uses BSC.

Another option is if you are planning to merge this PR in the next few days. 

Thanks!

**Comment by Spacesai1or** [comment]
Commenting here as well, so this isn't lost:

Waiting on @alstjd0921 to merge [this](https://github.com/alstjd0921/web3.js/pull/1), then we can merge this PR

**Comment by aslvrstn** [comment]
Along @tima-t 's request: how are people installing this as a temporary dependency and having the fix come in? I've been trying variations from https://stackoverflow.com/questions/17509669/how-to-install-an-npm-package-from-github-directly and yet it still seems to be pulling in old web3-core-helpers dependencies or something, because despite the code I see being updated, the code the browser gets is clearly the old hexToNumber version.

I know this is largely unrelated, but it'd really help to have a clear short-term workaround, including pushing an early 3.x release, or allowing a web3-bsc module to be published.

**Comment by Spacesai1or** [comment]
#3976 was merged so the 3.0.0 RC can be released

**Comment by phpnikolov** [comment]
Easy temporary fix:
1. Open file **.\node_modules\number-to-bn\node_modules\bn.js\lib\bn.js**
2. Go to line 506 **assert(false, 'Number can only safely store up to 53 bits');**
3. Replace it with **ret = Number.MAX_SAFE_INTEGER;**

**Comment by krunkosaurus** [comment]
@phpnikolov Wow thanks. This worked perfectly!

**Comment by hoangvnextdev** [comment]
@spacesailor24 can you create PR to fix web3 1.3.x too ? I can't modify node_modules to fix this .

**Comment by Spacesai1or** [comment]
@hoangvnextdev Unfortunately we cannot apply this fix to the `1.x` branch, because this is considering a breaking change (since we're returning a number string instead of a number now). To apply these changes right now, you must specifically use the
 `3.0.0-rc.4` version as the `3.x` branch will contain these fixes

**Comment by s29papi** [comment]
@spacesailor24 Help please, I have made this change to my node module but I am still getting this error. I think my direct changes in the module didn't reflect, please help   @phpnikolov just to add the error is emitted from web3-core-helpers errors.js ( I also made the changes here)

**Comment by hoangvnextdev** [comment]
@nots29vv Hi i think when you reinstall node_modules your modify is change back to origin ? Because i use @phpnikolov solution is worked for me. But I change to using ethersjs more stable than web3

**Comment by s29papi** [comment]
@hoangvnextdev that is right. moving to ethersjs would not be possible for me, as i am trying to implement gasless transactions using @opengsn and web3 is a dependency for the package. I really appreciate.

**Comment by itxtoledo** [comment]
using 3.0.0-rc.4 i can use this in BSC but is pretty cool to have this fix in main version

**Comment by francesco-clementi-92** [comment]
Hi guys, any news on the fix? Which version should I use?

**Comment by christianestrella-himari** [comment]
> Hi guys, any news on the fix? Which version should I use?

I had to create a prebuild script for replace some strings, includes the path because it fails after build an run an electron app :/

**Comment by tiendq** [comment]
> Hi guys, any news on the fix? Which version should I use?

Is it reported in `number-to-bn` or `bn.js` repos? why don't they fix it?

**Comment by stychu** [comment]
> Easy temporary fix:
> 
> 1. Open file **.\node_modules\number-to-bn\node_modules\bn.js\lib\bn.js**
> 2. Go to line 506 **assert(false, 'Number can only safely store up to 53 bits');**
> 3. Replace it with **ret = Number.MAX_SAFE_INTEGER;**

As long as this solution works this is insane that this error still occurs. How this is not fixed yet?

**Comment by Mehranh** [comment]
Pleaaaaase fix this error

**Comment by goodstemy** [comment]
Have the same error execute `getTransaction(...tx)` on BSC network. Anyone have an idea when it will be fixed?

**Comment by goodstemy** [comment]
Also for people who want to find a solution rn: https://github.com/ChainSafe/web3.js/issues/3936#issuecomment-797342613

Its solve my problem by extending new method.

**Comment by htkcodes** [comment]
+ 1 plus for this fix #3936

**Comment by lucaspiressimao** [comment]
Same here but 

> Also for people who want to find a solution rn: [#3936 (comment)](https://github.com/ChainSafe/web3.js/issues/3936#issuecomment-797342613)
> 
> Its solve my problem by extending new method.

this solve for now

**Comment by spartanz51** [comment]
> Have the same error execute `getTransaction(...tx)` on BSC network. Anyone have an idea when it will be fixed?

It will not be fixed, see https://github.com/ChainSafe/web3.js/pull/3789#issuecomment-770925044

**Pull request closed without merging**
