### PR TITLE
NewHeadsWatcher updated for CustomProvider

### LINKED ISSUE #2462: [1.0.0-beta.48] Contract.methods.myMethod.send() hangs forever
### Description 
I'm using HDWalletProvider with Infura API, and when I use HTTP API like

```
const web3 = new Web3(new HDWalletProvider(P_KEY, `https://${NETWORK}.infura.io/v3/${INFURA_API_KEY}`));
const contract = new web3.eth.Contract(ABI, CONTRACT_ADDRESS);
contract.methods.transfer(ETH_ADDRESS, 12345).send(defaultOption)
    .on('receipt', (res) => { ... });
```

This sends the transaction correctly, but crashes after with

> Error: Subscriptions are not supported with the CustomProvider.

I saw "The HTTP provider is deprecated" on the web3 document, so I changed the Infura endpoint using Websocket:

```
const web3 = new Web3(new HDWalletProvider(P_KEY, `wss://${NETWORK}.infura.io/ws/v3/${INFURA_API_KEY}`));
```

This doesn't send the transaction at all and just hangs forever (no error, nothing happens).

#### Expected behavior
Calling 
```
contract.methods.transfer(ETH_ADDRESS, 12345).send(defaultOption).on('receipt', (res) => { ... });
```
should sent the transaction and `receipt` event should be triggered.

#### Actual behavior
It doesn't send the transaction and `receipt` event doesn't get triggered.

### Versions 
* web3.js: 1.0.0-beta.48
* nodejs: v11.10.1
* browser: console
* ethereum node: Infura websocket

### PR DESCRIPTION
**Pull request by nivida**
## Description

Fixes #2462 

## Type of change

- [x] Bug fix 

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no warnings.
- [x] I have updated or added types for all modules I've changed
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran ```npm run test``` in the root folder with success and extended the tests if necessary.
- [x] I ran ```npm run build``` in the root folder and tested it in the browser and with node.
- [x] I ran ```npm run dtslint``` in the root folder and tested that all my types are correct
- [x] I have tested my code on an ethereum test network.

### CODE REVIEW

**Comment by selectstarfrom** [comment]
To use this version(_2462 fix_), 
in my package.json, I replaced 
**`"web3": "^1.0.0-beta.48"`**
with 
**`"web3": "git+https://github.com/ethereum/web3.js.git"`**

With the above change, I'm not sure how to import **web3**  in deploy file.
The statement was `const Web3 = require('web3');` which is not working now.

Can anyone please tell me how to import web3 in deploy.js file from module added via git-url.

**Comment by selectstarfrom** [comment]
I want to avail this version in my nodejs application.
As this fix(2462) is yet to be released, I have to use from branch 1.0 as the fix is already merged to 1.0.

So, can anyone please tell me how to use web3-branch-1.0 in my nodejs application?

The statement was const Web3 = require('web3'); which is not working now.

how to import Web3 constructor in deploy.js file.

**Comment by ahmedahmado** [comment]
hello nivida,
@nivida could you please explain what i should do with this file , as i mentioned before i have not much experience. should i replace it with my file and where can i find them ?

**Comment by iheqi** [comment]
So what time to merge it to next tag?

**Comment by iheqi** [comment]
> I want to avail this version in my nodejs application.
> As this fix(2462) is yet to be released, I have to use from branch 1.0 as the fix is already merged to 1.0.
> 
> So, can anyone please tell me how to use web3-branch-1.0 in my nodejs application?
> 
> The statement was const Web3 = require('web3'); which is not working now.
> 
> how to import Web3 constructor in deploy.js file.

Did you found the answer? I want to know, too.
And why nivida not merge this fix to next tag?

**Comment by iheqi** [comment]
> I want to avail this version in my nodejs application.
> As this fix(2462) is yet to be released, I have to use from branch 1.0 as the fix is already merged to 1.0.
> 
> So, can anyone please tell me how to use web3-branch-1.0 in my nodejs application?
> 
> The statement was const Web3 = require('web3'); which is not working now.
> 
> how to import Web3 constructor in deploy.js file.

[See this](https://stackoverflow.com/questions/46661726/webpack-cant-import-package-installed-from-git)

**Pull request merged**
