### PR TITLE
Bump  web3-providers-ipc oboe version to 2.1.5

### PR DESCRIPTION
**Pull request by maaktweluit**
## Description

Please include a summary of the changes and be sure to follow our [Contribution Guidelines](../CONTRIBUTIONS.md).

So it does not pack 8 MB of test files in its npm package https://github.com/jimhigson/oboe.js/pull/172

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [x] I have updated the `CHANGELOG.md` file in the root folder.

### CODE REVIEW

**Comment by ryanio** [comment]
@maaktweluit nice, thanks for this PR! would you mind adding an entry in the CHANGELOG.md?

**Comment by maaktweluit** [comment]
@ryanio Anytime! Thanks for the quick reply!

Updated changelog.md and checked the box in the description

**Review by GregTheGreek — DISMISSED** [review]
LGTM

**Comment by ryanio** [comment]
Ok this looks good! I realized though that we also need to commit the updated package-lock for web3-providers-ipc. @maaktweluit do you mind adding that?

**Review by frankiebee — CHANGES_REQUESTED** [review]
Please commit package-lock for deps bumps

**Comment by maaktweluit** [comment]
@ryanio @frankiebee Yes, will add the `package-lock` updates later today when I am finished with my current task :)

**Review by GregTheGreek — APPROVED** [review]

**Review by frankiebee — APPROVED** [review]
thank you!

**Pull request merged**
