### PR TITLE
Support for wss:// providers using ws library

### PR DESCRIPTION
**Pull request by learner-long-life**
## Description

Current websocket providers only support insecure websocket over HTTP.
However, this prevents the use of Whisper and Ethereum nodes (for real-time event updates) on static site hosts such as Netlify and GitHub Pages, which enforce HTTPS page loads and a consequent CORS policy preventing mixed HTTP/HTTPS websockets.

This change allows Secure Websocket providers, via the newer / smaller / faster websocket library `ws` rather than `w3cwebsocket`, indicated by the `wss://` URL scheme.

We have also provided a public Whisper node on Rinkeby for testing at wss://whisper.arcology.nyc:8547 and plan to provide a Mainnet node as well for production use to the community in the near future.

## Comments on Original Design

It may have been an original design intention of Whisper to require each dapp to run its own ws/http behind its own firewall and/or on its own cloud intranet, making unencrypted HTTP / JSONRPC requests less of a security risk. However, this limits the usefulness of Whisper or real-time Ethereum updates of blockchain events and increases centralized company overhead by forcing each dapp to run its own infrastructure, and then forcing all users to connect via the dapp's servers rather than directly from their browsers / clients, with each other in a peer-to-peer fashion.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran ```npm run dtslint``` with success and extended the tests and types if necessary.
- [x] I ran ```npm run test:unit``` with success.
- [ ] I have executed ``npm run test:cov`` and my test cases do cover all lines and branches of the added code.
- [ ] I ran ```npm run build-all``` and tested the resulting file/'s from  ```dist``` folder in a browser.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [ ] I have tested my code on the live network.

### CODE REVIEW

**Comment by cgewecke** [comment]
@cryptogoth Thanks for opening.

Could you go into greater detail about what problems you're seeing using Web3 with `wss`? 

For context, Web3 runs some [basic tests][1] calling Infura over wss that can be seen working in Travis CI [here][2]. 

[1]: https://github.com/ethereum/web3.js/blob/a6ddec59e65116853435f203b25cb9c55824d084/scripts/js/basic_usage.js#L60-L63
[2]: https://travis-ci.org/ethereum/web3.js/jobs/656246963#L1079-L1104

**Comment by learner-long-life** [comment]
Sure @cgewecke I believe that existing `wss://` support works for Infura Ethereum nodes, but not for Whisper nodes or other future `wss` services, of which there aren't yet very many (mine is the only one I know of).

I was able to reproduce the error with the current `1.2.6` version of `web3` with the following scripts:
```
Web3 = require('web3')
web3 = new Web3('wss://whisper.arcology.nyc:8547')
web3.shh.getInfo().then((val) => console.log(val))
```
after a timeout, it will display
```
> connection not open on send()
connection not open on send()
(node:65808) UnhandledPromiseRejectionWarning: Error: connection not open
    at WebsocketProvider.send (/Users/ppham/src/blockchain/whisper-client/node_modules/web3-providers-ws/src/index.js:282:18)
    at Timeout._onTimeout (/Users/ppham/src/blockchain/whisper-client/node_modules/web3-providers-ws/src/index.js:267:19)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
(node:65808) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:65808) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit
code.
(node:65808) UnhandledPromiseRejectionWarning: Error: connection not open
    at WebsocketProvider.send (/Users/ppham/src/blockchain/whisper-client/node_modules/web3-providers-ws/src/index.js:282:18)
    at Timeout._onTimeout (/Users/ppham/src/blockchain/whisper-client/node_modules/web3-providers-ws/src/index.js:267:19)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
(node:65808) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

However, the mods from my change, after they have been built with `yarn build` and copied into `node_modules/web3/dist/web3.min.js` of the project above, would output the following to the same call to `web3.shh.getInfo()`:
```
{ memory: 0, messages: 0, minPow: 0.2, maxMessageSize: 1048576 }
```

**Comment by cgewecke** [comment]
@cryptogoth 

Just tried your endpoint and it worked...can you see any recent reqs on your side? I ran `getInfo` 4x and `newKeyPair` 3x. 

```js
// Running as a node script...
web3 = new Web3('wss://whisper.arcology.nyc:8547');
const val = await web3.shh.newKeyPair();
```
```sh
> 30c5e9508cedf99e9a0c775b21baa26c8d56ef169f5e7c3808094cdb5b697597
```

Shot in the dark, but one difference I notice between `w3cwebsocket` and `ws` is that the headers are set a little differently...
+ [headers at ws][1]
+ [headers at w3cwebsocket][2]
+ how to [set headers][3] for Web3 WebsocketProvider

[1]: https://github.com/websockets/ws/blob/5fcdc42ef76d2d0ab920aa37631468e6f1066bcd/lib/websocket.js#L501-L507
[2]: https://github.com/web3-js/WebSocket-Node/blob/905deb4812572b344f5801f8c9ce8bb02799d82e/lib/WebSocketClient.js#L191-L209
[3]: https://github.com/ethereum/web3.js/tree/1.x/packages/web3-providers-ws#usage

**Comment by learner-long-life** [comment]
@cgewecke interesting. I did verify receiving three `newKeyPair` requests, with these results, the last one matching your key ID above:
```
ws received: {"jsonrpc":"2.0","id":1,"method":"shh_newKeyPair","params":[]}
{"jsonrpc":"2.0","id":1,"result":"6b44e3253c642faf22ca6d95cf6abaaefda847db337cc7a45040fe700ac07b5e"}
ws received: {"jsonrpc":"2.0","id":1,"method":"shh_newKeyPair","params":[]}
Received loopback data, sending back publicly {"jsonrpc":"2.0","id":1,"result":"38edd9a8c30ec1e0191f82c43a61bcd2aeea37c0aba4a8f4c9df986766cfb942"}
ws received: {"jsonrpc":"2.0","id":1,"method":"shh_newKeyPair","params":[]}
Received loopback data, sending back publicly {"jsonrpc":"2.0","id":1,"result":"30c5e9508cedf99e9a0c775b21baa26c8d56ef169f5e7c3808094cdb5b697597"}
```

Were you able to connect to my whisper node using unmodified (`w3cwebsocket`) `web3.js` 1.2.6,
or using my PR? Thanks for the links, I'll read up there and see if there's some header that might help `w3csocket` behave more like `ws` for me, without changing libraries.

I'll also log more header details on my server side.

**Comment by cgewecke** [comment]
@cryptogoth Yes, I used `web3.js 1.2.6`.... I didn't try in a browser or with a minified bundle though. Are you behind a proxy when you make the calls or anything?

**Comment by learner-long-life** [comment]
@cgewecke my mistake, I'm not able to repro the connection timeout anymore. It's possible I was using a slightly older version of `1.x`, or the very old web.js version `0.20.x` provided by Metamask.

I've tested with a minified bundle in the browser, and also in Node.js like you, and they all passed. I'll close out. Thanks for working through this with me.

**Pull request closed without merging**
