### PR TITLE
Release/1.3.1

### PR DESCRIPTION
**Pull request by GregTheGreek**
### Description

This release candidate fixes some errors throughout the codebase, and patches some security vulnerabilities.

We're also extremely excited to finally announce that web3.js has support for the eth2 beaconchain API! It should be noted that the eth2 API will follow the web3.js versioning and start at v1.3.1 (upon formally release next week) and should be considered an alpha release. It also will not bloat the existing web3 object, and was not imported into it. In order to use the eth2 beaconchain API please install it separately using `npm install --save web3-eth2-beaconchain`!

### Added

- Add `web3-eth2-core` package (#3743)
- Add `web3-eth2-beaconchain` package (#3743)

### Changed

- bump utils 0.10.0^ -> 0.12.0 (#3733)

### Removed

- Removed post-install script in `packages/web3`. Added documentation to root README (#3717)

### Fixed

- Fix possible unhandled promise rejection when sending a transaction (#3708)
- Fixed decoding bytes and string parameters for logs emitted with solc 0.4.x (#3724, #3738)
- Grammar changes to inputAddressFormatter error message
- Fixed vulnerable dependencies

### CODE REVIEW

**Comment by Spacesai1or** [comment]
Replicating the steps mentioned in [previous releases](https://github.com/ethereum/web3.js/pull/3633#issuecomment-656217052)

As part of the RC process, am doing some test installations in other projects and running their tests to see if everything.  
+ installs properly
+ builds
+ tests pass

(This list will be actively edited) 

| Project | Desc | Status | 
| ------ | ----- | ----- |
| [oz-test-helpers][1] | Test utils. Subset of their suite is web3 contracts | ✔️  |
| [synthetix][2] | ~1000 units | ✔️ |

[1]: https://github.com/OpenZeppelin/openzeppelin-test-helpers
[2]: https://github.com/Synthetixio/synthetix

[oz-test-helpers][1] fails with the following (not sure if this is related to the RC):

**UPDATE** Testing are passing as of 10/30/2020

```javascript
259 passing (1m)
  4 failing

  1) Contract: expectEvent (web3 contracts) 
       default
         with events containing indexed parameters
           "before each" hook for "accepts events emitted by the directly called contract":
     Error: invalid number value (arg="indexedValue", coderType="uint256", value="2a")
      at Object.throwError (node_modules/web3-eth-abi/node_modules/ethers/utils/errors.js:68:17)
      at CoderNumber.encode (node_modules/web3-eth-abi/node_modules/ethers/utils/abi-coder.js:353:20)
      at /home/anon/tmp/openzeppelin-test-helpers/node_modules/web3-eth-abi/node_modules/ethers/utils/abi-coder.js:605:59
      at Array.forEach (<anonymous>)
      at pack (node_modules/web3-eth-abi/node_modules/ethers/utils/abi-coder.js:604:12)
      at CoderTuple.encode (node_modules/web3-eth-abi/node_modules/ethers/utils/abi-coder.js:764:16)
      at AbiCoder.encode (node_modules/web3-eth-abi/node_modules/ethers/utils/abi-coder.js:897:77)
      at ABICoder.encodeParameters (node_modules/web3-eth-abi/src/index.js:96:27)
      at /home/anon/tmp/openzeppelin-test-helpers/node_modules/web3-eth-contract/src/index.js:426:24
      at Array.map (<anonymous>)
      at Object._encodeMethodABI (node_modules/web3-eth-contract/src/index.js:425:12)
      at Object._processExecuteArguments (node_modules/web3-eth-contract/src/index.js:741:39)
      at Object._executeMethod (node_modules/web3-eth-contract/src/index.js:766:54)
      at Context.<anonymous> (test/src/expectEvent.web3.test.js:350:11)
      at processImmediate (internal/timers.js:456:21)

  2) Contract: expectEvent (web3 contracts) 
       default
         with events containing conflicting indexed parameters
           "before each" hook for "accepts events emitted by the directly called contract":
     Error: invalid number value (arg="indexedValue1", coderType="uint256", value="2a")
      at Object.throwError (node_modules/web3-eth-abi/node_modules/ethers/utils/errors.js:68:17)
      at CoderNumber.encode (node_modules/web3-eth-abi/node_modules/ethers/utils/abi-coder.js:353:20)
      at /home/anon/tmp/openzeppelin-test-helpers/node_modules/web3-eth-abi/node_modules/ethers/utils/abi-coder.js:605:59
      at Array.forEach (<anonymous>)
      at pack (node_modules/web3-eth-abi/node_modules/ethers/utils/abi-coder.js:604:12)
      at CoderTuple.encode (node_modules/web3-eth-abi/node_modules/ethers/utils/abi-coder.js:764:16)
      at AbiCoder.encode (node_modules/web3-eth-abi/node_modules/ethers/utils/abi-coder.js:897:77)
      at ABICoder.encodeParameters (node_modules/web3-eth-abi/src/index.js:96:27)
      at /home/anon/tmp/openzeppelin-test-helpers/node_modules/web3-eth-contract/src/index.js:426:24
      at Array.map (<anonymous>)
      at Object._encodeMethodABI (node_modules/web3-eth-contract/src/index.js:425:12)
      at Object._processExecuteArguments (node_modules/web3-eth-contract/src/index.js:741:39)
      at Object._executeMethod (node_modules/web3-eth-contract/src/index.js:766:54)
      at Context.<anonymous> (test/src/expectEvent.web3.test.js:373:11)
      at processImmediate (internal/timers.js:456:21)

  3) Contract: expectEvent (web3 contracts) 
       inTransaction
         with indexed event parameters
           "before each" hook for "accepts emitted events with correct indexed parameter and emitter object":
     Error: invalid number value (arg="indexedValue", coderType="uint256", value="2a")
      at Object.throwError (node_modules/web3-eth-abi/node_modules/ethers/utils/errors.js:68:17)
      at CoderNumber.encode (node_modules/web3-eth-abi/node_modules/ethers/utils/abi-coder.js:353:20)
      at /home/anon/tmp/openzeppelin-test-helpers/node_modules/web3-eth-abi/node_modules/ethers/utils/abi-coder.js:605:59
      at Array.forEach (<anonymous>)
      at pack (node_modules/web3-eth-abi/node_modules/ethers/utils/abi-coder.js:604:12)
      at CoderTuple.encode (node_modules/web3-eth-abi/node_modules/ethers/utils/abi-coder.js:764:16)
      at AbiCoder.encode (node_modules/web3-eth-abi/node_modules/ethers/utils/abi-coder.js:897:77)
      at ABICoder.encodeParameters (node_modules/web3-eth-abi/src/index.js:96:27)
      at /home/anon/tmp/openzeppelin-test-helpers/node_modules/web3-eth-contract/src/index.js:426:24
      at Array.map (<anonymous>)
      at Object._encodeMethodABI (node_modules/web3-eth-contract/src/index.js:425:12)
      at Object._processExecuteArguments (node_modules/web3-eth-contract/src/index.js:741:39)
      at Object._executeMethod (node_modules/web3-eth-contract/src/index.js:766:54)
      at Context.<anonymous> (test/src/expectEvent.web3.test.js:503:11)
      at processImmediate (internal/timers.js:456:21)

  4) Contract: expectEvent (web3 contracts) 
       inTransaction
         with conflicting indexed event parameters
           "before each" hook for "throws if the event from other contract is passed":
     Error: invalid number value (arg="indexedValue1", coderType="uint256", value="2a")
      at Object.throwError (node_modules/web3-eth-abi/node_modules/ethers/utils/errors.js:68:17)
      at CoderNumber.encode (node_modules/web3-eth-abi/node_modules/ethers/utils/abi-coder.js:353:20)
      at /home/anon/tmp/openzeppelin-test-helpers/node_modules/web3-eth-abi/node_modules/ethers/utils/abi-coder.js:605:59
      at Array.forEach (<anonymous>)
      at pack (node_modules/web3-eth-abi/node_modules/ethers/utils/abi-coder.js:604:12)
      at CoderTuple.encode (node_modules/web3-eth-abi/node_modules/ethers/utils/abi-coder.js:764:16)
      at AbiCoder.encode (node_modules/web3-eth-abi/node_modules/ethers/utils/abi-coder.js:897:77)
      at ABICoder.encodeParameters (node_modules/web3-eth-abi/src/index.js:96:27)
      at /home/anon/tmp/openzeppelin-test-helpers/node_modules/web3-eth-contract/src/index.js:426:24
      at Array.map (<anonymous>)
      at Object._encodeMethodABI (node_modules/web3-eth-contract/src/index.js:425:12)
      at Object._processExecuteArguments (node_modules/web3-eth-contract/src/index.js:741:39)
      at Object._executeMethod (node_modules/web3-eth-contract/src/index.js:766:54)
      at Context.<anonymous> (test/src/expectEvent.web3.test.js:551:11)
      at processImmediate (internal/timers.js:456:21)
```

[synthetix][2] fails with the following (also not sure if this is related to the RC):

**UPDATE** Testing are passing as of 10/30/2020

```javascript
2436 passing (21m)
  17 pending
  4 failing

  1) Contract: BinaryOptionMarketManager @gas-skip @ovm-skip
       when integrating with modern contracts
         Market tracking
           Adding, resolving, and expiring markets properly updates market lists:
     TypeError: Cannot assign to read only property '0' of object '[object Array]'
      at Array.sort (<anonymous>)
      at Context.<anonymous> (test/contracts/BinaryOptionMarketManager.js:1000:64)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  2) Contract: EtherCollateralsUSD
       when integrating with modern contracts
         when collateral is deposited
           should revert if the loan does not exist:
     AssertionError: expected 'value out-of-bounds (argument="loanID", value=-1, code=INVALID_ARGUMENT, version=abi/5.0.0-beta.153)' to include 'revert'
      at Object.assertRevert [as revert] (test/utils/index.js:477:11)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  3) Contract: EtherCollateralsUSD
       when integrating with modern contracts
         when collateral is withdrawn
           should revert if the loan does not exist:
     AssertionError: expected 'value out-of-bounds (argument="loanID", value=-1, code=INVALID_ARGUMENT, version=abi/5.0.0-beta.153)' to include 'revert'
      at Object.assertRevert [as revert] (test/utils/index.js:477:11)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  4) Contract: SystemSettings
       when integrating with modern contracts
         setTargetThreshold()
           reverts when owner set the Target threshold to negative:
     AssertionError: expected 'value out-of-bounds (argument="_percent", value=-1, code=INVALID_ARGUMENT, version=abi/5.0.0-beta.153)' to include 'revert'
      at Object.assertRevert [as revert] (test/utils/index.js:477:11)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by Spacesai1or** [comment]
~oz-test-helpers and synthetix tests seem to fail using version `1.3.0` as well~ Pass as of 10/30/2020

**Comment by GregTheGreek** [comment]
out-of-bounds doesn't look good is it related to #3744 or #3692 ?

**Comment by 0xferit** [comment]
Waiting so badly for this fix because of #3724

**Comment by GregTheGreek** [comment]
@ferittuncer It will be cut this week, we ran into some odd erros but believe they've all been addressed.

**Review by koraykoska — COMMENTED** [review]
Looks good to me. Let's include #3773 and merge this.

**Review by miranda76 — DISMISSED** [review]

**Comment by GregTheGreek** [comment]
I've retagged this and created the new release. waiting for the CI

**Comment by 0xferit** [comment]
image

**Comment by Spacesai1or** [comment]
`synthetix` tests are still passing, but `oz-test-helpers` are failing with (I don't think it's related to RC):

**UPDATE** `oz-test-helpers` passes using version [0.5.6](https://github.com/OpenZeppelin/openzeppelin-test-helpers/releases/tag/v0.5.6), but any later version fails with the folllowing error

```javascript
Error: Cannot find module 'web3-eth-contract'
Require stack:
- /home/anon/tmp/openzeppelin-test-helpers/node_modules/@openzeppelin/contract-loader/lib/index.js
- /home/anon/tmp/openzeppelin-test-helpers/test/src/expectEvent.web3.test.js
- /home/anon/tmp/openzeppelin-test-helpers/node_modules/mocha/lib/mocha.js
- /home/anon/tmp/openzeppelin-test-helpers/node_modules/mocha/index.js
- /home/anon/tmp/openzeppelin-test-helpers/node_modules/truffle/build/commands.bundled.js
- /home/anon/tmp/openzeppelin-test-helpers/node_modules/truffle/build/cli.bundled.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.resolve (internal/modules/cjs/helpers.js:83:19)
    at Web3Loader.get [as web3Contract] (/home/anon/tmp/openzeppelin-test-helpers/node_modules/@openzeppelin/contract-loader/src/index.ts:100:33)
    at Web3Loader.fromABI (/home/anon/tmp/openzeppelin-test-helpers/node_modules/@openzeppelin/contract-loader/src/index.ts:88:21)
    at Web3Loader.BaseLoader.fromArtifact (/home/anon/tmp/openzeppelin-test-helpers/node_modules/@openzeppelin/contract-loader/src/index.ts:78:17)
    at Object.<anonymous> (/home/anon/tmp/openzeppelin-test-helpers/test/src/expectEvent.web3.test.js:13:33)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at /home/anon/tmp/openzeppelin-test-helpers/node_modules/mocha/lib/mocha.js:390:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/anon/tmp/openzeppelin-test-helpers/node_modules/mocha/lib/mocha.js:387:14)
    at Mocha.run (/home/anon/tmp/openzeppelin-test-helpers/node_modules/mocha/lib/mocha.js:961:10)
    at /home/anon/tmp/openzeppelin-test-helpers/node_modules/truffle/build/webpack:/packages/core/lib/test.js:170:1
    at new Promise (<anonymous>)
    at Object.run (/home/anon/tmp/openzeppelin-test-helpers/node_modules/truffle/build/webpack:/packages/core/lib/test.js:169:1)
Truffle v5.1.46 (core: 5.1.46)
Node v12.16.2
```

**Review by Spacesai1or — DISMISSED** [review]

**Review by koraykoska — DISMISSED** [review]
Looks good to me. What about changing the names of the taken package names?

EDIT: Why is coveralls failing?

**Comment by GregTheGreek** [comment]
@koraykoska nooo idea. I'm looking into it, didn't fail on any other pr so im finding it very odd.

re package nams: I'm in a dispute with npm so will probably put this on ice until then..

**Review by frankiebee — DISMISSED** [review]
seems to have failed coveralls and dropped test coverage bellow %80
but this pr dosent look to have changed anything other then version so looks good 🤙

**Review by Spacesai1or — APPROVED** [review]

**Comment by Spacesai1or** [comment]
UPDATE 12/11/2020: Looks like adding a timeout of 20 seconds corrected this. Previously the test was using version `82.0` of Firefox and is now using the latest version, `83.0`. @cgewecke found that encrypt seems to take a while in the new version of Firefox

Failing test:

```bash
✗ encrypt then decrypt wallet
	Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

Passes locally though:

```bash
✓ encrypt then decrypt wallet

  window.Web3 is defined
    ✓ loads

Firefox 78.0 (Ubuntu 0.0.0): Executed 87 of 87 SUCCESS (17.739 secs / 15.406 secs)
TOTAL: 87 SUCCESS
```

**Review by frankiebee — DISMISSED** [review]
🎉

**Review by Spacesai1or — DISMISSED** [review]

**Review by Spacesai1or — APPROVED** [review]

**Pull request closed without merging**
