### PR TITLE
Check for duplicate queue entries in WebsocketProvider

### LINKED ISSUE #3568: eth.getBlock sometimes returns an array
#### Expected behavior
[web3.eth.getBlock](https://web3js.readthedocs.io/en/v1.2.8/web3-eth.html#getblock) "Returns a block matching the block number or block hash."

#### Actual behavior
In most cases, the expected behavior, but in some cases not.  When I call 
`web3.eth.getBlock(blockNumber, function(error, blockData) {`...
where blockNumber is a number (e.g. 2577), `blockData` typically contains an Object more or less as described in the documentation.   However, *sometimes*, I get back an ARRAY containing Objects, but where the "blockNumber" field does not match the requested block number.  These arrays range in length from 0 (empty), including 1, to 17 (probably higher, but this is what I've observed in limited testing).  

The object keys also look a little different, containing keys `address` (40-hex-digit string), `topics` (an array of a couple 64-hex-digit strings), `data` (320-hex-digit-string), `blockNumber` (hex string without leading zeros padding it to a specific length, notably different from `number` as specified in the Block object), `transactionHash` (64-hex-digit string), `transactionIndex` (usually '0x0'), `blockHash` (64-hex-digit string), `logIndex` (usually '0x0'), `removed` (usually false), `gasLimit` (undefined), `gasUsed` (undefined), `size` (undefined), `timestamp` (undefined), and `number` (undefined).   

There is no `nonce`, `hash`, `from`, `to`, `value`, `gas`, `gasPrice` or `input` fields as in a [Transaction object](https://web3js.readthedocs.io/en/v1.2.8/web3-eth.html#gettransaction).

My inspection of the object is within the callback, and the callback is defined in the call.  The call is the primary/only contents of a Promise constructor in a wrapper function, which is called several times in different asynchronous chains kicked off by arrival of an event in the block for which data (specifically, the timestamp) is being requested.  In repeated testing, I am getting the arrival of the exact same set of past events on the same contract on the same private chain running on Geth 1.9.1-stable.  In these tests, the set of blocks for which an array is returned instead of a Block object seems random, with the probability of an array being returned somewhere around 1.5%. 

#### Steps to reproduce the behavior
Unfortunately, I don't have reliable reproduction steps as the effect appears to be somewhat random.

#### Environment
npm 6.14.5, node v9.3.0, web3 1.2.7, Windows 10

### PR DESCRIPTION
**Pull request by wbt**
## Description
This is intended to address the issue found in #3568 by detecting the condition causing that issue, and emitting an error instead of sending data to incorrect formatters and callbacks.  This error will not be emitted in cases where intended operation can continue because only ids that have already been fully used and deleted from queues are being reused, as the existing behavior is not specifically problematic in that case, though this may lead some bugs to go undiscovered in light testing.  

I have marked this as a draft because in limited testing with the example code of #3573, this does not produce helpful output such as the text of the error message; execution just silently stops and it's not clear why.  If someone else can do more testing or edits to make that clearer, that would be helpful. 

A corresponding change in 2.x might be a good idea. 

Fixes #3568

## Type of change
I am not sure if this should be considered a bug fix or breaking change.  It would only break code in cases where the code is already broken but where an existing issue might not be evident, making the issue more evident.

## Checklist:
This is as complete as of initial PR submission as the original submitter will get it:
- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build-all` and tested the resulting files from `dist` folder in a browser.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.

### CODE REVIEW

**Comment by cgewecke** [comment]
@wbt 

Tangentially, had a thought that your use case might also be helped by using yarn's [selective version resolutions][1] feature. This lets you coerce all instances of a package in the dependency tree to a single version, flat-packed once at the outer level. We use it here in E2E testing with projects that consume Web3 via truffle-contract. 

You add the following key to your package.json and install with yarn:
```json
"resolutions": {
  "*/**/web3": "1.2.8",
  "*/**/web3-bzz": "1.2.8",
  "*/**/web3-core-helpers": "1.2.8",
  "*/**/web3-core-method": "1.2.8",
  "*/**/web3-core-promievent": "1.2.8",
  "*/**/web3-core-requestmanager": "1.2.8",
  "*/**/web3-core-subscriptions": "1.2.8",
  "*/**/web3-core": "1.2.8",
  "*/**/web3-eth-abi": "1.2.8",
  "*/**/web3-eth-accounts": "1.2.8",
  "*/**/web3-eth-contract": "1.2.8",
  "*/**/web3-eth-ens": "1.2.8",
  "*/**/web3-eth-iban": "1.2.8",
  "*/**/web3-eth-personal": "1.2.8",
  "*/**/web3-eth": "1.2.8",
  "*/**/web3-net": "1.2.8",
  "*/**/web3-providers-http": "1.2.8",
  "*/**/web3-providers-ipc": "1.2.8",
  "*/**/web3-providers-ws": "1.2.8",
  "*/**/web3-shh": "1.2.8",
  "*/**/web3-utils": "1.2.8"
},
```

Nested Web3 dependencies will be installed at 1.2.8. You can check this by running `yarn list web3` and verifying that only a single version is listed for your project.

Another detail is that @truffle/contract automatically attaches a confirmation handler to each request which fires 24X by default. Setting `web3.eth.transactionConfirmationBlocks` to a lower number should address this. 

Side-note: if you're interested in running the ganache tests locally you can with
```
npm run test:e2e:ganache
```

To run against geth w/ websocket tests included (takes ~3 min)
```
npm run test:e2e:geth:auto
```

[1]: https://classic.yarnpkg.com/en/docs/selective-version-resolutions/

**Comment by wbt** [comment]
@cgewecke Thanks for the pointers! 
I am not quite comfortable coercing truffle packages to use a version of web3 they aren't yet designed to work with, largely due to past experience about the interaction between those projects and due to having spent too many weeks in "dependency hell."

**Comment by cgewecke** [comment]
> largely due to past experience about the interaction between those projects and due to having spent too many weeks in "dependency hell."

Understandable, although the interaction bug you discovered here with multiple versions installed is pretty bad. 

FWIW we use resolutions in testing here to inject the latest state of the lib into another project and run their units tests with it. So there's at least some ongoing validation that Web3 works with @truffle/contract. Would not pretend it's exhaustive though.

**Comment by wbt** [comment]
>So there's at least some ongoing validation that Web3 works with @truffle/contract. Would not pretend it's exhaustive though.

That comes as a bit of a surprise, looking at the failure of [this PR](https://github.com/trufflesuite/truffle/pull/3078), where a using project breaks absent changes in the using project following an attempt to upgrade a patch-level web3 change.  (The interaction issues are not all old ones!)  However, it's nice to hear there's some attempts to continue compatibility checking.

**Comment by cgewecke** [comment]
@wbt 

That PR is not getting past a typescript compilation step on install. Think it's something that could be resolved if they reworked their TS a bit. 

We've continued to make sure the core logic doesn't break @truffle/contract since that module is widely used on it's own. We're also trying to make sure that Web3's types changes are non-breaking by testing the latest state against a production TS project (gnosis/dex-react) [here][2].

Lastly, there's a tracking issue at [truffle 2688][1] that documents the main things Truffle would need to address to upgrade Web3.  

[1]: https://github.com/trufflesuite/truffle/issues/2688 
[2]: https://github.com/ethereum/web3.js/pull/3562

**Comment by wbt** [comment]
I don't think this should be autoclosed; I think it could benefit from some collaborative effort to get it over the finish line.

**Comment by wbt** [comment]
I still don't think this should be marked as stale.

**Comment by wbt** [comment]
I still don't think this should be autoclosed; I think it could benefit from some collaborative effort to get it over the finish line.

**Comment by wbt** [comment]
I don't remember the CLA requirement being part of the deal when taking over from the Ethereum Foundation.

**Comment by GregTheGreek** [comment]
Please see #3846 . CLA is not required.

**Comment by jdevcs** [comment]
This PR is still WIP and there is no activity, so closing . @wbt feel free to reopen this when you have time for contributions. Thanks

**Pull request closed without merging**
