### PR TITLE
Fix: ensure using this.provider as the context `this`

### PR DESCRIPTION
**Pull request by chendatony31**
## Description

The bug is brought in this PR: https://github.com/ethereum/web3.js/pull/3649 

It may cause some problems when calling `provider.request`. As the context `this` maybe `window` sometimes, so we should make sure the context is the `provider`.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [x] I ran `npm run test:unit` with success.
- [x] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [x] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [x] I have tested my code on the live network.
- [x] I have checked the Deploy Preview and it looks correct.
- [x] I have updated the `CHANGELOG.md` file in the root folder.

### CODE REVIEW

**Comment by ryanio** [comment]
Is it really necessary for the context to be `provider`? It could be, but I don't think it should be relied on like that. Could you adjust your provider code to bind to the scope as explicitly needed?

**Comment by chendatony31** [comment]
> Is it really necessary for the context to be `provider`? It could be, but I don't think it should be relied on like that. Could you adjust your provider code to bind to the scope as explicitly needed?

Yeah, We've got a problem, and now I have to detect the context whether is the `window` or the `provider`. it may work, but not cool. 

More discussion may check here: https://github.com/ethereum/web3.js/pull/3649#issuecomment-696533463

**Review by sebsobseb — APPROVED** [review]

**Comment by GregTheGreek** [comment]
This makes sense but will need to test it out later today and probably add a testcase for this

**Comment by Velenir** [comment]
Here's a [codesandbox](https://codesandbox.io/s/wc-web3-callbackify-issue-1beb2?file=/src/App.js:661-805) with a reproduction of this issue with `@walletconnect/web3-provider`

**Review by frankiebee — APPROVED** [review]
this looks good to me, `bind`ing provider context is relatively harmless in this situation and good practice for this style code. it's a little strange though because callbackifiy should preserve the `this` but maybe due to the changes in the pr mentioned that has change.

**Review by vikmeup — CHANGES_REQUESTED** [review]
Did you consider to write a test to avoid such issues in the future?

**Comment by sebsobseb** [comment]
Any idea when this will get merged and released with tag 1.3.1 ?

**Review by GregTheGreek — APPROVED** [review]

**Pull request merged**
