### PR TITLE
[Types] Fix typo in BlockHeader type

### PR DESCRIPTION
**Pull request by marcelltoth**
## Description

There was a typo in the typings for `BlockHeader`. As documented [here](https://web3js.readthedocs.io/en/v1.2.11/web3-eth.html#id58) blocks have a `transactionsRoot` property, but the typings spelled it as `transactionRoot`. Of course that property does not exist and will result in `undefined` values when using.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have selected the correct base branch. - **I think**
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas. **N/A**
- [ ] I have made corresponding changes to the documentation. **N/A**
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules. 
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary. **N/A** 
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code. **N/A**
- [ ] I ran `npm run build` with success. **N/A** (Won't CI run these anyway though?)
- [ ] I have tested the built `dist/web3.min.js` in a browser. **N/A**
- [ ] I have tested my code on the live network. **N/A**
- [ ] I have checked the Deploy Preview and it looks correct. **What is this?**
- [ ] I have updated the `CHANGELOG.md` file in the root folder. **How do I do so exactly, without knowing the version number upfront?**

### CODE REVIEW

**Review by jdevcs — CHANGES_REQUESTED** [review]
@marcelltoth Thanks for this PR. changelog update is also required under 1.7.5

**Comment by jdevcs** [comment]
https://github.com/ethereum/execution-apis/blob/985c936c57b5c613d7fdea9a1343b799874b24c3/src/schemas/block.json#L2

**Comment by jdevcs** [comment]
Same changes PR as https://github.com/ChainSafe/web3.js/pull/5083/

**Comment by nazarhussain** [comment]
As the PR https://github.com/ChainSafe/web3.js/pull/5083 with same change was created earlier, so I am closing this one.

**Pull request closed without merging**
