### PR TITLE
Fix promise in `accounts.signTransaction()` throwing errors that cannot be caught

### PR DESCRIPTION
**Pull request by andreistefanwork**
## Description

Accounts.signTransaction() can generate a stray Promise under JS job queue, and there's no way for library users to catch any exceptions the stray promise throws, which can kill the entire Node.js process.

Fixes (#4724)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [x] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [x] I ran `npm run build` with success.
- [ ] I have tested the built `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [x] I have updated the `CHANGELOG.md` file in the root folder.

### CODE REVIEW

**Comment by kai-alpha** [comment]
Unfortunately I'm not skilled in JS (esp. in raw Promises) enough to review your PR, but it's great you could write a unit test covering this case.

**Comment by andreistefanwork** [comment]
Hi @jdevcs! Can you guys review the PR and let me know if everything is alright?

**Review by nazarhussain — APPROVED** [review]

**Review by avkos — APPROVED** [review]
Thanks for the fix. but need to check why tests fails

**Comment by andreistefanwork** [comment]
Hi @avkos! Looking at the failed test, the promise: https://github.com/ChainSafe/web3.js/blob/9d5ce480d8f127e6868605fe684f9707a765e72b/test/e2e.contract.deploy.js#L112-L114

takes more that 2 seconds to resolve during e2e testing with Firefox browser. However, the same test using Chrome browser passes...

Also, this other very similar promise:
https://github.com/ChainSafe/web3.js/blob/9d5ce480d8f127e6868605fe684f9707a765e72b/test/e2e.contract.deploy.js#L97-L99

resolves both on Chrome and on Firefox..

I'm wondering, if we restart the tests, will it pass the second time? I'm really struggling to find a connection between the changes on the PR and the test that fails, without success

**Comment by kai-alpha** [comment]
Maybe you can rebase onto the latest HEAD and force-push to rerun the tests?

**Comment by andreistefanwork** [comment]
Ok, so the second run was successful

**Review by nikoulai — APPROVED** [review]

**Review by jdevcs — COMMENTED** [review]
@andreistefanwork This branch has conflicts that must be resolved

**Comment by andreistefanwork** [comment]
@jdevcs yes, some `changelog.md` conflicts. Solved them

**Comment by andreistefanwork** [comment]
@jdevcs @nazarhussain Can this PR be merged & closed?

**Review by jdevcs — APPROVED** [review]

**Comment by jdevcs** [comment]
Merged via https://github.com/ChainSafe/web3.js/pull/5252

**Pull request merged**
