### PR TITLE
add util polyfill

### LINKED ISSUE #6146: 4.x remove polyfills
https://github.com/web3/web3.js/issues/5994#issuecomment-1570947666
removing polyfills will reduce build size and allow cra and angular build from esm/cjs files
#### Steps to reproduce the behavior

1. [First step]
2. [Second step]
3. [and so on...]

### PR DESCRIPTION
**Pull request by mpetrunic**
## Description

Please include a summary of the changes and be sure to follow our [Contribution Guidelines](../CONTRIBUTIONS.md).

Fixes #6146 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run lint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:coverage` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [ ] I have linked Issue(s) with this PR in "Linked Issues" menu.

### CODE REVIEW

**Review by jdevcs — APPROVED** [review]

**Comment by luu-alex** [comment]
Can you double check if this fixs the polyfill problem? I'm still getting the error building with angular.

Although seems like CRA builds work fine on 4.x main branch, not sure why.

**Comment by mpetrunic** [comment]
> Can you double check if this fixs the polyfill problem? I'm still getting the error building with angular.
> 
> Although seems like CRA builds work fine on 4.x main branch, not sure why.

I tried it with CRA and it worked. Could you paste angular error and link to repo with angular repo?

**Comment by luu-alex** [comment]
> 

https://github.com/luu-alex/angular-web3/tree/main
`yarn link add web3`
`ng serve`
```
Uncaught ReferenceError: process is not defined
    at 9300 (util.js:109:1)
    at __webpack_require__ (bootstrap:19:1)
    at 3653 (index.js:1:12)
    at __webpack_require__ (bootstrap:19:1)
    at 2242 (index.js:2:14)
    at __webpack_require__ (bootstrap:19:1)
    at 630 (topic.ts:43:8)
    at __webpack_require__ (bootstrap:19:1)
    at 5788 (validator.ts:26:23)
    at __webpack_require__ (bootstrap:19:1)
```

**Review by avkos — APPROVED** [review]

**Comment by jdevcs** [comment]
> > 
> 
> https://github.com/luu-alex/angular-web3/tree/main `yarn link add web3` `ng serve`
> 
> ```
> Uncaught ReferenceError: process is not defined
>     at 9300 (util.js:109:1)
>     at __webpack_require__ (bootstrap:19:1)
>     at 3653 (index.js:1:12)
>     at __webpack_require__ (bootstrap:19:1)
>     at 2242 (index.js:2:14)
>     at __webpack_require__ (bootstrap:19:1)
>     at 630 (topic.ts:43:8)
>     at __webpack_require__ (bootstrap:19:1)
>     at 5788 (validator.ts:26:23)
>     at __webpack_require__ (bootstrap:19:1)
> ```

 For end users few options are, users adding explicitly in `polyfills.ts` :
```
(window as any).process = {
  env: { DEBUG: undefined },
};
```
or 

yarn add process
and after that adding explicitly in `polyfills.ts` :
```
import * as process from 'process';
window['process'] = process;
```

**Comment by mpetrunic** [comment]
> yarn link add web3

There is no way around it except for #6156

**Pull request merged**
