### PR TITLE
Transaction.to can be null

### PR DESCRIPTION
**Pull request by alexkvak**
According to [docs](https://web3js.readthedocs.io/en/1.0/web3-eth.html#gettransaction)
`to` - `String`: Address of the receiver. `null` when its a contract creation transaction.

### CODE REVIEW

**Review by princesinha19 — COMMENTED** [review]
I think we shouldn't make it as optional. RPC returns null if it's a contract creation so, we shouldn't make it as an optional parameter. In all case `to` parameter will exist.

**Comment by alexkvak** [comment]
@princesinha19 agree, fixed

**Review by joshstevens19 — APPROVED** [review]
Thanks for the PR @alexkvak :+1: @nivida can you merge.

**Review by princesinha19 — APPROVED** [review]
Thanks for the PR @alexkvak.

**Review by nivida — APPROVED** [review]

**Pull request merged**
