### PR TITLE
Fix misleading web3-providers tsconfig paths (Issue/3336)

### LINKED ISSUE #3336: Analysis of the defined paths for the provided types
### Expected behavior 

The path defined for example in the ``tsconfig`` file of the ``web3-providers-http`` package is misleading and should get corrected if possible in a non-breaking manner.

#### Actual behavior

The defined path is ``web3-providers`` instead of ``web3-providers-http``.

#### Steps to reproduce the behavior

1. Open a ``tsconfig`` file from one of the provider packages and check the ``path`` property.

#### Steps for this issue

1. Check all ``path`` properties of all ``tsconfig`` files and write the misleading down here
2. Analyze the possibilities to correct those paths in a non-breaking manner
3. Propose a PR with your solution.

### PR DESCRIPTION
**Pull request by wirednkod**
## Description

Issue: The path defined for example in the tsconfig file of the web3-providers-http package is misleading and should get corrected if possible in a non-breaking manner.

Fixes #3336 

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.
- [x] I ran ```npm run dtslint``` with success and extended the tests and types if necessary.
- [x] I ran ```npm run test:unit``` with success.

### CODE REVIEW

**Review by ryanio — DISMISSED** [review]
Hey @wirednkod thanks for this PR! It LGTM.

Did you by any chance check if any other packages have misleading paths outside the providers packages?

In a future PR would also love your help adding the missing types to the packages you identified in https://github.com/ethereum/web3.js/issues/3336#issuecomment-594900716 `web3-core-requestmanager` and `web3-core-promievent`.

**Comment by wirednkod** [comment]
@ryanio I did - Issue appeared only in the providers package. I'll open new PR for adding the missing types to the packages you identified in [#3336 (comment)](https://github.com/ethereum/web3.js/issues/3336#issuecomment-594900716) web3-core-requestmanager and web3-core-promievent.

**Comment by ryanio** [comment]
Thanks, that would be awesome!

For this PR do you mind adding a small one line Changelog.md entry?

Thanks again.

**Comment by wirednkod** [comment]
Done that :)

**Comment by ryanio** [comment]
Thanks!

We are prepping the 1.2.7 `rc` release now so it looks like this PR may have to wait for 1.2.8, but we will be sure to get it in soon! Thanks again.

**Comment by nivida** [comment]
@ryanio This would probably break existing DApp's. I would test it with different module imports in TS and with different depending projects.

**Comment by GregTheGreek** [comment]
I think @nivida may be correct here. Ultimately we did just merge #3652 which will eventually solve this issue.

**Pull request closed without merging**
