### PR TITLE
Remote node provider edits

### PR DESCRIPTION
**Pull request by thesuperb1**
Edited the documentation to include how to use web3 with a remote node provider.

Please include a summary of the changes and be sure to follow our [Contribution Guidelines](../CONTRIBUTIONS.md).

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

### CODE REVIEW

**Review by Spacesai1or — APPROVED** [review]

**Review by Spacesai1or — CHANGES_REQUESTED** [review]
Can you update the `CHANGELOG.md`? Other than that, this should be good to go, thank you for opening the PR

**Comment by thesuperb1** [comment]
Just updated the changelog.md - please let me know if there are any issues! Thanks.
[https://my-email-signature.link/signature.gif?u=1100946&e=134171491&v=c1f68f389579debc3b7bb1a3c5b1f2de50574b2a32ca54571622388bcbaa7c0f]
________________________________

**Comment by Spacesai1or** [comment]
Thank you for the response, doesn't look like the CHANGELOG change made it to this PR, could you try pushing again?

**Review by koraykoska — DISMISSED** [review]
Should work like that. I'll wait for a second review.

**Comment by thesuperb1** [comment]
Hi there! Just wanted to follow up on the status of this :)

**Comment by Spacesai1or** [comment]
Sorry that this hung around for so long, can you solve the merge conflicts, then this can be merged
Thank you!

**Comment by thesuperb1** [comment]
Just solved, lmk if you have any questions!
[https://my-email-signature.link/signature.gif?u=1100946&e=140335693&v=fc9174b9170616d34aabd7c04989a926f6ba434b5f82d63e43a2774beb1bd760]
________________________________

**Review by Spacesai1or — DISMISSED** [review]
Just needs merge conflict to be solved

**Comment by Spacesai1or** [comment]
Closing in favor of #3960, there was an update to how Infura links are provided to tests (#3943) and it seems to be causing an issue here

**Pull request closed without merging**
