### PR TITLE
v1/chore(web3-eth-accounts): bump @ethereumjs/common and @ethereumjs/tx

### PR DESCRIPTION
**Pull request by legobeat**
## Description

The versions of `@ethereumjs/` dependencies were pinned in #5529.

This retains the pin (uncertain why it was first introduced) but bumps them to latest within semver-major.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran `npm run lint` with success and extended the tests and types if necessary.
  - _Note: I do get a bunch of lint errors but these are unrelated and present on the base branch._
- [x] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:coverage` and my test cases cover all the lines and branches of the added code.
  - _This script does not exist on the `1.x` branch._
- [x] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [x] I have updated the `CHANGELOG.md` file in the root folder.
- [ ] I have linked Issue(s) with this PR in "Linked Issues" menu.

### CODE REVIEW

**Comment by legobeat** [comment]
@spacesailor24

**Review by jdevcs — CHANGES_REQUESTED** [review]
We dnt merge external PRs with following changes:

- dist/ build output

- package-lock files, ( If changes in packagelock are necessary thn one of our team member will do these in another PR )

**Comment by Muhammad-Altabba** [comment]
Hi @legobeat 
Did you face an issue that needed to update dependencies, in order to be fixed?
Thanks,

**Comment by legobeat** [comment]
> Hi @legobeat Did you face an issue that needed to update dependencies, in order to be fixed? Thanks,

Yes: To get the updates done in the updates in `@etehreumjs/common`, for example https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fcommon%402.6.5. Is there any reason to keep them frozen at legacy version?

**Review by jdevcs — APPROVED** [review]

**Review by luu-alex — APPROVED** [review]

**Review by Muhammad-Altabba — APPROVED** [review]
Thanks @legobeat for your contribution,

**Pull request merged**
