### PR TITLE
gentlejack

### PR DESCRIPTION
**Pull request by gentlejack**
gentlejack-web3.js

### CODE REVIEW

**Comment by gentlejack** [comment]
From 17078c89a0fd9175be361dc806e1ae4eeb4378a4 Mon Sep 17 00:00:00 2001
From: gentlejack <gentle.jack35@outlook.com>
Date: Fri, 6 Jan 2017 20:50:25 -0800
Subject: [PATCH] gentlejack

gentlejack-web3.js
---
 .gitattributes | 17 +++++++++++++++++
 1 file changed, 17 insertions(+)
 create mode 100644 .gitattributes

diff --git a/.gitattributes b/.gitattributes
new file mode 100644
index 0000000..bdb0cab
--- /dev/null
+++ b/.gitattributes
@@ -0,0 +1,17 @@
+# Auto detect text files and perform LF normalization
+* text=auto
+
+# Custom for Visual Studio
+*.cs     diff=csharp
+
+# Standard to msysgit
+*.doc	 diff=astextplain
+*.DOC	 diff=astextplain
+*.docx diff=astextplain
+*.DOCX diff=astextplain
+*.dot  diff=astextplain
+*.DOT  diff=astextplain
+*.pdf  diff=astextplain
+*.PDF	 diff=astextplain
+*.rtf	 diff=astextplain
+*.RTF	 diff=astextplain

**Comment by gentlejack** [comment]
Mergeable!!!

**Comment by gentlejack** [comment]
[clabot:check].

**Comment by frozeman** [comment]
Hey @gentlejack what exactly is this PR about?
you just add a random file, put out a random command and ask for merge..

Please explain in detail what you change is about and why it should be in web3.js

**Pull request closed without merging**
