### PR TITLE
Update helpers.js

### PR DESCRIPTION
**Pull request by Jack-Works**
## Description

Please include a summary of the changes and be sure to follow our [Contribution Guidelines](../CONTRIBUTIONS.md).

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

### CODE REVIEW

**Review by fallingicarus — APPROVED** [review]

**Review by fallingicarus — APPROVED** [review]
Code

**Comment by nazarhussain** [comment]
@Jack-Works Thanks for the contribution. I would suggest to create an issue on the repo mentioning what was the issue intended to fix and then link it to this PR. Also add entry to `CHANGELOG.md` file for your PR. 

Assigning some reviewers to get approvals, as soon you make above changes and PR looks good will be able to include in upcoming release.

**Review by nazarhussain — APPROVED** [review]
For reference for others attaching some docs describing historical changes which brought `globalThis`  

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis#description

**Comment by Jack-Works** [comment]
👀 Maybe don't merge yet. I want to review the whole repo to search for all window usages. FIY I'm trying to running web3.js in Web Workers

**Comment by Jack-Works** [comment]
Hi! I have searched in the repo and removed all usage to `window`. I use `globalThis`(modern JS) and `self` (available in both normal webpage and web worker) as fallback.

**Comment by luu-alex** [comment]
thank you for opening this PR, if possible can you update the `CHANGELOG.MD` https://github.com/ChainSafe/web3.js/blob/1.x/CHANGELOG.md detailing the changes you made?

**Comment by Jack-Works** [comment]
> thank you for opening this PR, if possible can you update the `CHANGELOG.MD` https://github.com/ChainSafe/web3.js/blob/1.x/CHANGELOG.md detailing the changes you made?

Done!

**Review by luu-alex — APPROVED** [review]

**Review by nazarhussain — CHANGES_REQUESTED** [review]
@Jack-Works The integration tests on windows are failing for your PR. Can you please debug those further.

**Comment by Jack-Works** [comment]
> @Jack-Works The integration tests on windows are failing for your PR. Can you please debug those further.

```
>>>>>>
HTTP:MAINNET getBlock
>>>>>>
Error: Failed to connect to Infura over websockets after 10 tries
    at getBlockWithRetry (D:\a\web3.js\web3.js\windows_test\basic_usage.js:31:15)
```

Hmm sorry, but I didn't change any platform-aware code. I have no idea why it is happening. It looks like a network problem on the CI machine, so I guess re-run the test might resolve the problem?

**Review by Spacesai1or — APPROVED** [review]

**Comment by Spacesai1or** [comment]
@Jack-Works The failing tests don't seem to be related to changes. The failing `Build / e2e_windows (pull_request)` is a recurring issue that we haven't found the cause for. In the past, waiting a bit and rerunning the tests seem to have resolved the issue, but we might need to rotate the Infura key

**Comment by Spacesai1or** [comment]
Okay so FYI for everyone, I merged this PR into a branch I just created and opened PR #4671, and the Windows test is no longer failing. I don't have an answer as to why this works, but we used this to solve the same issue previously

**Comment by Jack-Works** [comment]
> Okay so FYI for everyone, I merged this PR into a branch I just created and opened PR #4671, and the Windows test is no longer failing. I don't have an answer as to why this works, but we used this to solve the same issue previously

Oh, I know why. 

The Infura key is not accessible when the PR is triggered by a non-contributor (me). Because leaking a secret environment variable is a security violation.

**Pull request merged**
