### PR TITLE
fix(allevents): update decode logic to handle no topics

### PR DESCRIPTION
**Pull request by marcusmolchany**
the default for `data.topics` on line 53 was causing an exception on line 55:
```
TypeError: Cannot read property 'slice' of undefined
```

### CODE REVIEW

**Comment by marcusmolchany** [comment]
not sure the best way to add tests for this one

**Comment by frozeman** [comment]
A test case would be great. There should be some decoder tests, just add one with empty data, or create a new unit test for that. Thanks for the find though!

**Comment by frozeman** [comment]
Thanks for the fix, i'll fix the other one myself.

**Comment by frozeman** [comment]
The `this._json` is the jsonInterface of the contract which will fire this event. its needed to decode the event.

**Comment by marcusmolchany** [comment]
thanks!

**Pull request merged**
