### PR TITLE
Release 1.7.5

### PR DESCRIPTION
**Pull request by jdevcs**
### Changed
-  Replace xhr2-cookies deps to cross-fetch for web3-providers-http (#5085)

### Added
-  Documentation details about `maxFeePerGas` and `maxPriorityFeePerGas` (#5121)
-  Added `createAccessList` types in web3.eth (#5146)

### Fixed
-  Improving `AbstractProvider` interface (#5150)
-  Fix typos in web3-eth-accounts.rst & TESTING.md (#5047)
-  Fix remove wallet using an index when an account address and address lowercase are equal (#5049)
-  Improve README.md & Fix typos (#4848)
-  Add optional hex formatting parameter for getTransactionrReceipt (#5153)
-  Fix transactionRoot -> transactionsRoot in BlockHeader (#5083)
-  Fix Promise in Accounts.signTransaction() throwing errors that cannot be caught (#4724)
-  Fixed unit tests & removed dead code for web3-providers-http (#5228)

### Security
-  Updated `got` lib version and fixed other libs using npm audit fix (#5178) (#5254)

### CODE REVIEW

**Comment by jdevcs** [comment]
As part of the RC process, following test installations are performed in other projects and running their tests to see if everything.  
+ installs properly
+ builds
+ tests pass

(This list will be actively edited) 

| Project | Desc | Status | 
| ------ | ----- | ----- |
| [oz-test-helpers][1] | Test utils. Subset of their suite is web3 contracts |  |
| [synthetix][2] | ~1000 units |   |


[1]: https://github.com/OpenZeppelin/openzeppelin-test-helpers
[2]: https://github.com/Synthetixio/synthetix

**Comment by ghost** [comment]
@jdevcs Could you merge this PR #5228 prior to merging this PR? Since it fixes some bugs introduced by #5085, I think it is necessary.

**Comment by jdevcs** [comment]
> @jdevcs Could you merge this PR #5228 prior to merging this PR? Since it fixes some bugs introduced by #5085, I think it is necessary.

Thanks , we discussed in team and its imp to include PR #5228 in 1.7.5 due to following fix:
 (#5235)

**Comment by jdevcs** [comment]
**For RC 1.7.5-rc.1:**
As part of the RC process, following test installations are performed in other projects and running their tests to see if everything.  
+ installs properly
+ builds
+ tests pass

(This list will be actively edited) 

| Project | Desc | Status | 
| ------ | ----- | ----- |
| [oz-test-helpers][1] | Test utils. Subset of their suite is web3 contracts | x |
| [synthetix][2] | ~1000 units |  ✅   |


[1]: https://github.com/OpenZeppelin/openzeppelin-test-helpers
[2]: https://github.com/Synthetixio/synthetix

**Comment by luu-alex** [comment]
Synthetix tests and oz tests passed ✅  for 1.7.5-rc.1

**Review by luu-alex — APPROVED** [review]

**Review by avkos — APPROVED** [review]

**Review by nikoulai — APPROVED** [review]

**Comment by jdevcs** [comment]
oz two tests are failing:
```
1) expectRevert
       assertion
         rejects an outOfGas:
     AssertionError: expect.fail()
      at assertFailure (test/helpers/assertFailure.js:9:10)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Context.<anonymous> (test/src/expectRevert.test.js:123:7)

  2) expectRevert
       outOfGas
         accepts an outOfGas:

      Wrong kind of exception received
      + expected - actual

      -Transaction: 0x4e501c63fc4b9d533635216abf480158732cd842f20efd89335781fd1d0868e2 exited with an error (status 0) after consuming all gas.
      -     Please check that the transaction:
      -     - satisfies all conditions set by Solidity `assert` statements.
      -     - has enough gas to execute the full transaction.
      -     - does not trigger an invalid opcode by other means (ex: accessing an array out of bounds).
      +out of gas
      
      at expectException (src/expectRevert.js:20:30)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Context.<anonymous> (test/src/expectRevert.test.js:153:7)
```

discussed in team: oz two tests not passing ( for current RC also for couple of past releases ), we can ignore this test.

**Pull request merged**
