### PR TITLE
feat: Ask Cookbook integration (Docs)

### PR DESCRIPTION
**Pull request by ClockRide**
## Description

Re: Conversation with @SantiagoDevRel

The AI assistant and co-pilot is trained on all existing web3.js resources (source code, docs website, etc) and is available as a standalone modal, embeddable as a button on any page (recommended for technical docs). It answers developer questions about building projects using web3.js, acting as an enhanced and streamlined technical documentation search tool as well as a Solidity/JS coding co-pilot.

Ask Cookbook AI could also access context from thousands of data sources indexed by Cookbook.dev in addition to web3.js-specific data sources, providing the best blockchain developer-focused answers of any chatbot on the market. Cookbook will assist in the tuning and calibration of the AI assistant to ensure the highest answer quality. 

## Preview
https://docsbot-demo-git-web3js-cookbookdev.vercel.app/

image

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran `npm run lint` with success and extended the tests and types if necessary.
- [x] I ran `npm run test:unit` with success.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

### CODE REVIEW

**Comment by ClockRide** [comment]
I'm not sure if the last two checkpoints (`I have checked the Deploy Preview and it looks correct.` and `I have updated the CHANGELOG.md file in the root folder.`) are applicable here, so I ignored them for now. If they are, please let me know, and I'll be happy to make the necessary changes :)

**Comment by SantiagoDevRel** [comment]
Hi @ClockRide thanks for making this PR!
I just have a couple of things that I was talking with Tyler/Michael previously:

1. Scope the knowledge/answers of the bot only to web3.js questions related - since we don't want people asking about memes, rockets, investing, meme coins, or any other unrelated topics.
2. Train the bot only with [web3.js v4](https://docs.web3js.org/) docs, and not with [web3.js v1](https://web3js.readthedocs.io/en/v1.10.0/) - I asked a few questions and it responded with v4, but just double checking!

Let me know if there is something that can be done for #1, thank you so much!💪

**Review by jdevcs — APPROVED** [review]

**Review by jdevcs — COMMENTED** [review]
@SantiagoDevRel merge this PR into your own branch and update yarn.lock there before merging into 4.x

**Comment by ClockRide** [comment]
Superseded by #7178

**Pull request closed without merging**
