### PR TITLE
Proposal for rearranging docs

### PR DESCRIPTION
**Pull request by mpetrunic**
## Description

Docs seemed like a bit over the place with Guide/Tutorials. This PR tries to organize docs into a single page where previous "tutorials" are added as "Example" subpage in guides. 
A landing page is removed and users are welcomed in the getting started section of the docs.
Removed "Raw Transaction" section as it was just a c/p from local wallet section.

Obviously a lot of content regarding smart contract and transaction is still missing^^

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run lint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:coverage` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [ ] I have linked Issue(s) with this PR in "Linked Issues" menu.

### CODE REVIEW

**Review by jdevcs — COMMENTED** [review]
doc is not building (seems due to broken links) , it needs a fix . Thanks @mpetrunic

**Comment by mpetrunic** [comment]
@jdevcs working on it, didnt show during yarn start 😓

**Comment by mpetrunic** [comment]
> doc is not building (seems due to broken links) , it needs a fix . Thanks @mpetrunic

We need to use my fork until https://github.com/milesj/docusaurus-plugin-typedoc-api/pull/99 gets merged as current version has docs base path hardcoded 🤦🏻‍♂️

**Review by jdevcs — APPROVED** [review]
There are some merge conflicts.

**Review by avkos — APPROVED** [review]

**Pull request merged**
