### PR TITLE
Remove any-promise dependency

### LINKED ISSUE #3377: web3 -- Web Worker environment still is not supported in 1.2.4
Hi all,

`1.2.4` (and/or its dependencies, e.g. any-promise) seems to have dependencies on "window" instead of "self" which prevents it working in a Web Worker context.

When I've tried `importScripts` in a Web Worker using `web3.js` instead of `web3.min.js` from the node module i can see the `window is not defined` error being thrown when `register-shim` is being loaded; this is a file inside `any-promise`, and the `any-promise` library is used by `web3-core-promievent` in the current version.

The `loadImplementation()` inside `register-shim.js` is attempting to grab `window.Promise` when there is no `window`:
```
/**
 * Browser specific loadImplementation.  Always uses `window.Promise`
 *
 * To register a custom implementation, must register with `Promise` option.
 */
function loadImplementation(){
  if(typeof window.Promise === 'undefined'){
    throw new Error("any-promise browser requires a polyfill or explicit registration"+
      " e.g: require('any-promise/register/bluebird')")
  }
  return {
    Promise: window.Promise,
    implementation: 'window.Promise'
  }
}
```

It is possible to work around this by setting `window` as `self` first before the `importScripts` statements so that it has the correct environment (effectively tricking `any-promise` under the hood while loading to treat the worker as `window`:

```
var window = self;
importScripts(/*path to web 3 goes here*/);
```

however, there is still an issue of passing/accessing the current provider details to the web worker environment, as there's no way to access this information from the browser instance of web3. It is also not ideal having to create an entirely new instance of web3 inside the web worker instead of using an existing one.

Related: #2211 #1774
Related: https://ethereum.stackexchange.com/questions/56405/integrating-web3-from-metamask-in-react

### PR DESCRIPTION
**Pull request by cgewecke**
## Description

The [any-promise][5] package has an [unsafe dereferencing][1] of the `window` object in its code that throws in the Web Worker environment. This PR removes it and falls back on native promises.

**What does any-promise do?** (from their README)
> NOTE: You probably want native promises now

> Let your library support any ES 2015 (ES6) compatible Promise and leave the choice to application authors. The application can optionally register its preferred Promise implementation and it will be exported when requiring any-promise from library code.

> If no preference is registered, defaults to the global Promise for newer Node.js versions. The browser version defaults to the window Promise, so polyfill or register as necessary.

Essentially, consumers of Web3 can decide which promise to use and Web3 will respect that, since it (usually) requires Promise from `any-promise`.

Hard to know if anyone is relying on this...

**Resources**
+ [Most browsers support native Promises][2] - exceptions are IE11 and Opera mini. 
+ IE 11 [lifecycle FAQ][3] advises users to switch to IE Edge
+ PR #1415 (March 2018) standardized use of `any-promise` at Web3
 
[1]: https://github.com/harttle/liquidjs/issues/73
[2]: https://caniuse.com/#feat=promises
[3]: https://support.microsoft.com/en-us/help/17454/lifecycle-faq-internet-explorer
[5]: https://github.com/kevinbeaty/any-promise

Fixes #3377 #2211 #1774

## Type of change

- [x] Bug fix (probably non-breaking?)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran ```npm run dtslint``` with success and extended the tests and types if necessary.
- [x] I ran ```npm run test:unit``` with success.
- [x] I have executed ``npm run test:cov`` and my test cases do cover all lines and branches of the added code.
- [ ] I ran ```npm run build-all``` and tested the resulting file/'s from  ```dist``` folder in a browser.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [ ] I have tested my code on the live network.

### CODE REVIEW

**Comment by nivida** [comment]
> [EDIT - this coverage drop is due to web3-eth-accounts/src/index.js getting smaller after removing a require statement, increasing the proportion of uncovered lines]

Verified ✅

**Review by nivida — APPROVED** [review]

**Comment by nivida** [comment]
@cgewecke Oh! Have you done some further tests with the ``PromiEvent`` object? It would probably be the perfect moment to add some additional test cases for it :) 

... and did you also thought about to fix this upstream instead of removing it? (I think the possibility is here that some depending projects do want to support IE11)

Edit:
> add some additional test cases for it

"add some explicit test cases for it" this is probably the better wording.

**Review by holgerd77 — APPROVED** [review]
Would also agree that keeping this dependency causes more problems than helping to address. Also adding a [Can-I-use-Web-Workers](https://caniuse.com/#feat=webworkers) table here for reference. Generally have to say that I have not very much of a picture of how widely web workers are used atm.

**Comment by cgewecke** [comment]
@nivida 

> did you also thought about to fix this upstream instead of removing it?

Yes. There have been no changes to any-promise for ~4 years. The problem with the `window` object has been raised there before in [any-promise 29][1].

On the surface, the lib seems abandoned / a historical artifact but according to npm it continues see significant increases in usage. Its weekly downloads have almost doubled in the last year (base = 1.5 mil)

Screen Shot 2020-02-24 at 8 59 37 AM

RE: testing. I don't know what test to add here. If you can think of one, will happily add.  
 

[1]: https://github.com/kevinbeaty/any-promise/issues/29

**Pull request merged**
