### PR TITLE
Add personal.signTypedData

### PR DESCRIPTION
**Pull request by ukstv**
The method signs the data along with the schema, so that a user is well informed on what she signs.
As proposed in https://github.com/ethereum/EIPs/pull/712

### CODE REVIEW

**Comment by frozeman** [comment]
As this is not accepted standard yet, and not in geth or parity i can't merge that, also it should be on the `eth_` namespace, as it doesn't receive a password as last argument.

**Comment by frozeman** [comment]
Im happy adding that, if there is a broad consensus.

**Comment by elenadimitrova** [comment]
Isn't there also a requirement for `eth_signTypedData` in addition to `personal_signTypedData` according to https://github.com/ethereum/EIPs/pull/712

**Comment by ukstv** [comment]
@elenadimitrova It is indeed. It doesn’t matter though as eip712 is not widely accepted. Neither geth nor parity support it.

**Comment by Amxx** [comment]
+1

**Comment by nivida** [comment]
Closed because the latest maintenance release was 0.20.7.

**Pull request closed without merging**
