### PR TITLE
web3-eth-contract validation test fail

### PR DESCRIPTION
**Pull request by luu-alex**
## Description
investigated #6461 
```
const logs = await contractDeployed.getPastEvents('Transfer');
			const tokenId = (logs[0] as EventLog)?.returnValues?.tokenId as string;
```
in this line, logs can sometimes be undefined, creating this error.

Fix is to just use receipt and instead of `getPastEvents` 
Please include a summary of the changes and be sure to follow our [Contribution Guidelines](../CONTRIBUTIONS.md).

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run lint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:coverage` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [ ] I have linked Issue(s) with this PR in "Linked Issues" menu.

### CODE REVIEW

**Review by jdevcs — APPROVED** [review]
> investigated https://github.com/web3/web3.js/issues/6461
> 
> const logs = await contractDeployed.getPastEvents('Transfer');
> 			const tokenId = (logs[0] as EventLog)?.returnValues?.tokenId as string;
> in this line, logs can sometimes be undefined, creating this error.
> 
> Fix is to just use receipt and instead of getPastEvents

Why logs were undefined? if tx is mined there should be logs available via getPastEvents, was there issue in tx waiting long in tests and not mined?

**Comment by Muhammad-Altabba** [comment]
> > investigated #6461
> > const logs = await contractDeployed.getPastEvents('Transfer');
> > const tokenId = (logs[0] as EventLog)?.returnValues?.tokenId as string;
> > in this line, logs can sometimes be undefined, creating this error.
> > Fix is to just use receipt and instead of getPastEvents
> 
> Why logs were undefined? if tx is mined there should be logs available via getPastEvents, was there issue in tx waiting long in tests and not mined?

I also think that we need to know why the logs were undefined sometime. 

And I think either the proposed code will still fail in the same occasions where the old code fails. Or, if this would not be the case, then there is another issue that the users will face when using `const logs = await contractDeployed.getPastEvents('Transfer');` outside the erc721 context.

Could you please @luu-alex investigate more on why and when the `await contractDeployed.getPastEvents('Transfer')` is returning `undefined`. And if you like, it could be helpful also to investigate this case with a code not related to erc721. Because, this is a generic functionality that could be used anywhere.

Many thanks,

**Comment by luu-alex** [comment]
sounds good @Muhammad-Altabba , this PR and i think this [one as well](https://github.com/web3/web3.js/pull/6434) was holding up release. I created an [issue](https://github.com/web3/web3.js/issues/6475) and will begin investigating. Thanks for the feedback

**Comment by luu-alex** [comment]
@jdevcs im not too sure, i will need to [investigate](https://github.com/web3/web3.js/issues/6475) getPastEvents next

**Review by avkos — APPROVED** [review]

**Review by Muhammad-Altabba — APPROVED** [review]

**Comment by luu-alex** [comment]
Needs more investigation, it seems to be an issue with getpastevents returning undefined due to a change from validation

**Pull request merged**
