### PR TITLE
Use eslint as linting tool.

### PR DESCRIPTION
**Pull request by levino**
eslint throws 7501 errors with a basic configuration. Most of them are low hanging fruits like unused variables and stuff. The code quality is disturbingly bad!

Obviously this PR cannot be merged before all errors are fixed or the severity for these error types is turned to warning. I would immediatly start fixing these errors before doing anything else @nivida

### CODE REVIEW

**Comment by frozeman** [comment]
Many of these "errors" are a question of taste. What is wrong with `jshint`, which we use?

**Comment by levino** [comment]
https://www.sitepoint.com/comparison-javascript-linting-tools/

For example "unused variables" are a big problem for the code quality. As JSHint happily ignores these things I would prefer a stricter linter. As I was saying this originates from my observation that the `package.json` files are not correctly formatted. See #1863 I think adding eslint does not immediatly fix that issue but it should be possible to use it to lint the `package.json` files.

**Comment by leonprou** [comment]
I would suggest to use [standartjs](https://standardjs.com/) - npm, github and bitcoinjs are using this coding style.

**Comment by levino** [comment]
Also okay with me.

**Comment by levino** [comment]
BTW: standardjs is basically a specific eslint config, right? The thing with standardjs and `web3` is that `web3` so far uses semicolons at the end of lines. This is why I think the change is a rather hard one. I would vote to act more lightweight and just apply eslint with the same rules as before and fix obvious errors like unused variables.

**Review by decanus — APPROVED** [review]

**Comment by nivida** [comment]
@Levino Hay I've added eslint in the ethereumProvider branch and because of this I will close it but thanks for submitting this PR!

**Pull request closed without merging**
