### PR TITLE
Add debug_accountRangeAt/debug_storageRangeAt methods

### PR DESCRIPTION
**Pull request by axic**
These are needed for the ewasm testnet blockexplorer.

cc @cdetrio

### CODE REVIEW

**Comment by frozeman** [comment]
I dont think they should be part of the main web3.js lib, as they are node specific, but you can simply attach them later by using the extend function in your code: https://web3js.readthedocs.io/en/1.0/web3.html#extend

We can have a chat about that in skype if you like.

**Comment by axic** [comment]
Actually I don't think these are designed to be client specific (I agree the parity ones are).

These supposed to be standard tracing methods, used by Remix and all the frameworks for debugging.

Btw, can you quickly explain the rules of inclusion? Would it be possible to have these here as a separate module (optionally loaded)? Or what is the best way to supply a distribution of these?

**Comment by frozeman** [comment]
If they are supported in all/most nodes we can surely include them. 
You could always make a separate package that runs `web3.extend()..` before and adds it to the running web3.js. Ill merge this if its widely used. We should discuss adding this to 1.0 as well.

**Comment by axic** [comment]
Does `extend` only works on the instance and not on the package?

**Comment by axic** [comment]
@frozeman can you have a look at https://github.com/axic/web3-extended.js if this is the way you've suggested?

**Pull request merged**
