### PR TITLE
Use v1.1.1 coverallsapp/github-action

### PR DESCRIPTION
**Pull request by cgewecke**
## Description

Debugging the coveralls hook hang...

### CODE REVIEW

**Comment by ryanio** [comment]
Thanks for looking into this, yeah I’m not sure what’s going on.

It does seem like Coveralls is getting the data because the website contains each PR builds’ coverage. Maybe I can try reconnecting the GitHub app.

**Comment by cgewecke** [comment]
@ryanio Yes, I don't see any issues at the coverallsapp/github-actions repo about this. 

They did [make some changes ~6 days ago][1] and feel like that coincides with the hang here. If turning the app on/off doesn't work, maybe we can try using `1.1.0` instead.

[1]: https://github.com/coverallsapp/github-action/commits/master

**Comment by ryanio** [comment]
I tried to re-install the coveralls app, we can see if it fixes the check reporting.

**Comment by cgewecke** [comment]
Closing looks like this is a Github App settings problem...

**Pull request closed without merging**
