### PR TITLE
Simplify ENS E2E test 

### PR DESCRIPTION
**Pull request by cgewecke**
## Description

#3301 added E2E tests that deploy ENS by installing a Truffle project and some dependencies in the repository when the test is run. 

This works in CI but is less well suited to local development because it modifies the npm packages and leaves file debris in the repo whenever it's run. 

PR 
 + translates Truffle deployment script into a pure web3.js script
 + integrates ENS E2E into the rest of the E2E tests so it runs against all available clients

PR is  a preparatory step for PR #3428

## Type of change

- [x] Test refactor

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran ```npm run dtslint``` with success and extended the tests and types if necessary.
- [x] I ran ```npm run test:unit``` with success.
- [ ] I have executed ``npm run test:cov`` and my test cases do cover all lines and branches of the added code.
- [ ] I ran ```npm run build-all``` and tested the resulting file/'s from  ```dist``` folder in a browser.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [ ] I have tested my code on the live network.

### CODE REVIEW

**Comment by ryanio** [comment]
Hey @cgewecke, code is looking good.

I added a commit to update the script `test:e2e:ens` to `mocha test/e2e.ens.js` if that's helpful.

It's not clear to me where or how `test/e2e.ens.js` is being run, is it with `mocha` running `test/*.js`?

**Comment by cgewecke** [comment]
> It's not clear to me where or how test/e2e.ens.js is being run, is it with mocha running test/*.js?

Yes, it's a little confusing.. this PR makes ENS like the other tests whose mocha descriptions include an `[ E2E ]` tag. These are mocha grepped in the scripts that run individual clients, ex:

https://github.com/ethereum/web3.js/blob/dee72e00883c5a23a47b6d3c1d27304ab1d4922e/scripts/e2e.ganache.sh#L31-L35

To run the ENS tests by themselves, you can`.only` the `describe` and execute 
```
npm run test:e2e:ganache # or another client
```

ENS was anomalous...I think that package.json command could just be deleted - forgot that was there.

**Comment by ryanio** [comment]
Gotcha, thanks for explaining. Makes sense. Zapped it.

**Comment by cgewecke** [comment]
@ryanio Thanks for those changes! Great.

**Review by ryanio — APPROVED** [review]

**Comment by holgerd77** [comment]
`e2e_windows` tests are not passing.

**Comment by cgewecke** [comment]
@holgerd77 The windows tests timing out are fixed in #3421 but that's not merged yet....

Windows job was exiting 0 [here][1] yesterday.

[1]: https://travis-ci.org/github/ethereum/web3.js/jobs/666560274#L1232

**Pull request merged**
