### PR TITLE
Add eth.getChainId method to 1.x

### PR DESCRIPTION
**Pull request by gabmontes**
This method was added to the branch 2.x in d98cef20. This change is to support the method in the 1.x line.

Worth considering this PR in the discussion at #3070 .

### CODE REVIEW

**Review by nivida — APPROVED** [review]
Looks good to me. Thanks! :)

**Review by cgewecke — APPROVED** [review]
LGTM as well. 

NB: `eth.getChainId` needs to be added to the documentation at some point.

**Comment by nivida** [comment]
@cgewecke true that. It can be copied from the 2.x branch. 

@gabmontes Do you have the time to do this for us?

**Comment by gabmontes** [comment]
@nivida added docs and rebased to get rid of the merge conflict.

**Pull request merged**
