### PR TITLE
Removing deprecation notice for HttpProvider

### PR DESCRIPTION
**Pull request by evertonfraga**
From my view, it is just a provider with less capabilities than websockets, but still widely useful — and widely used as well.

@frozeman @nivida @GregTheGreek any thoughts?

## Description

Please include a summary of the changes and be sure to follow our [Contribution Guidelines](../CONTRIBUTIONS.md).

## Type of change

- [x] Documentation

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

### CODE REVIEW

**Review by GregTheGreek — DISMISSED** [review]
This makes sense

**Comment by evertonfraga** [comment]
Thank you @GregTheGreek!

**Review by Spacesai1or — CHANGES_REQUESTED** [review]
If you could just update the `CHANGELOG.md` with something along the lines of:

`Remove deprecation notice for HttpProvider (#4008)`

**Comment by evertonfraga** [comment]
Thanks @spacesailor24 and @GregTheGreek.

I have added the changelog entry and updated from the base branch.

**Review by GregTheGreek — APPROVED** [review]

**Comment by GregTheGreek** [comment]
@spacesailor24 Looks like #4077 may have an implication we didn't think of. Github settings require certain checks to pass, but they're skipped according ot #4077

**Comment by evertonfraga** [comment]
@GregTheGreek no worries, I can squash those two commits and force-push. That should do it.

**Pull request merged**
