### PR TITLE
Update packages/web3-providers-http/src/index.js to use Node.js URL to parse protocol 

### LINKED ISSUE #4954: Improve how web3-providers-http checks protocol
I came across an issue on a local project which I believe stems from how `web3-providers-http` parses the protocol with a simple `substring`. The bug was on my side - I had a space at the beginning of the url so an https string was being detected as http. However, the underlying package could be improved a little by using https://nodejs.org/api/url.html#urlprotocol to get the protocol instead. 

https://github.com/ChainSafe/web3.js/blob/f2036c0100fb7e74208e9d69914a84eed2cb72b5/packages/web3-providers-http/src/index.js#L47

### PR DESCRIPTION
**Pull request by eddybuilds**
## Description

A small simple fix to use `url`, the inbuilt nodejs library, to parse the protocol with `web3-providers-http/src/index.js` rather than checking a substring. 

Fixes [#(4954)](https://github.com/ChainSafe/web3.js/issues/4954)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [x] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

### CODE REVIEW

**Comment by eddybuilds** [comment]
@jdevcs - @'ing you because you 👍'd my issue (https://github.com/ChainSafe/web3.js/issues/4954)

I made the minor change to use `url.protocol` instead of a `substring` when parsing the host in `web3-providers-http/src/index.js` so it'll now correctly detect `"  https"` as `"https"` rather than `"http"`, manually checked the code change locally, and ran `npm run dtslint` which passed. However the other `npm` commands fail because of missing or conflicting ganache settings etc, and I'm currently working on my own contracts so don't want to start changing my local dev environment to further check this change. Any chance of running these in CI to check they work okay? Is it safe to just submit a PR with the changes and checks I've made? :) 

Edit: Okay lgtm-com actually found a problem - should have ran it properly 😓 Will fix.

**Review by jdevcs — COMMENTED** [review]
@eddybuilds Thanks for your contribution, some of tests are failing, could you fix these.

**Comment by nazarhussain** [comment]
@eddybuilds  Please add entry to CHANGELOG.md and get this PR ready for review.

**Comment by nazarhussain** [comment]
@eddybuilds Please add entry to CHANGELOG.md and get this PR ready for review.

**Comment by jdevcs** [comment]
This PR is still not completed and has conflicts with `/web3-providers-http/src/index.js` due to recent changes. @eddybuilds feel free to come back and reopen when you have time

**Pull request closed without merging**
