### PR TITLE
Document Formatting

### LINKED ISSUE #6743: Formatting Guide
2024 H1 Action Items: Expand web3.js documentation with 5 guides explaining common usage and/or best practices

### PR DESCRIPTION
**Pull request by danforbes**
Document formatting - closes #6743

### CODE REVIEW

**Review by avkos — APPROVED** [review]

**Review by jdevcs — COMMENTED** [review]
@danforbes In this doc PR, I'll suggest to create formatting guide using functions in packages like web3.eth.getBlockNumber(..), ...

**Comment by danforbes** [comment]
> @danforbes In this doc PR, I'll suggest to create formatting guide using functions in packages like web3.eth.getBlockNumber(..), ...

@jdevcs can you clarify your suggestion? The [existing guide](https://368d1e50.web3-js-docs.pages.dev/guides/getting_started/return-formats) uses `web3.eth.getBlock` as an example. Do you think it would be better to replace that example with one that uses `web3.eth.getBlockNumber`?

**Comment by jdevcs** [comment]
> > @danforbes In this doc PR, I'll suggest to create formatting guide using functions in packages like web3.eth.getBlockNumber(..), ...
> 
> @jdevcs can you clarify your suggestion? The [existing guide](https://368d1e50.web3-js-docs.pages.dev/guides/getting_started/return-formats) uses `web3.eth.getBlock` as an example. Do you think it would be better to replace that example with one that uses `web3.eth.getBlockNumber`?

what do you think for adding one example for each of sub sections specially for formatting numbers using `web3.eth.getBlockNumber`

**Review by Muhammad-Altabba — APPROVED** [review]

**Comment by danforbes** [comment]
> what do you think for adding one example for each of sub sections specially for formatting numbers using `web3.eth.getBlockNumber`

@jdevcs is this what you had in mind? https://f3916c2c.web3-js-docs.pages.dev/guides/getting_started/return-formats

**Comment by jdevcs** [comment]
> > what do you think for adding one example for each of sub sections specially for formatting numbers using `web3.eth.getBlockNumber`
> 
> @jdevcs is this what you had in mind? https://f3916c2c.web3-js-docs.pages.dev/guides/getting_started/return-formats

yes, looks very good,

**Review by jdevcs — APPROVED** [review]

**Pull request merged**
