### PR TITLE
Number Overflow Issue

### LINKED ISSUE #3745: Error while decode transaction gas: "Number can only safely store up to 53 bits"
I tried decode transaction from block but got a error 

```
Number can only safely store up to 53 bits
	at assert ./node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:6
	at BN.toNumber ./node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:506
	at Object.hexToNumber ./node_modules/web3-core-helpers/node_modules/web3-utils/lib/utils.js:208
	at Method.outputTransactionFormatter [as outputFormatter] ./node_modules/web3-core-helpers/lib/formatters.js:204
	at Method.formatOutput ./node_modules/web3-core-method/lib/index.js:147
	at sendTxCallback ./node_modules/web3-core-method/lib/index.js:523
	at ./node_modules/web3-core-requestmanager/lib/index.js:293
	at XMLHttpRequest.request.onreadystatechange ./node_modules/web3-providers-http/lib/index.js:98
	at XMLHttpRequestEventTarget.dispatchEvent ./node_modules/xhr2-cookies/xml-http-request-event-target.ts:44
	at XMLHttpRequest._setReadyState ./node_modules/xhr2-cookies/xml-http-request.ts:219
	at XMLHttpRequest._onHttpResponseEnd ./node_modules/xhr2-cookies/xml-http-request.ts:345
	at IncomingMessage.<anonymous> ./node_modules/xhr2-cookies/xml-http-request.ts:311
	at IncomingMessage.emit events.js:326
	at endReadableNT _stream_readable.js:1252
	at processTicksAndRejections internal/process/task_queues.js:80
```

error occur with tx id `0xe0db32759810271eec05326a4c96fbb42a185139134e16b4581f77456df226a9`

if look closely on https://bscscan.com/tx/0xe0db32759810271eec05326a4c96fbb42a185139134e16b4581f77456df226a9

we can see that gas equal `9,223,372,036,854,775,807`, so web3 js can't convert this string to number 

Anyone has idea how resolve this problem? 

```
import Web3 from 'web3';

async function main() {
  const web3 = new Web3('https://bsc-dataseed1.binance.org:443');

  const res = await web3.eth.getBlock(1365710);

  await Promise.all(
    res.transactions.map(async (txId) => {
      try {
        const tx = await web3.eth.getTransaction(txId);

        console.log(`decode ${txId}`);
      } catch (error) {
        console.error(`error decode ${txId}`);
      }
    }),
  );
}

main();
```

### PR DESCRIPTION
**Pull request by Spacesai1or**
Updates the use of `hexToNumber` to `outputBigNumberFormatter` (which returns a number string instead of a number)

This currently doesn't update other potentially problematic places such as [here](https://github.com/ChainSafe/web3.js/blob/1.x/packages/web3-eth/src/index.js#L517) and [here](https://github.com/ChainSafe/web3.js/blob/1.x/packages/web3-eth-contract/src/index.js#L915)

Fixes #3745, #3912, #3829, and #3936
Supersedes #3789 and #3948

## Notes

- This is a **breaking change** since it updates returns values from numbers to number strings, hence the base branch is `3.x`
- A testing repo that uses problematic code from #3745 and #3912 can be found [here[(https://github.com/spacesailor24/web3-3976)

### CODE REVIEW

**Comment by alstjd0921** [comment]
Currently, no errors are being seen anywhere other than the process of formatting the gas value. I think it's too radical a change.

**Comment by Spacesai1or** [comment]
@alstjd0921 Thank you for commenting/reviewing the code, this was actually a point of discussion I wanted to have:

I've tested your #3948 against the test repo I made, and it does pass using your branch, so presumably it fixes all the mentioned issues. 

However, even though changing one field is more desirable that forcing users to update multiple fields, I want to avoid having to make another breaking change in the future where some field related to gas overflows. So, I would like to keep any updates I've made to fields pertaining to gas, but revert other changes like `block.number` or `transactionIndex`, as they probably won't come near exceeding JavaScript's max integer.

To be specific, the fields I want to remain returning number strings are: `gas`, `cumulativeGasUsed`, `gasUsed`, and `gasLimit` (I will be updating this PR accordingly after this comment)

How do you (and anyone else reading this) feel about this?

P.s. in the rewrite we've started, we will be using the native BigInt, so this won't be a problem going forward

**Comment by Spacesai1or** [comment]
~Blocked by #3982~

**Comment by alstjd0921** [comment]
@spacesailor24 As you said, it seems desirable to limit the problem to gas-related things.
I think it makes sense now. I was just concerned about the change of unrelated with gas overflow (e.g., timestamp, index, or other things) in commit a687dde.

**Comment by Spacesai1or** [comment]
@alstjd0921 if you want to merge [this](https://github.com/alstjd0921/web3.js/pull/1), then we could merge your #3948

**Comment by alstjd0921** [comment]
@spacesailor24 
I merged [this](https://github.com/alstjd0921/web3.js/pull/1) but seems like some checks were broken. Should i handle it?

**Comment by Spacesai1or** [comment]
@alstjd0921 Thought I fixed all the tests, but missed the CI ones. I'm going to work on getting those fixed today

**Comment by Spacesai1or** [comment]
Am now just realizing that the failing tests are a result of pulling the [ganache-core](https://github.com/trufflesuite/ganache-core) repo and running their tests, so I'm trying to figure out what to do about that because of the breaking change

**Comment by Spacesai1or** [comment]
So the plan will be to merge [this](https://github.com/ChainSafe/ganache-core/pull/1), branch off `develop`, update the tests, then target the branch for failing check

**Review by frankiebee — APPROVED** [review]
Wool woop

**Comment by Spacesai1or** [comment]
The was merged with failing `ganache-core` tests. I updated most of the failing tests in [this](https://github.com/ChainSafe/ganache-core/tree/2.13.2-overflow-fix), but there were 3 remaining that seem to need actual core code to be updated

**Comment by sebsobseb** [comment]
Am I correct that the actual `hexToNumber` util method remains the same? It will still return a number?

For example, this check with triple equals will not be impacted? :
`web3.util.hexToNumber("0x4") === 4`

**Pull request merged**
