### PR TITLE
Replace deprecated String.prototype.substr()

### PR DESCRIPTION
**Pull request by CommanderRoot**
## Description

[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [x] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [x] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [x] I have updated the `CHANGELOG.md` file in the root folder.

### CODE REVIEW

**Review by jdevcs — CHANGES_REQUESTED** [review]
@CommanderRoot Thanks for your contributions, Could you also update changelog, and add this PR under 1.7.2

**Comment by CommanderRoot** [comment]
Of course. I've added the changelog entry as requested

**Review by nazarhussain — APPROVED** [review]

**Comment by nazarhussain** [comment]
@CommanderRoot Please resolve the conflicts in `CHANGELOG.md`

**Review by avkos — APPROVED** [review]

**Review by nikoulai — APPROVED** [review]

**Review by jdevcs — APPROVED** [review]

**Comment by jdevcs** [comment]
Merged in 1.x via https://github.com/ChainSafe/web3.js/pull/4941

**Pull request merged**
