### PR TITLE
adding webpack 5

### PR DESCRIPTION
**Pull request by luu-alex**
## Description
(#5629) Webpack 4 -> Webpack 5:
As well an update to webpack, the build size has been made smaller with optimizations in webpack configs.
Packages were added to dev-dependencies due to breaking changes upgrading to webpack 5  

previously: 1.39mb
Screen Shot 2022-11-25 at 5 03 53 PM

current: 1.31mb
Screen Shot 2022-11-25 at 5 01 41 PM

edit: was able to improve and now 1.12-1.13mb
Screen Shot 2022-12-02 at 1 10 11 PM

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist for 1.x:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` with success.
- [ ] I have tested the built `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

## Checklist for 4.x:

- [ ] I have selected the correct 4.x base branch.
- [ ] Within the description, the feature or issue is discussed in detail or an issue is linked.   
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added any required tests for the changes I made 
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `yarn` successfully
- [ ] I ran `yarn lint` successfully
- [ ] I ran `yarn build:web` successfully
- [ ] I ran `yarn test:unit` successfully
- [ ] I ran `yarn test:integration` successfully
- [ ] I ran `compile:contracts` successfully
- [ ] I have tested my code.
- [ ] I have updated the corresponding `CHANGELOG.md` file in the packages I have edited.

### CODE REVIEW

**Review by avkos — CHANGES_REQUESTED** [review]
You have some problems with encrypt/decrypt the wallet in tests. Can it be related to webpack config?

**Comment by luu-alex** [comment]
@avkos yes, a browser test was failing due to the upgrade. its passing now

**Review by avkos — APPROVED** [review]

**Comment by luu-alex** [comment]
Screen Shot 2022-12-02 at 12 51 21 PM
new webpack now produces a web3.min.js.lincese.txt

```
/*
object-assign
(c) Sindre Sorhus
@license MIT
*/

/*!
 * @overview es6-promise - a tiny implementation of Promises/A+.
 * @copyright Copyright (c) 2014 Yehuda Katz, Tom Dale, Stefan Penner and contributors (Conversion to ES6 API by Jake Archibald)
 * @license   Licensed under MIT license
 *            See https://raw.githubusercontent.com/stefanpenner/es6-promise/master/LICENSE
 * @version   v4.2.8+1e68dce6
 */

/*!
 * The buffer module from node.js, for the browser.
 *
 * @author   Feross Aboukhadijeh <feross@feross.org> <http://feross.org>
 * @license  MIT
 */

/*!
 * The buffer module from node.js, for the browser.
 *
 * @author   Feross Aboukhadijeh <http://feross.org>
 * @license  MIT
 */

/*!
 * v2.1.4-104-gc868b3a
 * 
 */

/*! https://mths.be/utf8js v3.0.0 by @mathias */

/*! ieee754. BSD-3-Clause License. Feross Aboukhadijeh <https://feross.org/opensource> */

/*! regenerator-runtime -- Copyright (c) 2014-present, Facebook, Inc. -- license (MIT): https://github.com/facebook/regenerator/blob/main/LICENSE */

/*! safe-buffer. MIT License. Feross Aboukhadijeh <https://feross.org/opensource> */

/**
 * [js-sha3]{@link https://github.com/emn178/js-sha3}
 *
 * @version 0.5.7
 * @author Chen, Yi-Cyuan [emn178@gmail.com]
 * @copyright Chen, Yi-Cyuan 2015-2016
 * @license MIT
 */

/**
 * [js-sha3]{@link https://github.com/emn178/js-sha3}
 *
 * @version 0.8.0
 * @author Chen, Yi-Cyuan [emn178@gmail.com]
 * @copyright Chen, Yi-Cyuan 2015-2018
 * @license MIT
 */

```
Its an MIT license for some modules, it looks ok to keep

**Review by nikoulai — APPROVED** [review]

**Review by jdevcs — COMMENTED** [review]
@luu-alex was [compatibility](https://webpack.js.org/migrate/5/#test-webpack-5-compatibility) test working fine before this change?

**Comment by luu-alex** [comment]
@jdevcs yes 👍

**Review by jdevcs — APPROVED** [review]

**Comment by jdevcs** [comment]
Before merging we should make sure manually that newly packed web3.js with webpack 5 following is passing:
https://github.com/web3/web3.js/tree/1.x/scripts/html

**Comment by luu-alex** [comment]
No errors caused by script 👍 
Screen Shot 2022-12-06 at 8 39 09 AM
@jdevcs

**Review by Sammiegirl411 — COMMENTED** [review]
Yes

**Review by Sammiegirl411 — COMMENTED** [review]
Yes

**Pull request merged**
