### PR TITLE
Converted the rest of the tests to es6

### PR DESCRIPTION
**Pull request by dacarley**

### CODE REVIEW

**Comment by frozeman** [comment]
@dacarley please change mocha reporters to `dot`, it gives better overview errors show the actual problems anyway.

You have one test failing: 
```
  1) web3-providers-http
       send
         should send basic async request:

      AssertionError: expected 'undefined' to equal 'object'
      + expected - actual

      -undefined
      +object
```

**Comment by dacarley** [comment]
I switched to the "dot" reporter for Mocha, and removed a stray "console.error" that shouldn't have been in the code at all.

I don't see the test failure you're referring to, either on my machine, or in Travis.

What node and npm version are you using when you see the failure?

**Comment by frozeman** [comment]
I use node 6 I think. Not on my comp to check.

**Comment by frozeman** [comment]
I will try tomorrow again. Thanks for the great work!

**Comment by dacarley** [comment]
I just tried a fresh enlistment on Node 6.11.5 / NPM 3.10.10, and all is well.

**Comment by frozeman** [comment]
There seems to be a left over in mocha, because when i run it standalone the test passes: `mocha test/httpprovider.js`.

I removed the node modules folder and re-run all and now it passes :) Thanks.

Currently the listing is not running, you removed that from the npm test call? Is it because it wouldn't pass yet?

**Comment by dacarley** [comment]
I'm not sure what you mean by "the listing is not running"?

**Comment by frozeman** [comment]
Linting

**Comment by dacarley** [comment]
No, that was an oversight on my part -- I'll address that in my next PR.

**Pull request merged**
