### PR TITLE
sha3 in browser

### PR DESCRIPTION
**Pull request by debris**
- this will fix sending call && sendTransaction in batch

### CODE REVIEW

**Comment by kumavis** [comment]
@debris is this correct? seems like you'll need to pluck off any '0x' prefix on the input and add it back on the result. Also, what kind of input is it expecting? hex string, big num, buffer?

**Comment by debris** [comment]
@kumavis, Yes, it's correct. It expects plain string and the output is a string without `0x` prefix. For backwards compatibility we also can provide support for hex form of the string as an input. Although I don't think it's really necessary (We still haven't released).

**was**

```javascript
var x = web3.sha3(web3.fromAscii('helloWorld'));
console.log(x); // 0xfff...
```

**is**

```javascript
web3.sha3('helloWorld');
console.log(x); // fff...
```

**Comment by kumavis** [comment]
@debris i mean that `web3.fromAscii('helloWorld') // 0xfff` has the hex prefix, which will be part of the content that gets hashed

**Comment by kumavis** [comment]
ah sorry reading again I got it

**Comment by kumavis** [comment]
@debris even though you "haven't released" many developers including myself do rely on web3. if you can keep at least a primitive migration notes, that would be much appreciated.

**Comment by debris** [comment]
@kumavis, before merging to master I will prepare migration notes.

**Comment by kumavis** [comment]
yaay :joy_cat:

**Pull request merged**
