### PR TITLE
Apply `context` in constructor

### LINKED ISSUE #5802: `new Contract(abi, web3Context)` doesn't apply context to instance
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```typescript
const web3Context = new Web3Context('http://127.0.0.1:8545');
const contract = new Contract(abi, web3Context);
```

Should apply `web3Context` to `contract` instance, but [this](https://github.com/web3/web3.js/blob/e00bd8425ef6f2c6122030838bae665b3475a4ab/packages/web3-eth-contract/src/contract.ts#L322) `context` argument is never used within the constructor

### Expected Behavior

`new Contract(abi, web3Context);` applied the given context to the `Contract` instance

### Steps to Reproduce

```typescript
const web3Context = new Web3Context('http://127.0.0.1:8545');
const contract = new Contract(abi, web3Context);
```

### Web3.js Version

4.x.x

### Environment

_No response_

### Anything Else?

_No response_

### PR DESCRIPTION
**Pull request by kevinam99**
## Description

Aims to fix the issue linked below to apply `context` in the constructor which was previously not done.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist for 4.x:

- [x] I have selected the correct 4.x base branch.
- [x] Within the description, the feature or issue is discussed in detail or an issue is linked.   
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added any required tests for the changes I made 
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged and published in downstream modules.
- [x] I ran `yarn` successfully
- [x] I ran `yarn lint` successfully
- [x] I ran `yarn build:web` successfully
- [x] I ran `yarn test:unit` successfully
- [x] I ran `yarn test:integration`
- [x] I ran `compile:contracts` successfully but it ended up removing important comments, so didn't commit this change
- [x] I have tested my code.
- [ ] I have updated the corresponding `CHANGELOG.md` file in the packages I have edited.

### CODE REVIEW

**Comment by kevinam99** [comment]
I can't seem to add the `pleasereview` label. Could anyone with permissions please add it?

**Comment by Spacesai1or** [comment]
Hi there! Thank you for your interest in contributing to web3.js!

After reviewing the change you made, I've realized that I made a mistake in my understanding of the overloaded `constructor`: Only [these](https://github.com/web3/web3.js/blob/4e748c5cef8f7c99e38f285492fd8f2def7f265c/packages/web3-eth-contract/src/contract.ts#L282-L294) parameter names are to be used within the `constructor`. This is because TypeScript allows for overloaded constructors, but only allows for a single implementation that is compatible with the other defined function signatures. This is why the second constructor argument is called `addressOrOptionsOrContext`, because it's a catch-all for all the second arguments mentioned in the function signatures above it

I suspect that the bug causing #5802 is probably because of the first part of [this](https://github.com/web3/web3.js/pull/5756#discussion_r1091434230) comment. If you'd still like to contribute to web3.js, you could see if this is actually the issue and attempt to fix the bug there. Either way, thank you for your interest in helping us maintain the library

**Comment by kevinam99** [comment]
Thank you for the very detailed explanation. Could you help me with some guidance on where or how I could start? Would be nice to contribute to this project since I am a user myself at work and personal projects.

**Comment by Spacesai1or** [comment]
From the comment I linked above,

> When `Contract` is passed an instance of `Web3Context`, [this config](https://github.com/web3/web3.js/blob/4bbc030ba86f2e5b6494b395d77acce130d90c66/packages/web3-core/src/web3_context.ts#L127) is `undefined` because the expected `Web3Context.config` is actually [_config](https://github.com/web3/web3.js/blob/4bbc030ba86f2e5b6494b395d77acce130d90c66/packages/web3-core/src/web3_config.ts#L68) and `Web3Config.getConfig` is expected to be used to access the `config` object

So I'm assuming we'd need to update `Web3Context` to get `_config` from `providerOrContext`[here](https://github.com/web3/web3.js/blob/4bbc030ba86f2e5b6494b395d77acce130d90c66/packages/web3-core/src/web3_context.ts#L134) if `providerOrContext` is an `instanceof` `Web3Context` using `getConfig` or something

**Comment by Spacesai1or** [comment]
If you're curious @kevinam99, [this](https://github.com/web3/web3.js/pull/5950/files#diff-5e56e7b4c4229c78c1bea8ddfb8baaa68f22a7f07d5efcd78d2e5c56eb014410R68) was a possible fix for this issue

Thank you again for your interest and contributions! Closing this in favor of #5950

**Comment by kevinam99** [comment]
Thank you @spacesailor24. I had just gotten some time to work on it, but no problem.

**Comment by Spacesai1or** [comment]
@kevinam99 sorry about that, I'll keep you in mind if any other good-first-issues pop up, but if you'd still like to contribute, testing the latest RC for 4.x in your projects would be a huge help as we're trying to iron out any issues for migrating users

**Comment by kevinam99** [comment]
@spacesailor24 sure, thanks :)
I'll check the latest RC like you said and create an issue in case I find something.

**Pull request closed without merging**
