### PR TITLE
Update web3-core-requestmanager/src/index.js - Listen to incoming notifications

### PR DESCRIPTION
**Pull request by alonavns**
### Case

- Connect Dapp to Metamask
- Change Wallet

### Error

```
Unhandled Runtime Error
TypeError: Cannot read property 'subscription' of undefined

Call Stack
t.exports.data
node_modules/web3-core-requestmanager/src/index.js (104:0)
u
chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js (1:129212)
t.exports.a.emit
chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js (1:129794)
a.<anonymous>
chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js (1:8520)
u
chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js (1:129212)
a.emit
chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js (1:129737)
<unknown>
chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js (1:89596)
l.write [as _write]
chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js (1:89619)
b
chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js (1:116940)
<unknown>
chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js (1:120056)
l.v.write
chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js (1:120083)
a.y
chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js (1:109376)
h
chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js (1:40426)
a.s.emit
chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js (1:43412)
_
chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js (1:104215)
w
chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js (1:104030)
a.b.push
chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js (1:104841)
t.exports._write
chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js (1:93581)
b
chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js (1:116940)
<unknown>
chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js (1:120056)
t.exports.v.write
chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js (1:120083)
o.y
chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js (1:109376)
h
chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js (1:40426)
o.s.emit
chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js (1:43412)
_
chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js (1:104215)
w
chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js (1:104030)
o.b.push
chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js (1:104841)
o._onMessage
chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js (1:96151)
```

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] My changes generate no new warnings.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.

## Environment

- MetaMask Version (8.0.4)
- Next.js Dapp (9.4.4)
- Web3 (1.2.9)
- Node (10.16.0)
- NPM (6.14.4)

## Screenshot

image

### CODE REVIEW

**Comment by GregTheGreek** [comment]
Can you provide a test repo/gist?

**Comment by su45fg** [comment]
repo/test ผ่านเเล้วครับ

**Comment by su45fg** [comment]
patch

**Comment by GregTheGreek** [comment]
@alonavns So i linked this package into the metamask test repo, and subscribed to new block headers. unfortunately it returned me some errors. Are you able to produce a workable demo that shows this fix works?

**Comment by GregTheGreek** [comment]
Thank you for the contribution! Unfortunately we needed to get a fix in, I'm closing this because it was superseded by #3660

**Pull request closed without merging**
