### PR TITLE
Fix incorrectly versioned bn.js type export (#4418)

### PR DESCRIPTION
**Pull request by Spacesai1or**
Took over the original PR to make some changes

### CODE REVIEW

**Comment by Spacesai1or** [comment]
Oh I think [I'm wrong](https://stackoverflow.com/questions/45176661/how-do-i-decide-whether-types-goes-into-dependencies-or-devdependencies#:~:text=In%20that%20particular%20case%20you,%22devDependencies%22%20are%20good%20enough.&text=If%20you're%20just%20generating,distinction%20between%20dependencies%20and%20devDependencies%20.) about including `@types/bn.js` as a `dev-dependency`

In this particular case, we want to provide users with the specific version of the types so that type mismatches don't occur

**Review by nazarhussain — CHANGES_REQUESTED** [review]
As per the change log we have very minimal change.

> `@types/bn.js` as dev-dependency to additional packages (notably web3-utils)

But the files which are changed are 27, Is there a possibility to only include required changes in this PR. And if there is any other package update we can create specific PR for it.

**Comment by Spacesai1or** [comment]
@nazarhussain 

> As per the change log we have very minimal change.
> 
> > `@types/bn.js` as dev-dependency to additional packages (notably web3-utils)
> 
> But the files which are changed are 27, Is there a possibility to only include required changes in this PR. And if there is any other package update we can create specific PR for it.

The files changes are all updates to `package.json` and `package-lock.json` (minus `CHANGELOG.md`). Updating these files all at once, and not trying to discern what `package-lock.json` changes are bare minimum necessary, is the easiest way to avoid breaking something, imo

**Review by nazarhussain — APPROVED** [review]

**Review by luu-alex — APPROVED** [review]

**Review by deauna — COMMENTED** [review]
cheers

**Pull request merged**
