### PR TITLE
update node versions

### PR DESCRIPTION
**Pull request by luu-alex**
#4888 Updating node version for builds and fixing mosaic tests that were failing due to [node 12 version](https://github.com/ChainSafe/web3.js/runs/7612528975?check_suite_focus=true). Was running into issues trying to include more node versions with what seemed like random 1-2 test cases failing
## Description

Please include a summary of the changes and be sure to follow our [Contribution Guidelines](../blob/1.x/CONTRIBUTIONS.md).

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` with success.
- [ ] I have tested the built `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

### CODE REVIEW

**Comment by jdevcs** [comment]
LGTM, for :

> Was running into issues trying to include more node versions with what seemed like random 1-2 test cases failing

wts are error logs?

**Comment by jdevcs** [comment]
For 
image
I updated 1.x repo branch rules., so with new commit push it will not be required.

**Review by jdevcs — APPROVED** [review]

**Comment by jdevcs** [comment]
Is this duplicate PR https://github.com/ChainSafe/web3.js/pull/5314 ? For current PR, also mention it in changelog. Thanks

**Review by nikoulai — APPROVED** [review]

**Comment by luu-alex** [comment]
@jdevcs when using [node 14 and node 16 ](https://github.com/ChainSafe/web3.js/pull/5314/commits/f753071aca46ebca31ef05f515c61ad9ebd7ec94) node-gyp has an error installing and mosaic has a test contract error. heres the [CI](https://github.com/ChainSafe/web3.js/runs/7884587389?check_suite_focus=true)

**Comment by luu-alex** [comment]
@jdevcs yes is a duplicate, will close the other

**Pull request merged**
