### PR TITLE
1.7.4

### PR DESCRIPTION
**Pull request by jdevcs**
### Fixed
-  Fix dead link in web3-eth.rst (#4916)
-  Fix web3-core-method throws on `f.call = this.call` when intrinsic is frozen (#4918) (#4938)
-  Fix static tuple encoding (#4673) (#4884)
-  Fix bug in handleRevert logic for eth_sendRawTransaction (#4902)
-  Fix resolve type of getBlock function (#4911)
-  Web3-utils BN fix (#5132)

### Changed
-  Replace deprecated String.prototype.substr() (#4855)
-  Exporting AbiCoder as coder (#4937)
-  Github build workflow updated min build for node.js 12 and tests for 12, 14 and 16 (#5014)
-  Updated libraries using BN and the BN library (#5072)

### Added
- Exposing `web3.eth.Contract.setProvider()` as per public documentation (#4822) (#5001)
- Improve npm script commands for development purposes (#4848)

### Security
-  `npm audit fix` to address vulnerabilities and update libraries (#5014)

### CODE REVIEW

**Comment by jdevcs** [comment]
As part of the RC process, following test installations are performed in other projects and running their tests to see if everything.  
+ installs properly
+ builds
+ tests pass

(This list will be actively edited) 

| Project | Desc | Status | 
| ------ | ----- | ----- |
| [oz-test-helpers][1] | Test utils. Subset of their suite is web3 contracts |  |
| [synthetix][2] | ~1000 units |   |


[1]: https://github.com/OpenZeppelin/openzeppelin-test-helpers
[2]: https://github.com/Synthetixio/synthetix

**Review by nazarhussain — APPROVED** [review]

**Comment by jdevcs** [comment]
For 1.7.4-rc.1:

As part of the RC process, following test installations are performed in other projects and running their tests to see if everything.  
+ installs properly
+ builds
+ tests pass

(This list will be actively edited) 

| Project | Desc | Status | 
| ------ | ----- | ----- |
| [oz-test-helpers][1] | Test utils. Subset of their suite is web3 contracts | x  |
| [synthetix][2] | ~1000 units |  ✓ |


[1]: https://github.com/OpenZeppelin/openzeppelin-test-helpers
[2]: https://github.com/Synthetixio/synthetix

**Comment by luu-alex** [comment]
Synthetix test passed for 1.7.4-rc.1 ✔️ , open zepelin testcases had around 80 failing test cases due to attributes not existing on web3.utils.BN due to my BN PR that merged. https://github.com/ChainSafe/web3.js/pull/5132 This PR fixes it.

**Comment by jdevcs** [comment]
For 1.7.4-rc.2:

As part of the RC process, following test installations are performed in other projects and running their tests to see if everything.  
+ installs properly
+ builds
+ tests pass

(This list will be actively edited) 

| Project | Desc | Status | 
| ------ | ----- | ----- |
| [oz-test-helpers][1] | Test utils. Subset of their suite is web3 contracts | ✅  |
| [synthetix][2] | ~1000 units | ✅  |


[1]: https://github.com/OpenZeppelin/openzeppelin-test-helpers
[2]: https://github.com/Synthetixio/synthetix

**Comment by luu-alex** [comment]
For 1.7.4-rc.2:

As part of the RC process, following test installations are performed in other projects and running their tests to see if everything.  
+ installs properly
+ builds
+ tests pass

(This list will be actively edited) 

| Project | Desc | Status | 
| ------ | ----- | ----- |
| [oz-test-helpers][1] | Test utils. Subset of their suite is web3 contracts | ✅   |
| [synthetix][2] | ~1000 units |  ✅  |


[1]: https://github.com/OpenZeppelin/openzeppelin-test-helpers
[2]: https://github.com/Synthetixio/synthetix

**Review by luu-alex — APPROVED** [review]

**Review by nikoulai — APPROVED** [review]

**Comment by wbt** [comment]
FYI, this turned out to be a breaking change on nonbreaking semver, as discussed in more detail in the above-linked comment.

**Pull request merged**
