### PR TITLE
Update: using provided gas options for eip-1559 tx

### PR DESCRIPTION
**Pull request by chendatony31**
## Description

We should use provided gas options for eip-1559 tx same as the legacy ones, and avoid useless RPC requests

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [x] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [x] I ran `npm run build` with success.
- [x] I have tested the built `dist/web3.min.js` in a browser.
- [x] I have tested my code on the live network.
- [x] I have checked the Deploy Preview and it looks correct.
- [x] I have updated the `CHANGELOG.md` file in the root folder.

### CODE REVIEW

**Review by nazarhussain — APPROVED** [review]

**Review by nazarhussain — CHANGES_REQUESTED** [review]
@chendatony31 The change looks good. Can you please add at least one test to cover this scenario?

**Review by avkos — APPROVED** [review]

**Review by nikoulai — APPROVED** [review]

**Review by nazarhussain — APPROVED** [review]

**Comment by chendatony31** [comment]
Rebased

**Review by jdevcs — CHANGES_REQUESTED** [review]
@chendatony31 change log update is also required

**Comment by chendatony31** [comment]
Done @jdevcs

**Review by jdevcs — APPROVED** [review]

**Comment by jdevcs** [comment]
@chendatony31 due to recent merge of another PR there are merge conflicts, could you fix those.

**Comment by chendatony31** [comment]
@jdevcs  Any plan to merge this PR? As it has been about 3 months

**Comment by jdevcs** [comment]
merged into 1.x via https://github.com/ChainSafe/web3.js/pull/5418

**Pull request merged**
