### PR TITLE
treat RLP 'r' and 's' fields as quantity, not string

### LINKED ISSUE #1170: eth.accounts.signTransaction: expected r & s to be treated as quantity, not data
According to the docs, [r & s are returned from signTransaction with leading zeros](https://web3js.readthedocs.io/en/1.0/web3-eth-accounts.html#id6), implying that they are always 32 bytes of binary data. In many other implementations that return r & s (geth, parity, ethereum-keys), they are treated as integers, without leading zeros.

I would expect r & s in web3.eth.accounts.signTransaction to follow the same pattern.

### PR DESCRIPTION
**Pull request by jellegerbrandy**
This fixes #1170 by using the patch provided by @ldn0x7dc in that issue

### CODE REVIEW

**Comment by carver** [comment]
This change in output seems like the right thing to do, but it doesn't completely fix #1170. `r` and `s` fields should have single leading `0`s trimmed as well (when returned individually in https://github.com/ethereum/web3.js/pull/1258/files#diff-7bb2a20126193b9ecfe4723f83429c49R168 ).

**Comment by jellegerbrandy** [comment]
You are right of course; should be better now

**Comment by malissa** [comment]
Would love to get this merged in!

**Comment by jellegerbrandy** [comment]
Applying the patch in our code, and running it against parity, returns the following error (from Parity):

```Invalid params: Invalid bytes format. Expected a 0x-prefixed hex string with even length.```

Apparently, the issue is more complex than I had hoped. This issue seems related as well: https://github.com/ethereumjs/ethereumjs-tx/issues/51

In our code, we have gone back to the "strip two leading zeros" code, and that seems to work fine against parity.

**Comment by malissa** [comment]
@jellegerbrandy I also received an error (using geth) when stripping zeros resulted in an odd numbered string. I will try removing two leading zeros - should at least improve the number of times I receive this error which is A LOT.

**Comment by jellegerbrandy** [comment]
I reverted the commit stripping _all_ leading zeros, which clearly was mistaken. Apparently, `geth` and `parity` expect strings with an even number of characters that do not start with `0x00`... the documentation does not help me much here, unfortunately..

**Comment by carver** [comment]
RLP encoding is one byte at the smallest unit. Represented as a hex string, that's two hex characters at a time. So for the rlp encoding here, it should only trim 0 **bytes** (double 0 hex characters): https://github.com/ethereum/web3.js/pull/1258/files#diff-7bb2a20126193b9ecfe4723f83429c49R162

But for the `r` and `s` values, which are not RLP-encoded when returned individually, they should trim down all leading hex 0 characters. https://github.com/ethereum/web3.js/pull/1258/files#diff-7bb2a20126193b9ecfe4723f83429c49R168

**Comment by frozeman** [comment]
Thanks for the fix! And sorry for the delay, i was not available over christmas.

**Comment by malissa** [comment]
Woot! Thanks for this!

**Comment by frozeman** [comment]
It would be good to add a few test cases, does somebody have a tx and key which results in the 0x00.. r, s values?

**Comment by malissa** [comment]
Of course now I am unable to get an error. I will comment here if I come across one.

**Comment by carver** [comment]
I just posted short r & s values in #1170

**Comment by frozeman** [comment]
@malissa you could use a previous commit :)

**Pull request merged**
