### PR TITLE
Fix Provider Compatibility with EIP 1193

### LINKED ISSUE #5590: [4.x] Ganache EthereumProvider type not compatible with Web3 constructor
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Yields type error:
```
index.ts:17:27 - error TS2345: Argument of type 'EthereumProvider' is not assignable to parameter of type 'string | SupportedProviders<EthExecutionAPI> | undefined'.
  Type 'EthereumProvider' is missing the following properties from type 'Web3BaseProvider<EthExecutionAPI>': getStatus, supportsSubscriptions, connect, reset, [symbol]

17     const web3 = new Web3(provider)
```

### Expected Behavior

Should work.

### Steps to Reproduce

```typescript
import Web3 from "web3"
import ganache from "ganache";

(async function() {
    const LOCAL_PREFUNDED_MNEMONIC =
  "pioneer casual canoe gorilla embrace width fiction bounce spy exhibit another dog";
    
    const server = ganache.server({
        wallet: {
            mnemonic: LOCAL_PREFUNDED_MNEMONIC,
            defaultBalance: 100,
        },
    });
    const provider = server.provider;

    const web3 = new Web3(provider)
})()
```

### Web3.js Version

4.0.1-alpha.1

### Environment

- Operating System: 
- Browser: 
- Node.js Version: 
- NPM Version: 

### Anything Else?

_No response_

### PR DESCRIPTION
**Pull request by Muhammad-Altabba**
## Description

Fixes #5590

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist for 1.x:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` with success.
- [ ] I have tested the built `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

## Checklist for 4.x:

- [ ] I have selected the correct 4.x base branch.
- [ ] Within the description, the feature or issue is discussed in detail or an issue is linked.   
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added any required tests for the changes I made 
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `yarn` successfully
- [ ] I ran `yarn lint` successfully
- [ ] I ran `yarn build:web` successfully
- [ ] I ran `yarn test:unit` successfully
- [ ] I ran `yarn test:integration` successfully
- [ ] I ran `compile:contracts` successfully
- [ ] I have tested my code.
- [ ] I have updated the corresponding `CHANGELOG.md` file in the packages I have edited.

### CODE REVIEW

**Comment by nikoulai** [comment]
Good work! Could we also add some tests (similar to the example in the issue report) ?

**Review by nikoulai — APPROVED** [review]

**Comment by Muhammad-Altabba** [comment]
> Good work! Could we also add some tests (similar to the example in the issue report) ?

Thanks Nikos, 
Actually, I hoped for a test but the original issue was about the compatibility with Ganache. As you can find, it has `import ganache from "ganache";`. So, on my local machine, I made a test application for this and used the full code provided. But we cannot have this as part of this repo as such an approach would increase the size drastically.

**Review by luu-alex — APPROVED** [review]

**Comment by luu-alex** [comment]
Hey there @Muhammad-Altabba perhaps Could be added as a testing library in a chainsafe repo

**Comment by nikoulai** [comment]
> > Good work! Could we also add some tests (similar to the example in the issue report) ?
> 
> Thanks Nikos, Actually, I hoped for a test but the original issue was about the compatibility with Ganache. As you can find, it has `import ganache from "ganache";`. So, on my local machine, I made a test application for this and used the full code provided. But we cannot have this as part of this repo as such an approach would increase the size drastically.

I believe that adding the package as `devDependency` would be ok

**Pull request merged**
