### PR TITLE
Use async contract calls when a callback is passed

### PR DESCRIPTION
**Pull request by niran**

### CODE REVIEW

**Comment by niran** [comment]
I put this together when I thought that synchronous contract calls were making my app slow, which was incorrect. This might not be worth pursuing in the near term, but at the very least, the documentation for `Contract.call` should mention that it should be so fast on localhost that you shouldn't really need an async version.

**Comment by niran** [comment]
Never mind, the synchronous calls are actually making the app slow. What do I need to do to get something like this merged?

**Comment by debris** [comment]
This looks good and I like the idea of having asynchronous calls, but unfortunately it interferes with `toPayload` method in `SolidityFunction.prototype` (see [transactionObject](https://github.com/ethereum/wiki/wiki/JavaScript-API#contract-methods) in docs). We need a better way to solve passing arguments,callback and 'transactionObject' to solidity functions.

Suggestions are welcomed. :+1:

**Comment by frozeman** [comment]
Please direct your PR into develop no master. @debris can you take a look?

**Comment by debris** [comment]
I'm closing, cause it's gonna be a part of #199. Thanks @niran !

**Pull request closed without merging**
