### PR TITLE
remove symlinks 

### PR DESCRIPTION
**Pull request by luu-alex**
## Description
#5075 

this PR addresses an issue with building errors from windows computers.

Symlinks paths are not supported the same way on windows/linux leading to an error when trying to build.
This PR replaces the symlink files with the actual file. As well I added a new [script](https://github.com/web3/web3.js/pull/6189/files#diff-e41175d590aa54fc8ae016d998b32e947e8fa221a0c2dba8dccaa7af803e4d73), it generates files based on the source  template and target directory.

in this pr as well, theres some config and template clean up

The notable changes in this PR:
-  a new [script](https://github.com/web3/web3.js/pull/6189/files#diff-e41175d590aa54fc8ae016d998b32e947e8fa221a0c2dba8dccaa7af803e4d73)
- symlinks are removed in favor of generating templates into project folders
- some config folders are moved to the `config` directory

Please include a summary of the changes and be sure to follow our [Contribution Guidelines](../CONTRIBUTIONS.md).

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run lint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:coverage` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [ ] I have linked Issue(s) with this PR in "Linked Issues" menu.

### CODE REVIEW

**Comment by jdevcs** [comment]
@luu-alex have you tried building 4.x using:
Windows Subsystem for Linux (WSL)

**Comment by luu-alex** [comment]
@jdevcs  yes it works properly

**Comment by luu-alex** [comment]
The windows build properly now, but it runs into a typescript compile issue
```
web3-errors: $ yarn build:cjs & yarn build:esm & yarn build:types     
web3-errors: $ tsc --build tsconfig.cjs.json && echo '{"type": "commonjs"}' > ./lib/commonjs/package.json
web3-errors: C:\Users\Im cyborg\web3.js\packages\web3-errors\node_modules\typescript\lib\tsc.js:96888
web3-errors:                 throw e;
web3-errors:                 ^
web3-errors: SyntaxError: Unexpected token ' in JSON at position 0    
web3-errors:     at JSON.parse (<anonymous>)
web3-errors:     at tryDirectoryWithPackageJson (C:\Users\Im cyborg\web3.js\packages\web3-errors\node_modules\typescript\lib\tsc.js:101146:163)
web3-errors:     at tryGetModuleNameAsNodeModule (C:\Users\Im cyborg\web3.js\packages\web3-errors\node_modules\typescript\lib\tsc.js:101105:30)
web3-errors:     at computeModuleSpecifiers (C:\Users\Im cyborg\web3.js\packages\web3-errors\node_modules\typescript\lib\tsc.js:100757:33)  
web3-errors:     at getModuleSpecifiersWithCacheInfo (C:\Users\Im cyborg\web3.js\packages\web3-errors\node_modules\typescript\lib\tsc.js:100728:26)
web3-errors:     at Object.getModuleSpecifiers (C:\Users\Im cyborg\web3.js\packages\web3-errors\node_modules\typescript\lib\tsc.js:100712:20)
web3-errors:     at getSpecifierForModuleSymbol (C:\Users\Im cyborg\web3.js\packages\web3-errors\node_modules\typescript\lib\tsc.js:44013:62)
web3-errors:     at C:\Users\Im cyborg\web3.js\packages\web3-errors\node_modules\typescript\lib\tsc.js:43887:39
web3-errors:     at Array.map (<anonymous>)
web3-errors:     at getSymbolChain (C:\Users\Im cyborg\web3.js\packages\web3-errors\node_modules\typescript\lib\tsc.js:43885:58)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
web3-errors: error Command failed with exit code 1.
web3-errors: $ tsc --build tsconfig.esm.json && echo '{"type": "module"}' > ./lib/esm/package.json
web3-errors: $ tsc --build tsconfig.types.json
web3-errors: C:\Users\Im cyborg\web3.js\packages\web3-errors\node_modules\typescript\lib\tsc.js:96888
web3-errors:                 throw e;
web3-errors:                 ^
web3-errors: SyntaxError: Unexpected token ' in JSON at position 0    
web3-errors:     at JSON.parse (<anonymous>)
web3-errors:     at tryDirectoryWithPackageJson (C:\Users\Im cyborg\web3.js\packages\web3-errors\node_modules\typescript\lib\tsc.js:101146:163)
web3-errors:     at tryGetModuleNameAsNodeModule (C:\Users\Im cyborg\web3.js\packages\web3-errors\node_modules\typescript\lib\tsc.js:101105:30)
web3-errors:     at computeModuleSpecifiers (C:\Users\Im cyborg\web3.js\packages\web3-errors\node_modules\typescript\lib\tsc.js:100757:33)  
web3-errors:     at getModuleSpecifiersWithCacheInfo (C:\Users\Im cyborg\web3.js\packages\web3-errors\node_modules\typescript\lib\tsc.js:100728:26)
web3-errors:     at Object.getModuleSpecifiers (C:\Users\Im cyborg\web3.js\packages\web3-errors\node_modules\typescript\lib\tsc.js:100712:20)
web3-errors:     at getSpecifierForModuleSymbol (C:\Users\Im cyborg\web3.js\packages\web3-errors\node_modules\typescript\lib\tsc.js:44013:62)
web3-errors:     at C:\Users\Im cyborg\web3.js\packages\web3-errors\node_modules\typescript\lib\tsc.js:43887:39
web3-errors:     at Array.map (<anonymous>)
web3-errors:     at getSymbolChain (C:\Users\Im cyborg\web3.js\packages\web3-errors\node_modules\typescript\lib\tsc.js:43885:58)
web3-errors: error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
web3-errors: error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Spacesai1or** [comment]
> The windows build properly now, but it runs into a typescript compile issue
> 
> ```
> web3-errors: $ yarn build:cjs & yarn build:esm & yarn build:types     
> web3-errors: $ tsc --build tsconfig.cjs.json && echo '{"type": "commonjs"}' > ./lib/commonjs/package.json
> web3-errors: C:\Users\Im cyborg\web3.js\packages\web3-errors\node_modules\typescript\lib\tsc.js:96888
> web3-errors:                 throw e;
> web3-errors:                 ^
> web3-errors: SyntaxError: Unexpected token ' in JSON at position 0    
> web3-errors:     at JSON.parse (<anonymous>)
> web3-errors:     at tryDirectoryWithPackageJson (C:\Users\Im cyborg\web3.js\packages\web3-errors\node_modules\typescript\lib\tsc.js:101146:163)
> web3-errors:     at tryGetModuleNameAsNodeModule (C:\Users\Im cyborg\web3.js\packages\web3-errors\node_modules\typescript\lib\tsc.js:101105:30)
> web3-errors:     at computeModuleSpecifiers (C:\Users\Im cyborg\web3.js\packages\web3-errors\node_modules\typescript\lib\tsc.js:100757:33)  
> web3-errors:     at getModuleSpecifiersWithCacheInfo (C:\Users\Im cyborg\web3.js\packages\web3-errors\node_modules\typescript\lib\tsc.js:100728:26)
> web3-errors:     at Object.getModuleSpecifiers (C:\Users\Im cyborg\web3.js\packages\web3-errors\node_modules\typescript\lib\tsc.js:100712:20)
> web3-errors:     at getSpecifierForModuleSymbol (C:\Users\Im cyborg\web3.js\packages\web3-errors\node_modules\typescript\lib\tsc.js:44013:62)
> web3-errors:     at C:\Users\Im cyborg\web3.js\packages\web3-errors\node_modules\typescript\lib\tsc.js:43887:39
> web3-errors:     at Array.map (<anonymous>)
> web3-errors:     at getSymbolChain (C:\Users\Im cyborg\web3.js\packages\web3-errors\node_modules\typescript\lib\tsc.js:43885:58)
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> web3-errors: error Command failed with exit code 1.
> web3-errors: $ tsc --build tsconfig.esm.json && echo '{"type": "module"}' > ./lib/esm/package.json
> web3-errors: $ tsc --build tsconfig.types.json
> web3-errors: C:\Users\Im cyborg\web3.js\packages\web3-errors\node_modules\typescript\lib\tsc.js:96888
> web3-errors:                 throw e;
> web3-errors:                 ^
> web3-errors: SyntaxError: Unexpected token ' in JSON at position 0    
> web3-errors:     at JSON.parse (<anonymous>)
> web3-errors:     at tryDirectoryWithPackageJson (C:\Users\Im cyborg\web3.js\packages\web3-errors\node_modules\typescript\lib\tsc.js:101146:163)
> web3-errors:     at tryGetModuleNameAsNodeModule (C:\Users\Im cyborg\web3.js\packages\web3-errors\node_modules\typescript\lib\tsc.js:101105:30)
> web3-errors:     at computeModuleSpecifiers (C:\Users\Im cyborg\web3.js\packages\web3-errors\node_modules\typescript\lib\tsc.js:100757:33)  
> web3-errors:     at getModuleSpecifiersWithCacheInfo (C:\Users\Im cyborg\web3.js\packages\web3-errors\node_modules\typescript\lib\tsc.js:100728:26)
> web3-errors:     at Object.getModuleSpecifiers (C:\Users\Im cyborg\web3.js\packages\web3-errors\node_modules\typescript\lib\tsc.js:100712:20)
> web3-errors:     at getSpecifierForModuleSymbol (C:\Users\Im cyborg\web3.js\packages\web3-errors\node_modules\typescript\lib\tsc.js:44013:62)
> web3-errors:     at C:\Users\Im cyborg\web3.js\packages\web3-errors\node_modules\typescript\lib\tsc.js:43887:39
> web3-errors:     at Array.map (<anonymous>)
> web3-errors:     at getSymbolChain (C:\Users\Im cyborg\web3.js\packages\web3-errors\node_modules\typescript\lib\tsc.js:43885:58)
> web3-errors: error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> web3-errors: error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```

I know the time has already been invested in refactoring our use of symlinks, but it seems like solving this TS issue, keeping the symlinks and current repo config, and having Windows users use WSL would be a better approach. It's nice to have a single source of truth for these config files, and having each package have their own version of the files seem like an easy way for an update to get missed for a particular package

**Comment by luu-alex** [comment]
@spacesailor24 i think thats fine, i'll close the pr + issue

**Comment by hammersharkfish** [comment]
I am facing this issue on windows . 
In `web3-providers-http` 
`yarn build` 
```
yarn run v1.22.19
$ yarn clean
$ rimraf dist && rimraf lib
$ yarn build:cjs & yarn build:esm & yarn build:types
$ tsc --build tsconfig.cjs.json && echo '{"type": "commonjs"}' > ./lib/commonjs/package.json
tsconfig.cjs.json:1:1 - error TS1005: '{' expected.

1 ../../config/tsconfig.cjs.json
  ~

tsconfig.cjs.json:1:2 - error TS1003: Identifier expected.

1 ../../config/tsconfig.cjs.json
   ~

tsconfig.cjs.json:1:3 - error TS1003: Identifier expected.

1 ../../config/tsconfig.cjs.json
    ~

tsconfig.cjs.json:1:4 - error TS1109: Expression expected.

1 ../../config/tsconfig.cjs.json
     ~

tsconfig.cjs.json:1:5 - error TS1003: Identifier expected.

1 ../../config/tsconfig.cjs.json
      ~

tsconfig.cjs.json:1:6 - error TS1003: Identifier expected.

1 ../../config/tsconfig.cjs.json
       ~

tsconfig.cjs.json:1:31 - error TS1005: '}' expected.

1 ../../config/tsconfig.cjs.json


tsconfig.cjs.json:1:1 - error TS1327: String literal with double quotes expected.

1 ../../config/tsconfig.cjs.json


tsconfig.cjs.json:1:1 - error TS1328: Property value can only be string literal, numeric literal, 'true', 'false', 'null', object literal or array literal.

1 ../../config/tsconfig.cjs.json
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

test/fixtures/system_test_utils.ts:1:1 - error TS1128: Declaration or statement expected.

1 ../../../../scripts/system_tests_utils.ts
  ~

test/fixtures/system_test_utils.ts:1:2 - error TS1128: Declaration or statement expected.

1 ../../../../scripts/system_tests_utils.ts
   ~

test/fixtures/system_test_utils.ts:1:8 - error TS1003: Identifier expected.

1 ../../../../scripts/system_tests_utils.ts
         ~

test/fixtures/system_test_utils.ts:1:9 - error TS1003: Identifier expected.

1 ../../../../scripts/system_tests_utils.ts
          ~

test/fixtures/system_test_utils.ts:1:10 - error TS1109: Expression expected.

1 ../../../../scripts/system_tests_utils.ts
           ~

test/fixtures/system_test_utils.ts:1:11 - error TS1003: Identifier expected.

1 ../../../../scripts/system_tests_utils.ts
            ~

test/fixtures/system_test_utils.ts:1:12 - error TS1003: Identifier expected.

1 ../../../../scripts/system_tests_utils.ts
             ~


Found 16 errors.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
$ tsc --build tsconfig.esm.json && echo '{"type": "module"}' > ./lib/esm/package.json
tsconfig.esm.json:1:1 - error TS1005: '{' expected.

1 ../../config/tsconfig.esm.json
  ~

tsconfig.esm.json:1:2 - error TS1003: Identifier expected.

1 ../../config/tsconfig.esm.json
   ~

tsconfig.esm.json:1:3 - error TS1003: Identifier expected.

1 ../../config/tsconfig.esm.json
    ~

tsconfig.esm.json:1:4 - error TS1109: Expression expected.

1 ../../config/tsconfig.esm.json
     ~

tsconfig.esm.json:1:5 - error TS1003: Identifier expected.

1 ../../config/tsconfig.esm.json
      ~

tsconfig.esm.json:1:6 - error TS1003: Identifier expected.

1 ../../config/tsconfig.esm.json
       ~

tsconfig.esm.json:1:31 - error TS1005: '}' expected.

1 ../../config/tsconfig.esm.json


tsconfig.esm.json:1:1 - error TS1327: String literal with double quotes expected.

1 ../../config/tsconfig.esm.json


tsconfig.esm.json:1:1 - error TS1328: Property value can only be string literal, numeric literal, 'true', 'false', 'null', object literal or array literal.

1 ../../config/tsconfig.esm.json
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

test/fixtures/system_test_utils.ts:1:1 - error TS1128: Declaration or statement expected.

1 ../../../../scripts/system_tests_utils.ts
  ~

test/fixtures/system_test_utils.ts:1:2 - error TS1128: Declaration or statement expected.

1 ../../../../scripts/system_tests_utils.ts
   ~

test/fixtures/system_test_utils.ts:1:8 - error TS1003: Identifier expected.

1 ../../../../scripts/system_tests_utils.ts
         ~

test/fixtures/system_test_utils.ts:1:9 - error TS1003: Identifier expected.

1 ../../../../scripts/system_tests_utils.ts
          ~

test/fixtures/system_test_utils.ts:1:10 - error TS1109: Expression expected.

1 ../../../../scripts/system_tests_utils.ts
           ~

test/fixtures/system_test_utils.ts:1:11 - error TS1003: Identifier expected.

1 ../../../../scripts/system_tests_utils.ts
            ~

test/fixtures/system_test_utils.ts:1:12 - error TS1003: Identifier expected.

1 ../../../../scripts/system_tests_utils.ts
             ~


Found 16 errors.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
$ tsc --build tsconfig.types.json
tsconfig.types.json:1:1 - error TS1005: '{' expected.

1 ../../config/tsconfig.types.json
  ~

tsconfig.types.json:1:2 - error TS1003: Identifier expected.

1 ../../config/tsconfig.types.json
   ~

tsconfig.types.json:1:3 - error TS1003: Identifier expected.

1 ../../config/tsconfig.types.json
    ~

tsconfig.types.json:1:4 - error TS1109: Expression expected.

1 ../../config/tsconfig.types.json
     ~

tsconfig.types.json:1:5 - error TS1003: Identifier expected.

1 ../../config/tsconfig.types.json
      ~

tsconfig.types.json:1:6 - error TS1003: Identifier expected.

1 ../../config/tsconfig.types.json
       ~

tsconfig.types.json:1:33 - error TS1005: '}' expected.

1 ../../config/tsconfig.types.json


tsconfig.types.json:1:1 - error TS1327: String literal with double quotes expected.

1 ../../config/tsconfig.types.json


tsconfig.types.json:1:1 - error TS1328: Property value can only be string literal, numeric literal, 'true', 'false', 'null', object literal or array literal.

1 ../../config/tsconfig.types.json
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

test/fixtures/system_test_utils.ts:1:1 - error TS1128: Declaration or statement expected.

1 ../../../../scripts/system_tests_utils.ts
  ~

test/fixtures/system_test_utils.ts:1:2 - error TS1128: Declaration or statement expected.

1 ../../../../scripts/system_tests_utils.ts
   ~

test/fixtures/system_test_utils.ts:1:8 - error TS1003: Identifier expected.

1 ../../../../scripts/system_tests_utils.ts
         ~

test/fixtures/system_test_utils.ts:1:9 - error TS1003: Identifier expected.

1 ../../../../scripts/system_tests_utils.ts
          ~

test/fixtures/system_test_utils.ts:1:10 - error TS1109: Expression expected.

1 ../../../../scripts/system_tests_utils.ts
           ~

test/fixtures/system_test_utils.ts:1:11 - error TS1003: Identifier expected.

1 ../../../../scripts/system_tests_utils.ts
            ~

test/fixtures/system_test_utils.ts:1:12 - error TS1003: Identifier expected.

1 ../../../../scripts/system_tests_utils.ts
             ~


Found 16 errors.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Pull request closed without merging**
