### PR TITLE
Autotype for contract methods

### LINKED ISSUE #6128: Typescript compilation error when calling a contract method with a parameter: `Expected 0 arguments, but got 1`
I am trying to call this contract method the following way:

```
const contractInstance = new web3.eth.Contract([
    {
        inputs: [
            {
                internalType: "uint256",
                name: "tokenId",
                type: "uint256",
            },
        ],
        name: "tokenURI",
        outputs: [{ internalType: "string", name: "", type: "string" }],
        stateMutability: "view",
        type: "function",
    },
], contractAddress);
const result = await contractInstance.methods.tokenURI(tokenID).call();
```
I cannot compile this as it will throw this typescript error: `Expected 0 arguments, but got 1` for the `tokenURI` method.

This happens in version the latest version `4.0.1-rc.1` but I can compile and run the same code successfully in version 1.x.

OS: Mac M1
Node Version: 19.6.0
NPM Version: 9.4.0

### PR DESCRIPTION
**Pull request by avkos**
## Description

fixes #6128

after this fix code builds without passing `typeof ABI`:

```ts
const contractInstance = new web3.eth.Contract([
        {
            inputs: [
                {
                    internalType: 'uint256',
                    name: 'tokenId',
                    type: 'uint256',
                },
            ],
            name: 'tokenURI',
            outputs: [{ internalType: 'string', name: '', type: 'string' }],
            stateMutability: 'view',
            type: 'function',
        },
    ] as const);

contractInstance.methods.tokenURI(123);
```

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run lint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:coverage` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [ ] I have linked Issue(s) with this PR in "Linked Issues" menu.

### CODE REVIEW

**Comment by Spacesai1or** [comment]
Great idea, please update `CHANGELOG.md`

**Review by jdevcs — APPROVED** [review]

**Review by luu-alex — APPROVED** [review]

**Review by Spacesai1or — APPROVED** [review]
Can you also update the root `CHANGELOG.md`?

**Review by Sammiegirl411 — COMMENTED** [review]
Ok

**Review by Sammiegirl411 — COMMENTED** [review]
Ok

**Pull request merged**
