### PR TITLE
Fix: rm console.warn if scrypt not present

### PR DESCRIPTION
**Pull request by CruzMolina**
🙏

### CODE REVIEW

**Review by gnidan — APPROVED** [review]
Yes, please!

**Comment by michaelsbradleyjr** [comment]
Already done in #3035, #3036. That warning is now only printed when [installing web3](https://github.com/web3-js/scrypt-shim/blob/master/scripts/postinstall.js).

I'm about to make a PR for the [web3-js/scrypt-shim](https://github.com/web3-js/scrypt-shim) repo that will remove the runtime warning in the event of maxmem exceptions, since the [true reason](https://github.com/ethereum/go-ethereum/issues/19977) those may arise is now understood. I will also make a PR for this repo to remove the static tests (copied from go-ethereum's repo) that contain invalid kdf parameters.

**Comment by michaelsbradleyjr** [comment]
Quick update on improvements to `scrypt-shim`: https://github.com/web3-js/scrypt-shim/compare/master...michaelsbradleyjr:refactor-per-rfc?expand=1.

I've done my best to be super-attentive to edge cases and whatnot. Last thing is to get the test suite into proper shape. PRs #3035, #3036 will be updated once that work is complete and the PR has been submitted for `scrypt-shim`.

**Comment by nivida** [comment]
I'm closing this PR because of the mentioned PRs for 1.x and 2.x from @michaelsbradleyjr

**Pull request closed without merging**
