### PR TITLE
fixed bugs when calling contract string method

### PR DESCRIPTION
**Pull request by emn178**
case 1: if str is string type and contract has no this property

origin
```JavaScript
contract.methods.str().call((err, result) => {
  console.log(err); // null
  console.log(result); // "ERROR: Strings are not yet supported as return values"
});
```
after patch
```JavaScript
contract.methods.str().call((err, result) => {
  console.log(err); // an Error object
                    // Error: ERROR: Strings are not yet supported as return values....
  console.log(result); // undefined
});
```
case 2: if str is string type and value is empty
```JavaScript
contract.methods.str().call((err, result) => {
  console.log(err); // null
  console.log(result); // "0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000"
});
// and something error message in console 
Unhandled rejection Error: The parameter "0x" must be a valid HEX string....
```
after patch
```JavaScript
contract.methods.str().call((err, result) => {
  console.log(err); // null
  console.log(result); // ""
});
```

### CODE REVIEW

**Comment by frozeman** [comment]
When the type is wrong it should rather return an error. @chriseth what do you think about the above?

**Comment by chriseth** [comment]
@frozeman you have to give me more context.

**Comment by frozeman** [comment]
Could you please put the ABI in your example above, and add test cases to the `tests/contract.js` ?

**Comment by frozeman** [comment]
I fixed this myself with added tests. Thank you so much for the find, well done!

**Pull request closed without merging**
