### PR TITLE
Use different types for jsonInterface setter and getter

### LINKED ISSUE #5474: Change contract.options.jsonInterface - ts issue
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Changing contract abi via:
`contract.options.jsonInterface = another_abi_json;`

doesn't allow in **ts** with following error:
```
error TS2322: Type '({ anonymous: boolean; inputs: { indexed: boolean; internalType: string; name: string; type: string; }[]; name: string; type: string; outputs?: undefined; stateMutability?: undefined; } | { inputs: never[]; ... 4 more ...; anonymous?: undefined; } | { ...; })[]' is not assignable to type 'ContractAbiWithSignature'.

      Type '{ anonymous: boolean; inputs: { indexed: boolean; internalType: string; name: string; type: string; }[]; name: string; type: string; outputs?: undefined; stateMutability?: undefined; } | { inputs: never[]; ... 4 more ...; anonymous?: undefined; } | { ...; }' is not assignable to type 'AbiFragment & { signature: string; }'.
        Type '{ anonymous: boolean; inputs: { indexed: boolean; internalType: string; name: string; type: string; }[]; name: string; type: string; outputs?: undefined; stateMutability?: undefined; }' is not assignable to type 'AbiFragment & { signature: string; }'.
          Type '{ anonymous: boolean; inputs: { indexed: boolean; internalType: string; name: string; type: string; }[]; name: string; type: string; outputs?: undefined; stateMutability?: undefined; }' is not assignable to type 'AbiBaseFragment & { readonly name: never; readonly type: string; readonly stateMutability: string; readonly inputs: never; readonly outputs: never; readonly constant?: boolean | undefined; readonly payable?: boolean | undefined; } & { ...; }'.
            Type '{ anonymous: boolean; inputs: { indexed: boolean; internalType: string; name: string; type: string; }[]; name: string; type: string; outputs?: undefined; stateMutability?: undefined; }' is not assignable to type '{ readonly name: never; readonly type: string; readonly stateMutability: string; readonly inputs: never; readonly outputs: never; readonly constant?: boolean | undefined; readonly payable?: boolean | undefined; }'.
```

### Expected Behavior

On contract instance `contract.options.jsonInterface = another_abi_json;` should reset and should **regenerate** the methods and events of the contract instance without ts error.

### Steps to Reproduce

```
			const contract = new Contract(
				sampleStorageContractABI,
				addr,
			);

			contract.options.jsonInterface = sampleStorageContractABI__2;
```

### Web3.js Version

4.0.1-alpha.0

### Environment

- Operating System: 
- Browser: 
- Node.js Version: 
- NPM Version: 

### Anything Else?

_No response_

### PR DESCRIPTION
**Pull request by Muhammad-Altabba**
## Description

Fixes #5474

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist for 1.x:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` with success.
- [ ] I have tested the built `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

## Checklist for 4.x:

- [ ] I have selected the correct 4.x base branch.
- [ ] Within the description, the feature or issue is discussed in detail or an issue is linked.   
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added any required tests for the changes I made 
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `yarn` successfully
- [ ] I ran `yarn lint` successfully
- [ ] I ran `yarn build:web` successfully
- [ ] I ran `yarn test:unit` successfully
- [ ] I ran `yarn test:integration` successfully
- [ ] I ran `compile:contracts` successfully
- [ ] I have tested my code.
- [ ] I have updated the corresponding `CHANGELOG.md` file in the packages I have edited.

### CODE REVIEW

**Review by nikoulai — APPROVED** [review]

**Comment by avkos** [comment]
I see a problem here. If we change abi we need to regenerate methods to make correct types, especially for overloaded functions.

**Comment by Muhammad-Altabba** [comment]
> I see a problem here. If we change abi we need to regenerate methods to make correct types, especially for overloaded functions.

Actually, the exact same logic that is used the first time the ABI is provided, is used when assigning a new ABI to `jsonInterface`. So, there should be no issues. And I also have a test written to ensure that. However, if you still think there is a problem, could you please provide a coding sample? You may just modify the newly added test case to show the edge case you are pointing to.

Thanks in advance,

**Comment by avkos** [comment]
in constructor we call function `this._parseAndSetJsonInterface(jsonInterface, returnDataFormat);`
this function creates methods with types based on `jsonInterface`

For example abi has this function:
```
{
		inputs: [
			{ internalType: 'uint256', name: '_value', type: 'uint256' },
			{ internalType: 'string', name: '_stringValue', type: 'string' },
			{ internalType: 'bool', name: '_boolValue', type: 'bool' },
		],
		name: 'setValues',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	}
```

then you set new `jsonInterface` and function changes to:

```
{
		inputs: [
			{ internalType: 'uint256', name: '_value', type: 'uint256' }
		],
		name: 'setValues',
		outputs: [
                         { internalType: 'bool', name: '_boolValue', type: 'bool' }
                ],
		stateMutability: 'nonpayable',
		type: 'function',
	}
```

but methods in the contract will not change. that is why I think we need to run `this._parseAndSetJsonInterface(jsonInterface, returnDataFormat);` if we set new abi to contract

**Comment by avkos** [comment]
Also we can add types chek test after we change abi in a contract. Like in this [PR](https://github.com/web3/web3.js/pull/5613/files)

**Review by avkos — APPROVED** [review]

**Pull request merged**
