### PR TITLE
Show "Transaction ran out of gas" error when 'receipt.gasUsed >= gasProvided'

### PR DESCRIPTION
**Pull request by nujabes403**
## Description

Show "Transaction ran out of gas" error when gasUsed property in receipt is greater than gasProvided in transaction object.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [x] I ran ```npm run test``` with success and extended the tests if necessary.
- [x] I ran ```npm run build``` and tested the resulting file from ```dist``` folder in a browser.
- [ ] I have tested my code on the live network.

### CODE REVIEW

**Comment by nujabes403** [comment]
```
receiptJSON = JSON.stringify(receipt, null, 2);
if (receipt.status === false || receipt.status === '0x0') {
    utils._fireError(new Error("Transaction has been reverted by the EVM:\n" + receiptJSON),
        defer.eventEmitter, defer.reject);
} else {
    utils._fireError(
        new Error("Transaction ran out of gas. Please provide more gas:\n" + receiptJSON),
        defer.eventEmitter, defer.reject);
}
```
This is whole code which has a problem.

When the 'status' property of receipt is 'false' or '0x0', it just shows "Transaction has been reverted by the EVM".

In this sentence, user couldn't find the reason why transaction has been reverted.

It would be good for user to show "Transaction ran out of gas. Provide more gas" when 'gasUsed' of receipt is lesser than 'gasProvided' of transaction object.

**Comment by nujabes403** [comment]
```
receiptJSON = JSON.stringify(receipt, null, 2);
if (receipt.gasUsed >= gasProvided) {
  utils._fireError(
      new Error("Transaction ran out of gas. Please provide more gas:\n" + receiptJSON),
      defer.eventEmitter, defer.reject);
} else if (receipt.status === false || receipt.status === '0x0') {
    utils._fireError(new Error("Transaction has been reverted by the EVM:\n" + receiptJSON),
        defer.eventEmitter, defer.reject);
} else {
    // TODO:
    // When it is not 'Transaction ran out of gas' error or 'Reverted' error,
    // What error message should we show?
    utils._fireError(
        new Error("Transaction ran out of gas. Please provide more gas:\n" + receiptJSON),
        defer.eventEmitter, defer.reject);
}
```

This is whole code I fixed.
After fixing I found that we need a new error message when it is not a situation like below:
1) Transaction ran out of gas
2) receipt status is '0x0' or false

TODO:
What error message should we show?

**Comment by nujabes403** [comment]
Please check my request @frozeman @nivida :)

**Comment by nivida** [comment]
I've closed this because there are some issues for improving the errors. I would like to introduce clear error codes for Web3.js and for example a logger like Winston.

**Pull request closed without merging**
