### PR TITLE
add: custom transaction polling interval

### LINKED ISSUE #2621: Transaction confirmation poll rate as a constructor option
### Description
In the `TransactionObserver` class, the polling rate is set to poll every 1000 ms. While this is fine for the mainnet and testnets, people using private networks or ganache have experienced a significant performance dip.
I personally have fixed this locally by changing the observer to poll every 100ms.
Perhaps this could be added as a configurable option (with a default of 1000), similar to the options added under this new transaction confirmation workflow.
Plus it's nice to remove hardcoded values in the codebase.

#### Expected behavior
Transaction confirmations are processed multiple times per second.

#### Actual behavior
Confirmations take up to 1000ms each, a hardcoded value.

#### Steps to reproduce the behavior
Configure web3 with any private network that has a high transaction throughput and try to run many transactions in a row.

### Versions 
* web3.js: 1.0.0-beta.51

### PR DESCRIPTION
**Pull request by sirpy**
## Description

allow to set via options the interval which polls for TX status
#2621 

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [x] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [x] I have updated the `CHANGELOG.md` file in the root folder.

### CODE REVIEW

**Review by nazarhussain — CHANGES_REQUESTED** [review]
Hi @sirpy Thanks for contribution. Please add relevant docs under `docs/` folder to reflect the changes. 

Also update the `CHANGELOG.md` to specify what new config been added.

**Comment by nazarhussain** [comment]
@sirpy Did you get a chance to look into feedback I posted earlier. I will encourage you to complete it so we can include this PR in upcoming sprint.

**Comment by sirpy** [comment]
@nazarhussain Hey, actually looking at it again, I dont think what I did works.
Not only that, i'm not able to understand and track how all those defaults are passed down to the contract and then to the method sending. Can some enlighten me?

**Comment by sirpy** [comment]
@nazarhussain updated

**Review by nazarhussain — APPROVED** [review]

**Comment by jdevcs** [comment]
`Build / e2e_windows` is failing on this

**Review by jdevcs — CHANGES_REQUESTED** [review]
`Build / e2e_windows (pull_request) ` is failing on this PR, needs to be fixed

also could you add test for passing custom `transactionPollingInterval`

**Comment by sirpy** [comment]
@jdevcs I dont see how this PR is related to this error. In anycase I wouldnt have any idea how to fix it.

**Comment by Spacesai1or** [comment]
@sirpy FYI I merged this PR into a branch I just created and opened PR #4672, the Windows test is no longer failing. I don't have an answer as to why this works, but we used this to solve the same issue previously

**Comment by sirpy** [comment]
@spacesailor24 thanks

**Pull request merged**
