### PR TITLE
Typing Contract.methods

### PR DESCRIPTION
**Pull request by dvargas92495**
## Description

Change adds a type to `Contract.methods`. I found myself making this cast manually and couldn't find any issue/context as to why it was previously kept as `any`.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
  - Was running into a failure trying to install dependencies `Error: Could not find any Visual Studio installation to use`
- [ ] I ran `npm run test:unit` with success.
  - blocked by above
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
  - blocked by above
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
  - blocked by above
- [ ] I have tested my code on the live network.
  - blocked by above
- [ ] I have checked the Deploy Preview and it looks correct.
  - blocked by above
- [x] I have updated the `CHANGELOG.md` file in the root folder.

### CODE REVIEW

**Comment by dvargas92495** [comment]
@luu-alex hey, are there any steps I should take in order to get this reviewed?

**Comment by luu-alex** [comment]
Hey @dvargas92495  sorry we didn't get back to you yet, we'll try getting back to you when we have enough bandwidth for enhancements.

**Review by luu-alex — APPROVED** [review]

**Comment by jdevcs** [comment]
@dvargas92495  Thanks for your contribution. Currently our team is working on [web3.js 4.x](https://github.com/ChainSafe/web3.js/tree/4.x) for full types support, so if you have time you may review and suggest improvements in 4.x .

**Comment by dvargas92495** [comment]
Is web3.js version 4.x the recommended branch to use? when I installed latest from npm, it downloaded a 1.x

From my brief skim, it appears that version 4.x has the appropriate typing for this use case

**Comment by Spacesai1or** [comment]
> Is web3.js version 4.x the recommended branch to use? when I installed latest from npm, it downloaded a 1.x
> 
> From my brief skim, it appears that version 4.x has the appropriate typing for this use case

@dvargas92495 

`4.x` is still in development, so `1.x` is the correct branch/version to use

We have refrained from making changes to `1.x`'s types because it would be considered a breaking change to anyone who uses TypeScript

We appreciate your PR and will be solving this issue in `4.x`

**Comment by dvargas92495** [comment]
got it makes sense, feel free to discard this PR then!

**Pull request closed without merging**
