### PR TITLE
Libs and CI updates

### LINKED ISSUE #5020: libs and CI update
Libs and CI node.js version update before next release:

npm audit fix
CI node.js version updated for build and tests.

### PR DESCRIPTION
**Pull request by jdevcs**
## Description
Libs and CI node.js version update before next release:

- npm audit fix
- CI node.js version updated for build and tests.

Fixes #5020 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` with success.
- [ ] I have tested the built `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

### CODE REVIEW

**Comment by jdevcs** [comment]
For following I will update 1x branch rule in repo settings: 
```
unit (11) Expected — Waiting for status to be reported
Required

unit (13) Expected — Waiting for status to be reported
Required
```
This will effect all other 1x PRs as well.

**Review by nazarhussain — CHANGES_REQUESTED** [review]
Is there any issue which document why are removing support for 11 and 13?

**Review by avkos — APPROVED** [review]

**Comment by jdevcs** [comment]
> Is there any issue which document why are removing support for 11 and 13?

https://github.com/ChainSafe/web3.js/issues/5020

**Comment by jdevcs** [comment]
> Is there any issue which document why are removing support for 11 and 13?

@nazarhussain 
Its already linked in zenhub as well. 

https://github.com/ChainSafe/web3.js/issues/5020 

https://nodejs.org/en/about/releases/

**Review by nazarhussain — APPROVED** [review]

**Comment by nazarhussain** [comment]
@jdevcs Try to mention the issue in the PR description, it's the part of the PR template as well.

**Pull request merged**
