### PR TITLE
Response handling of GetTransactionReceiptMethod fixed and test updated

### PR DESCRIPTION
**Pull request by nivida**
## Description

Fixes #https://github.com/ethereum/web3.js/issues/2246

## Type of change

- [x] Bug fix 

## Checklist:

- [X] I have selected the correct base branch.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no warnings.
- [X] I have updated or added types for all modules I've changed
- [X] Any dependent changes have been merged and published in downstream modules.
- [X] I ran ```npm run test``` in the root folder with success and extended the tests if necessary.
- [X] I ran ```npm run build``` in the root folder and tested it in the browser and with node.
- [X] I ran ```npm run dtslint``` in the root folder and tested that all my types are correct
- [ ] I have tested my code on the live network.

### CODE REVIEW

**Comment by nivida** [comment]
Merged because it's running locally with version 9 of node: 
screenshot 2019-01-27 at 17 46 39

**Comment by 0x-genesys** [comment]
When will this change be live? Im still facing an issue

**Comment by nivida** [comment]
@0x-genesys This will be released today.

**Comment by 0x-genesys** [comment]
Hey @nivida please release this, I'm still facing the issue .

`"web3": "1.0.0-beta.38",`

**Pull request merged**
