### PR TITLE
Release/1.9.0

### PR DESCRIPTION
**Pull request by jdevcs**
### Fixed

  - Fixed skipped ws-ganache tests (#5759)
  - Fixed "provider started to reconnect error" in web3-provider-ws (#5820)
  - Fixed Error: Number can only safely store up to 53 bits (#5845)
  - Fixed types for packages which have default exports but not declared default export in .d.ts (#5866)
  - Fixed Transaction type by adding missing properties (#5856)

### Changed

  - Add optional `hexFormat` param to `getTransaction` and `getBlock` that accepts the value `'hex'` (#5845)
  - `utils.toNumber` and `utils.hexToNumber` can now return the large unsafe numbers as `BigInt`, if `true` was passed to a new optional parameter called `bigIntOnOverflow` (#5845)
  - Updated @types/bn.js dependency to 5.1.1 in web3, web3-core and web3-eth-contract as reason mentioned in #5640 (#5885)
  - Add description to error for failed connection on websocket (#5884)

  
### Security
  - Updated dependencies (#5885)

### CODE REVIEW

**Review by avkos — APPROVED** [review]

**Review by nikoulai — APPROVED** [review]

**Review by Muhammad-Altabba — APPROVED** [review]

**Comment by jdevcs** [comment]
As part of the RC process, following test installations are performed in other projects and running their tests to see if everything.  
+ installs properly
+ builds
+ tests pass

(This list will be actively edited) 

| Project | Desc | Status | 
| ------ | ----- | ----- |
| [oz-test-helpers][1] | Test utils. Subset of their suite is web3 contracts |   |
| [synthetix][2] | ~1000 units |    |


[1]: https://github.com/OpenZeppelin/openzeppelin-test-helpers
[2]: https://github.com/Synthetixio/synthetix

**Comment by jdevcs** [comment]
**synthetix**
```

 4443 passing (1h)
  71 pending
  1 failing

  1) Contract: SupplySchedule
       functions and modifiers
         Given inflation amount of 800,000 - mintable supply
           should calculate the mintable supply as 0 within 1st week of inflation start date:
     Error: Time parameter
     
     
```
**OZ**
```
275 passing (16s)
  3 failing

  1) expectRevert
       expectRevert
         rejects a revert with incorrect expected reason:

      AssertionError: expected 'VM Exception while processing transac…' to equal 'Call to revert'
      + expected - actual

      -VM Exception while processing transaction: revert Call to revert
      +Call to revert
      
      at Context.<anonymous> (test/src/expectRevert.test.js:34:35)

  2) expectRevert
       assertion
         rejects an outOfGas:
     AssertionError: expect.fail()
      at assertFailure (test/helpers/assertFailure.js:9:10)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Context.<anonymous> (test/src/expectRevert.test.js:123:7)

  3) expectRevert
       outOfGas
         accepts an outOfGas:

      Wrong kind of exception received
      + expected - actual

      -Transaction: 0x2ac43c339baaec32fc43c4d3b955696f738613626c504c7715e69c7a616e4ead exited with an error (status 0) after consuming all gas.
      -     Please check that the transaction:
      -     - satisfies all conditions set by Solidity `assert` statements.
      -     - has enough gas to execute the full transaction.
      -     - does not trigger an invalid opcode by other means (ex: accessing an array out of bounds).
      +out of gas
      
      at expectException (src/expectRevert.js:20:30)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Context.<anonymous> (test/src/expectRevert.test.js:153:7)

     
```

These external repos test cases output is same like performed in last few releases.

**Comment by jdevcs** [comment]
merging 1.x into this release branch because https://github.com/web3/web3.js/pull/5932 merged in 1.x, for clean reference to release branch refer to 1 previous commit or v1.9.0 tag

**Comment by jdevcs** [comment]
we didn't do another RC due to https://github.com/web3/web3.js/pull/5932 because its minor change in github CI.

**Pull request merged**
