### PR TITLE
Added safer localStorage detection so that web3 does not break the JS…

### PR DESCRIPTION
**Pull request by asselstine**
… on the page when turned off.

Original PR was https://github.com/ethereum/web3.js/pull/1923

### CODE REVIEW

**Comment by joshstevens19** [comment]
Hey i think the PR https://github.com/ethereum/web3.js/pull/2203 fixes this already? If localStorage fails i think it puts out code 18 which is covered in all regards. This PR went in today so let me know if you think we need what you have defined if not we can close it.

Thanks again for your pull request 👍

**Comment by nivida** [comment]
@asselstine Thanks for submitting this PR. I'll test it and merge it after.

**Comment by asselstine** [comment]
@nivida I've fixed the build- looks like Unicorn was unhappy with a variable name and an unused import.

Thanks for taking some time for this one, having the project work without localStorage would really help us out.

**Comment by nivida** [comment]
This will get fixed with PR https://github.com/ethereum/web3.js/pull/2367 because it just gets items from the ``localStorage`` when you explicit call the ``accounts.wallet.load`` or ``accounts.wallet.save`` method.

**Pull request closed without merging**
