### PR TITLE
Add bignumber.js to web3-core (for its types)

### LINKED ISSUE #3386: Typescript compilation error regarding a bignumber.js import
#### Expected behavior

Build web3 with typescript without errors

#### Actual behavior

```
node_modules/web3-core/types/index.d.ts(31,23): error TS2307: Cannot find module 'bignumber.js'.
node_modules/web3-eth/types/index.d.ts(51,25): error TS2307: Cannot find module 'bignumber.js'.
```

see this Github Action to reproduce, logs, and configuration 
https://github.com/dapplion/web3-tsc-test/runs/461815145

### PR DESCRIPTION
**Pull request by cgewecke**
## Description

In #3213 @types/bignumber.js was removed - that package is [now a stub][4] and the main module implements its types internally. 

However, bignumber.js is not a direct dependency here - it's only used for its types - and TS users currently see the error reported in #3386 about an unresolved import. 

`tsc` tests did not catch this because bignumber.js exists in the development dependency tree.

`bignumber.js` is imported in 
+ [web3-core][1]
+ [web3-eth][2] (which has web3-core [as a dep][3])

This PR should not affect the bundle size.

[1]: https://github.com/ethereum/web3.js/blob/1.x/packages/web3-core/types/index.d.ts#L31
[2]: https://github.com/ethereum/web3.js/blob/1.x/packages/web3-eth/types/index.d.ts#L51
[3]: https://github.com/ethereum/web3.js/blob/1.x/packages/web3-eth/package.json#L17
[4]: https://www.npmjs.com/package/@types/bignumber.js

Fixes #3386

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [x] I ran ```npm run dtslint``` with success and extended the tests and types if necessary.
- [x] I ran ```npm run test:unit``` with success.
- [ ] I have executed ``npm run test:cov`` and my test cases do cover all lines and branches of the added code.
- [ ] I ran ```npm run build-all``` and tested the resulting file/'s from  ```dist``` folder in a browser.
- [x] I have updated the ``CHANGELOG.md`` file in the root folder.
- [ ] I have tested my code on the live network.

### CODE REVIEW

**Review by holgerd77 — APPROVED** [review]
LGTM, fix has also be confirmed [here](https://github.com/ethereum/web3.js/issues/3386#issuecomment-590619980).

**Comment by holgerd77** [comment]
Hmm, Travis is failing after I updated the branch.

**Comment by holgerd77** [comment]
Update: CI already [failed](https://travis-ci.org/ethereum/web3.js/builds/654854315?utm_medium=notification&utm_source=email) after merging https://github.com/ethereum/web3.js/pull/3376

**Comment by cgewecke** [comment]
@holgerd77 I think Travis or mocha just ran one of the jobs too slowly - this happens fairly often :) It's possible to restart the job from the Travis UI using a button next to the failing item - usually passes second time. 

The "allowed failure" windows job (always times out) looks ok for this PR - it's running as expected and [exiting 0 here][1].

[1]: https://travis-ci.org/ethereum/web3.js/jobs/654854677#L1239

**Review by nivida — APPROVED** [review]

**Pull request merged**
