### PR TITLE
fix bug when 2+ events are returned in logs subscription

### PR DESCRIPTION
**Pull request by perissology**
If 2 or more of the same event type are logged in a single transaction,
the eth_subscription result will contain multiple logs.

### CODE REVIEW

**Comment by perissology** [comment]
I'm wondering if it might be better for output to always be an array. Otherwise, clients will need to issue an array check in the subscription handler if there is a possibility for multiple events.

I can update the PR if you agree.

**Comment by frozeman** [comment]
The subscription notification return should only return objects, i discussed that a long time ago with @bas-vk and assumed it is fixed.
If there are multiple logs, it should fire multiple notifications, one per log.

**Comment by frozeman** [comment]
Supposedly geth will only return one log at a time, did you experience multiple logs, and if so with which version of geth? @perissology

**Comment by bas-vk** [comment]
This was fixed a more than a year ago.
If you still have this issue with a recent version of geth it would help if you could provide an example.

**Comment by perissology** [comment]
ah sorry, I was actually using parity v1.7.0-beta-5f2cabd-20170727.

not sure about geth

**Comment by perissology** [comment]
so is this a parity bug then?

**Comment by perissology** [comment]
@frozeman ^

**Comment by frozeman** [comment]
They will fix that.

**Pull request closed without merging**
