### PR TITLE
update ethereumjs libraries

### LINKED ISSUE #5943: Update @ethereumjs/tx Lib to 4.x
Review breaking changes and  @ethereumjs/tx Lib upgrade to 4.x as mentioned [here](https://github.com/web3/web3.js/pull/5904/files#r1143992147)

### PR DESCRIPTION
**Pull request by mpetrunic**
## Description

ethereumjs/common received big update which reduces bundle size significantly, unfortunately:
- ethereumjs/tx now depends on ethers - https://github.com/ethereumjs/ethereumjs-monorepo/pull/2513 should mitigate this slightly once released
- ethereumjs/util depends on async which breaks our webpack build - proposed PR https://github.com/ethereumjs/ethereumjs-monorepo/pull/2514 to remove async library altogether (if that doesn't work, will try to propose to just use `import ... from "async/eachSeries"`)

closes #5943

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist for 1.x:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` with success.
- [ ] I have tested the built `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

## Checklist for 4.x:

- [ ] I have selected the correct 4.x base branch.
- [ ] Within the description, the feature or issue is discussed in detail or an issue is linked.   
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added any required tests for the changes I made 
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `yarn` successfully
- [ ] I ran `yarn lint` successfully
- [ ] I ran `yarn build:web` successfully
- [ ] I ran `yarn test:unit` successfully
- [ ] I ran `yarn test:integration` successfully
- [ ] I ran `compile:contracts` successfully
- [ ] I have tested my code.
- [ ] I have updated the corresponding `CHANGELOG.md` file in the packages I have edited.

### CODE REVIEW

**Comment by mpetrunic** [comment]
Heck, seems like with latest ethereumjs libs we get ssz and ethers providers libraries which are still large :(

**Comment by mpetrunic** [comment]
Heck, seems like with latest ethereumjs libs we get ssz and ethers providers libraries which are still large :(

> Heck, seems like with latest ethereumjs libs we get ssz and ethers providers libraries which are still large :(

cc @web3/web3-js

**Comment by jdevcs** [comment]
This PR can be closed , as eth/tx functions moved into 4.x

**Comment by holgerd77** [comment]
Hi there, Holger from EthereumJS, we have a fix in the works for the Ethers dependency (with the goal to remove): https://github.com/ethereumjs/ethereumjs-monorepo/pull/2633, feedback would be appreciated! 🙂 

SSZ we still need to discuss.

**Comment by holgerd77** [comment]
(respectively, to manage expectations: it is more unlikely that we will remove SSZ, since this is becoming such an integral part of the protocol in the near distant future. Might be a way here to continue to work together to make the SSZ library more compatible (if needed), lessen dependencies, size,...)

**Comment by holgerd77** [comment]
(might generally be worth to have monthly ChainSafe(so mainly: Lodestar, Web3.js)/EthereumJS calls to discuss things like that)

**Comment by jdevcs** [comment]
@holgerd77 For optimising 4.x web3.js build size we have removed some ethereumjs dependencies by using its functionality https://github.com/web3/web3.js/pull/5963

**Comment by jdevcs** [comment]
> (might generally be worth to have monthly ChainSafe(so mainly: Lodestar, Web3.js)/EthereumJS calls to discuss things like that)

cc: @mconnelly8

**Comment by holgerd77** [comment]
> @holgerd77 For optimising 4.x web3.js build size we have removed some ethereumjs dependencies by using its functionality #5963

To be honest: I think that is totally a dead end, especially our Common library is evolving so quickly that you will likely (and unnecessarily) waste a lot of ressources to catch up.

Guess it would be beneficial to find some way together here. If you have some additional demands, just open an issue on our side https://github.com/ethereumjs/ethereumjs-monorepo or mention people from our team. 🙂

**Comment by mpetrunic** [comment]
> > @holgerd77 For optimising 4.x web3.js build size we have removed some ethereumjs dependencies by using its functionality #5963
> 
> To be honest: I think that is totally a dead end, especially our Common library is evolving so quickly that you will likely (and unnecessarily) waste a lot of ressources to catch up.
> 
> Guess it would be beneficial to find some way together here. If you have some additional demands, just open an issue on our side https://github.com/ethereumjs/ethereumjs-monorepo or mention people from our team. slightly_smiling_face

Hey @holgerd77,
this change reduced web3.js bundle size by ~30%. 
Some of the stuff that we would need before we could consider using it again:
- replace Buffer with Uint8Array or use Buffer polyfill explicitly (we would prefer the first one as we already modified the code to use Uint8Array https://github.com/web3/web3.js/pull/6033). Your code expects that users will provide Buffer implementation in the browser which is very confusing for them.
- change typescript config so "imports" are not transpiled into "require's"
- run some basic checks to ensure common and tx packages work in browser
- making transaction builder modular
   - so we can decide which transaction types you are supporting. Like, I don't think we will add eip4844 tx by default but rather as an optional plugin since those tx types add a lot of weight to the bundle but it's not gonna be used much by regular users
   - allowing us to add different transaction types ourselves or through plugins
   
Let me know if you think I should open those issues on ethereumjs repo or if you don't think this aligns with ethereumjs roadmap^^

**Comment by paulmillr** [comment]
@mpetrunic do you use tree-shaking? Does it work?

> replace Buffer with Uint8Array

This is planned for v7 and huge amount of work for this was done over the last couple months.

>making transaction builder modular

That seems like it should be solved with tree-shaking.

**Comment by mpetrunic** [comment]
> @mpetrunic do you use tree-shaking? Does it work?

Yes we use tree shaking when creating minified bundle.

 
> > making transaction builder modular
> 
> That seems like it should be solved with tree-shaking.

Treeshaking cannot remove dynamic code from [TransactionFactory](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/tx/src/transactionFactory.ts) so we end up with ssz and ckzg code from eip4844 transaction type. I feel like better approach would be to allow users to instantiate transaction factory with transaction types they want to support^^

TBH, we could've fixed that if we just wrote our TxFactory that uses individual tx implementations.

We can promise to try library again with v7 version :)

**Pull request closed without merging**
