### PR TITLE
Rationale Behind Contract ABI Supporting GAS

### PR DESCRIPTION
**Pull request by maektwain**
Supports cases like 
```
 {
    name: 'setup',
    outputs: [],
    inputs: [{ type: 'address', name: 'token_addr' }],
    constant: false,
    payable: false,
    type: 'function',
    gas: 175875
}
```

## Description

Please include a summary of the change and be sure you follow the contributions rules we do provide [here](./CONTRIBUTIONS.md)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [Y ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [Y ] I have selected the correct base branch.
- [Y ] I have performed a self-review of my own code.
- [ N] I have commented my code, particularly in hard-to-understand areas.
- [ N] I have made corresponding changes to the documentation.
- [ Y] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ N] I ran ```npm run dtslint``` with success and extended the tests and types if necessary.
- [ N] I ran ```npm run test:unit``` with success.
- [ N] I have executed ``npm run test:cov`` and my test cases do cover all lines and branches of the added code.
- [ ] I ran ```npm run build-all``` and tested the resulting file/'s from  ```dist``` folder in a browser.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [ ] I have tested my code on the live network.

### CODE REVIEW

**Comment by cgewecke** [comment]
@maektwain Out of curiosity, which compiler/tool generates this gas property in the ABI?

**Comment by alcuadrado** [comment]
I believe vyper does, as it can always compute a bound of the gas for each function.

**Comment by cgewecke** [comment]
@alcuadrado Thanks! Confirmed at [vyper 306][1]. 

@maektwain You've pointed this PR at Web3's 2.x branch which is not on a regular publishing schedule at the moment. Happy to approve this but it might be a while before it gets to npm.

Do you have any interest in retargeting it at 1.x?

[1]: https://github.com/vyperlang/vyper/issues/306

**Comment by maektwain** [comment]
@cgewecke Sure, I would like to look into it once more.

**Pull request closed without merging**
