### PR TITLE
Add Windows CI job (Node 12)

### PR DESCRIPTION
**Pull request by cgewecke**
## Description

Part of #3098. 

+ Adds a basic check in CI to make sure Web3 installs and runs on Windows 10 / Node 12. 
+ Moves other E2E tests up to Node 12
+ Increases the proxy registry timeouts (again) because that continues to be a problem
+ Adds an 'install' script to move some logic which decides whether to install web3's full dependency tree out of travis.yml (because getting too big)
 
The new Windows job has to go in as an "allowed failure" because even though it succeeds, the Travis' Windows container hangs open without completing.  

This is a [known problem there][1]  - their Windows is in beta. It has various fixes, none of which seemed to help in Web3's case. Tried to isolate the cause of the hang by closing all handles including virtual registry and eliminating the Node tests, etc but couldn't determine the source. There are also notes in the Travis issues suggesting that they should be clearing up resources on their end...idk.

In summary: this test can be used as a pre-publication check and it's a convenient way of evaluating reported Windows installation issues.

Related to #3371, #3051, #3033, #3002 etc...

[1]:  https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288

## Type of change

- [x] Test / OS

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran ```npm run dtslint``` with success and extended the tests and types if necessary.
- [x] I ran ```npm run test:unit``` with success and extended the tests if necessary.
- [ ] I ran ```npm run build-all``` and tested the resulting file/'s from  ```dist``` folder in a browser.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [ ] I have tested my code on the live network.

### CODE REVIEW

**Review by nivida — APPROVED** [review]

**Review by ryanio — APPROVED** [review]
Hey @cgewecke, @holgerd77 asked if I could do a review here so I’m happy to help.

Overall the PR looks great and I like how the external bash scripts organize the conditional logic well 👍 easy to understand and parse.

I very much like the verdaccio solution for e2e testing by swapping web3.js in other libs for the CI built version! Neat idea and seems really powerful for catching bugs.

> The new Windows job has to go in as an "allowed failure" because even though it succeeds, the Travis' Windows container hangs open without completing.

OK great, yeah it looks like it's running fine since it exited with status 0 at the end of the basic_usage test.

Over the past few months I’ve had a lot of success migrating some of the EthereumJS repos over to [Github Actions](https://github.com/ethereumjs/ethereumjs-vm/actions). I found it quite a bit faster than travis or circleci and required fewer hacky workarounds, at least for our simpler requirements. I’m unsure of how strong gh actions Windows support is, but perhaps it’s worth a look in the future. The current travis config looks a bit sophisticated though so I understand if it’s not a priority for now :)

**Comment by cgewecke** [comment]
@ryanio Thanks!

> I’ve had a lot of success migrating some of the EthereumJS repos over to Github Actions

👍 

Migrating might mostly be a matter of transferring the Travis matrix / ci.sh setup to a github.yml - could be pretty straightforward. 

Note to self:  "allowed failure" is ~ called [continue-on-error][1] in Github actions.

[1]: https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error

**Comment by holgerd77** [comment]
Branch is very much behind on this PR, wouldn't dare to use the "Update branch" functionality. @cgewecke can you rebase here (will likely need re-approvals then)?

**Comment by cgewecke** [comment]
@holgerd77 @ryanio Rebased, just pinging for a double-check.

**Review by ryanio — APPROVED** [review]

**Pull request merged**
