### PR TITLE
fix: edit example error on utils-bn

### PR DESCRIPTION
**Pull request by cokia**
## Description

corrected the error in the web3-utils document, in the example of BN.

```
Run:
new BN('0xea').toString();

Expected behavior
"234"

Actual behavior
"3450"

PS: web3.utils.toBN('0xea') returns "234" correctly
```

The issue was generated here. #3762

### CODE REVIEW

**Comment by cokia** [comment]
this is not stale PR.. :( 
please recheck it 👍

**Comment by GregTheGreek** [comment]
~@cokia since we migrated the repo to chainsafe, you'll actually need to fill out our CLA~ 

Actually it looks like cla was added by automatically by our org rules. We will be removing that for web3.js

**Comment by cokia** [comment]
In conclusion, do I not have to agree to the CLA up there?

**Comment by GregTheGreek** [comment]
No please ignore it, ever since the repo transfer things got a little weird

**Comment by GregTheGreek** [comment]
@cokia Is there a reason this was closed?

**Comment by cokia** [comment]
I mistook this for a merged Pull Request.

**Comment by vicnaum** [comment]
Actually, the correct value is 234.

It should had been corrected to:
`new BN('ea').toString();`

**Comment by Spacesai1or** [comment]
> Actually, the correct value is 234.
> 
> It should had been corrected to:
> `new BN('ea').toString();`

This returns `NaN` without the `0x` prefix

I'm going to close this because running:

```javascript
const BN = require('bignumber.js')

console.log(new BN('0xea').toString())
```

returns `234`

**Comment by vicnaum** [comment]
With bignumber.js - probably yes (I didn't check).
But I thought the default in web3 is BN.js?

With these two big number libraries - there's always some confusion...

**Pull request closed without merging**
