### PR TITLE
The version should be semver compatible

### PR DESCRIPTION
**Pull request by justinmchase**
The version should be semver compatible and instead when publishing to npm you should specify the beta tag.

e.g.
```
npm publish --tag beta
```

This will allow users to opt-into this package by installing either this version specifically or this tag and still get patch level updates as they are available:

```
npm install web3@beta
```
or
```
npm install web3@1.0.0
```

Users who simply do the basic `npm install web3` will get the version currently published as `latest`.

### CODE REVIEW

**Comment by justinmchase** [comment]
Addresses issue #1310

**Comment by frozeman** [comment]
web3.js 1.0.0 is not yet released, so this would release it.

**Comment by justinmchase** [comment]
No, I don't think so. Publishing it to NPM as latest would do that. When you publish it, specify the beta or next tag instead of latest. That way people can opt into beta and still get updates as patches are published without it ever being officially released. To release you just remove the beta tag and replace it with the latest tag.

https://docs.npmjs.com/getting-started/using-tags

**Comment by KaelWD** [comment]
@justinmchase You're right that they should be using tags, but there's nothing wrong with the version number.

**Comment by justinmchase** [comment]
@KaelWD Well I should say that I created this because I specifically encountered an issue with updating to newer versions with npm. New versions are published but you can't tell from npm commands like `npm outdated` because they were not being published with proper semver compatible versions.

Then after looking at it it became apparent that the reasoning behind the odd versioning scheme just seemed to not necessary if the tag feature was used instead. It would make working with this library a lot smoother.

**Comment by justinmchase** [comment]
Here is an example of a popular npm project (gulp) on which uses this technique:
https://www.npmjs.com/package/gulp#versions

Notice they have `latest` and `next` tags. If you just do an `npm install gulp` it installs `^3.9.1` but one could install `npm install gulp@next` and it would give you `^4.0.0` instead but you'd know you're opt'ing in to the beta track.

**Comment by KaelWD** [comment]
> you can't tell from npm commands like npm outdated because they were not being published with proper semver compatible versions

 - the versions are semver compatible: https://semver.org/#spec-item-9
 - `npm outdated` works for me, but shows the wrong version in "Wanted". I guess someone forgot a `.` when publishing. They can fix this just by unpublishing that version, although it's probably too late now thanks to the whole left-pad thing. 

image

**Comment by KaelWD** [comment]
Tags would be good though, I use a script that automatically sets the release tag from the version. Anything  with a pre-release version goes to `next`, everything else goes to `latest`.

**Comment by justinmchase** [comment]
Interesting, got it. I do think I was getting hit by that `beta2` issue. May be worth unpublishing it if you're already on 34. I was aware of the `-foo` being legit but I didn't realize you could tag on `.n` also and have it resolve correctly so I thought that was the issue.

**Pull request closed without merging**
