### PR TITLE
Fixed documentation for web3.eth.accounts.signTransaction

### LINKED ISSUE #5141: web3.eth.accounts.signTransaction VS EIP-1559
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to say about Web3.js' documentation?

When we read the document part for web3.eth.accounts.signTransaction,
There is only have gas and gas price, no max priority, no max fee.

May you update this part document for support EIP-1559?
Or it need to update the API library code?

Thanks.

### Examples/References

_No response_

### PR DESCRIPTION
**Pull request by Neurone**
## Description

Fixed documentation for maxPriorityFeePerGas and maxFeePerGas in web3.eth.accounts.signTransaction

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [x] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [x] I ran `npm run build` with success.
- [x] I have tested the built `dist/web3.min.js` in a browser.
- [x] I have tested my code on the live network.
- [x] I have checked the Deploy Preview and it looks correct.
- [x] I have updated the `CHANGELOG.md` file in the root folder.

### CODE REVIEW

**Review by nazarhussain — CHANGES_REQUESTED** [review]
Please add an entry to `CHANGELOG.md`

**Comment by Neurone** [comment]
> Please add an entry to `CHANGELOG.md`

Done.

**Review by nikoulai — APPROVED** [review]

**Review by nazarhussain — APPROVED** [review]

**Review by avkos — APPROVED** [review]
Thanks for the support. Just fix merge conflicts

**Comment by Neurone** [comment]
> Thanks for the support. Just fix merge conflicts

Done.

**Review by jdevcs — APPROVED** [review]

**Pull request merged**
