### PR TITLE
Replace ganache-cli (deprecated) with ganache

### PR DESCRIPTION
**Pull request by petrosDemetrakopoulos**
## Description

This PR replaces the ganache-cli dependency (which is currently deprecated) with ganache, which is the new name of the old ganache-cli package.

## Type of change

- Dependency upgrade

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [x] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [x] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [x] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [x] I have updated the `CHANGELOG.md` file in the root folder.

### CODE REVIEW

**Comment by petrosDemetrakopoulos** [comment]
@nazarhussain Could you please run the CI tests again ?

**Review by jdevcs — CHANGES_REQUESTED** [review]
@petrosDemetrakopoulos  Thanks for your contribution could you remove changes in following files:

- dist/web3.min.js 
- dist/web3.min.js.map
- **all** package-lock.json

**Comment by petrosDemetrakopoulos** [comment]
> @petrosDemetrakopoulos Thanks for your contribution could you remove changes in following files:
> 
>     * dist/web3.min.js
> 
>     * dist/web3.min.js.map
> 
>     * **all** package-lock.json

Done!

**Comment by jdevcs** [comment]
**Build / unit (14) (pull_request)** is failing, we will need to investigate this.

**Comment by petrosDemetrakopoulos** [comment]
> **Build / unit (14) (pull_request)** is failing, we will need to investigate this.

Do we have any way to see the logs ?

**Comment by petrosDemetrakopoulos** [comment]
@jdevcs Could you please trigger the test run again ?

**Comment by jdevcs** [comment]
Failing tests:

  ```
1) web.providers.givenProvider (ganache)
       requestManager attaches 4 listeners:

      AssertionError [ERR_ASSERTION]: 1 == 0
      + expected - actual

      -1
      +0
      
      at Context.<anonymous> (test/3_givenProvider-ganache.js:30:16)
      at processImmediate (internal/timers.js:464:21)

  2) web.providers.givenProvider (ganache)
       deploys a contract:
     RuntimeError: VM Exception while processing transaction: Transaction's maxFeePerGas (1) is less than the block's baseFeePerGas (875000000) (vm hf=london -> block -> tx)
      at Miner.result (node_modules/ganache/dist/node/webpack:/Ganache/chains/ethereum/ethereum/lib/src/miner/miner.js:318:31)
      at Miner.transactions (node_modules/ganache/dist/node/webpack:/Ganache/chains/ethereum/ethereum/lib/src/miner/miner.js:168:27)
      at Miner.result (node_modules/ganache/dist/node/webpack:/Ganache/chains/ethereum/ethereum/lib/src/miner/miner.js:83:39)
      at Miner.transactions [as mine] (node_modules/ganache/dist/node/webpack:/Ganache/chains/ethereum/ethereum/lib/src/miner/miner.js:454:19)
      at Blockchain.resolvedPromise [as mine] (node_modules/ganache/dist/node/webpack:/Ganache/chains/ethereum/ethereum/lib/src/blockchain.js:267:17)
      at async Promise.all (index 0)
      at TransactionPool.emit (node_modules/ganache/dist/node/webpack:/Ganache/core/node_modules/emittery/index.js:302:9)

  3) web.providers.givenProvider (ganache)
       "after all" hook for "can repeatedly setProvider without triggering MaxListeners":
     TypeError: provider.close is not a function
      at Context.<anonymous> (test/3_givenProvider-ganache.js:26:18)
      at processImmediate (internal/timers.js:464:21)

  4) subscription connect/reconnect
       "before each" hook for "subscribes (baseline)":
     TypeError: Cannot read private member from an object whose class did not declare it
      at __classPrivateFieldGet (node_modules/ganache/dist/node/webpack:/Ganache/core/lib/src/server.js:10:94)
      at listen (node_modules/ganache/dist/node/webpack:/Ganache/core/lib/src/server.js:150:24)
      at web3.js/node_modules/pify/index.js:32:6
      at new Promise (<anonymous>)
      at web3.js/node_modules/pify/index.js:6:9
      at ret (node_modules/pify/index.js:56:76)
      at Context.<anonymous> (test/eth.subscribe.ganache.js:16:34)
      at processImmediate (internal/timers.js:464:21)

  5) subscription connect/reconnect
       "after each" hook for "subscribes (baseline)":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (web3.js/test/eth.subscribe.ganache.js)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)

  6) WebsocketProvider (ganache)
       "error" handler fires if the client closes unilaterally:
     TypeError: Cannot read private member from an object whose class did not declare it
      at __classPrivateFieldGet (node_modules/ganache/dist/node/webpack:/Ganache/core/lib/src/server.js:10:94)
      at listen (node_modules/ganache/dist/node/webpack:/Ganache/core/lib/src/server.js:150:24)
      at web3.js/node_modules/pify/index.js:32:6
      at new Promise (<anonymous>)
      at web3.js/node_modules/pify/index.js:6:9
      at ret (node_modules/pify/index.js:56:76)
      at Context.<anonymous> (test/websocket.ganache.js:39:34)
      at processImmediate (internal/timers.js:464:21)

  7) WebsocketProvider (ganache)
       "after each" hook for ""error" handler fires if the client closes unilaterally":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (web3.js/test/websocket.ganache.js)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
```

**Comment by jdevcs** [comment]
> Failing tests:
> 
> ```
> 1) web.providers.givenProvider (ganache)
>      requestManager attaches 4 listeners:
> 
>     AssertionError [ERR_ASSERTION]: 1 == 0
>     + expected - actual
> 
>     -1
>     +0
>     
>     at Context.<anonymous> (test/3_givenProvider-ganache.js:30:16)
>     at processImmediate (internal/timers.js:464:21)
> 
> 2) web.providers.givenProvider (ganache)
>      deploys a contract:
>    RuntimeError: VM Exception while processing transaction: Transaction's maxFeePerGas (1) is less than the block's baseFeePerGas (875000000) (vm hf=london -> block -> tx)
>     at Miner.result (node_modules/ganache/dist/node/webpack:/Ganache/chains/ethereum/ethereum/lib/src/miner/miner.js:318:31)
>     at Miner.transactions (node_modules/ganache/dist/node/webpack:/Ganache/chains/ethereum/ethereum/lib/src/miner/miner.js:168:27)
>     at Miner.result (node_modules/ganache/dist/node/webpack:/Ganache/chains/ethereum/ethereum/lib/src/miner/miner.js:83:39)
>     at Miner.transactions [as mine] (node_modules/ganache/dist/node/webpack:/Ganache/chains/ethereum/ethereum/lib/src/miner/miner.js:454:19)
>     at Blockchain.resolvedPromise [as mine] (node_modules/ganache/dist/node/webpack:/Ganache/chains/ethereum/ethereum/lib/src/blockchain.js:267:17)
>     at async Promise.all (index 0)
>     at TransactionPool.emit (node_modules/ganache/dist/node/webpack:/Ganache/core/node_modules/emittery/index.js:302:9)
> 
> 3) web.providers.givenProvider (ganache)
>      "after all" hook for "can repeatedly setProvider without triggering MaxListeners":
>    TypeError: provider.close is not a function
>     at Context.<anonymous> (test/3_givenProvider-ganache.js:26:18)
>     at processImmediate (internal/timers.js:464:21)
> 
> 4) subscription connect/reconnect
>      "before each" hook for "subscribes (baseline)":
>    TypeError: Cannot read private member from an object whose class did not declare it
>     at __classPrivateFieldGet (node_modules/ganache/dist/node/webpack:/Ganache/core/lib/src/server.js:10:94)
>     at listen (node_modules/ganache/dist/node/webpack:/Ganache/core/lib/src/server.js:150:24)
>     at web3.js/node_modules/pify/index.js:32:6
>     at new Promise (<anonymous>)
>     at web3.js/node_modules/pify/index.js:6:9
>     at ret (node_modules/pify/index.js:56:76)
>     at Context.<anonymous> (test/eth.subscribe.ganache.js:16:34)
>     at processImmediate (internal/timers.js:464:21)
> 
> 5) subscription connect/reconnect
>      "after each" hook for "subscribes (baseline)":
>    Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (web3.js/test/eth.subscribe.ganache.js)
>     at listOnTimeout (internal/timers.js:557:17)
>     at processTimers (internal/timers.js:500:7)
> 
> 6) WebsocketProvider (ganache)
>      "error" handler fires if the client closes unilaterally:
>    TypeError: Cannot read private member from an object whose class did not declare it
>     at __classPrivateFieldGet (node_modules/ganache/dist/node/webpack:/Ganache/core/lib/src/server.js:10:94)
>     at listen (node_modules/ganache/dist/node/webpack:/Ganache/core/lib/src/server.js:150:24)
>     at web3.js/node_modules/pify/index.js:32:6
>     at new Promise (<anonymous>)
>     at web3.js/node_modules/pify/index.js:6:9
>     at ret (node_modules/pify/index.js:56:76)
>     at Context.<anonymous> (test/websocket.ganache.js:39:34)
>     at processImmediate (internal/timers.js:464:21)
> 
> 7) WebsocketProvider (ganache)
>      "after each" hook for ""error" handler fires if the client closes unilaterally":
>    Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (web3.js/test/websocket.ganache.js)
>     at listOnTimeout (internal/timers.js:557:17)
>     at processTimers (internal/timers.js:500:7)
> ```

There is no activity on this PR so closing, @petrosDemetrakopoulos feel free to reopen when you have time for fixing failing tests.

**Pull request closed without merging**
