### PR TITLE
v1.6.1

### PR DESCRIPTION
**Pull request by Spacesai1or**
### Added

- Support for `eth_createAccessList` as both an rpc call (`web3.eth.createAccessList`) and property of contract method wrappers (`contractInstance.methods.getValue().createAccessList`) (#4332)

### Changed

- Not considering `tx.chainId` if `tx.common.customChain.chainId` is provided for `web3.eth.accounts.signTransaction` function (#4293)
- Added missing PromiEvent handler types (#4194) 
- Updated README to include Webpack 5 angular support instructions (#4174)
- Updated the documentation for the `Web3.utils`, removed context for `_` (underscore lib) (#4403)
- Emit subscription id with connect event when creating a subscription (#4300)
- Introduced new configuration "blockHeaderTimeout" for waiting of block headers for transaction receipt  (#3891)
- Format `block.baseFeePerGas` to number (#4330)
- Correct `web3-eth-personal.sendTransaction` example in documentation (#4409)
- Updated README to include Webpack 5 angular support instructions (#4174)

### Fixed

- Fix 1.6.1 build size issue with removing static asset files (#4506)
- Correct `web3.rst` example in documentation (#4511)
- Correct `BlockHeader` typing (`receiptRoot` -> `receiptsRoot`) (#4452)

### CODE REVIEW

**Comment by Spacesai1or** [comment]
As part of the RC process, am doing some test installations in other projects and running their tests to see if everything.  
+ installs properly
+ builds
+ tests pass

| Project | Desc | Status | 
| ------ | ----- | ----- |
| [oz-test-helpers][1] | Test utils. Subset of their suite is web3 contracts | ✅  |
| [synthetix][2] | ~1000 units | ✅  |


[1]: https://github.com/OpenZeppelin/openzeppelin-test-helpers
[2]: https://github.com/Synthetixio/synthetix

**Comment by Spacesai1or** [comment]
As part of the RC process, am doing some test installations in other projects and running their tests to see if everything.  
+ installs properly
+ builds
+ tests pass

| Project | Desc | Status | 
| ------ | ----- | ----- |
| [oz-test-helpers][1] | Test utils. Subset of their suite is web3 contracts | ✅  |
| [synthetix][2] | ~1000 units | ✅  |


[1]: https://github.com/OpenZeppelin/openzeppelin-test-helpers
[2]: https://github.com/Synthetixio/synthetix

**Comment by Spacesai1or** [comment]
As part of the RC process, am doing some test installations in other projects and running their tests to see if everything.  
+ installs properly
+ builds
+ tests pass

| Project | Desc | Status | 
| ------ | ----- | ----- |
| [oz-test-helpers][1] | Test utils. Subset of their suite is web3 contracts | ✅  |
| [synthetix][2] | ~1000 units | ?  |

I was unable to run the Synthetix tests, running `npm test` provides no output

[1]: https://github.com/OpenZeppelin/openzeppelin-test-helpers
[2]: https://github.com/Synthetixio/synthetix

**Comment by luu-alex** [comment]
| Project | Desc | Status | 
| ------ | ----- | ----- |
| [synthetix][2] | ~1000 units |   6 Failing testcases  |

3441 passing (26m)
  19 pending
  6 failing

  1) Contract: EtherWrapper
       On deployment of Contract
         should have a default
           mintFeeRate of 50 bps:

      AssertionError: expected '20000000000000000' to equal '5000000000000000'
      + expected - actual

      -20000000000000000
      +5000000000000000
      
      at Object.assertBNEqual [as bnEqual] (test/utils/index.js:348:10)
      at Context.<anonymous> (test/contracts/EtherWrapper.js:143:12)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  2) Contract: EtherWrapper
       On deployment of Contract
         should have a default
           burnFeeRate of 50 bps:

      AssertionError: expected '500000000000000' to equal '5000000000000000'
      + expected - actual

      -500000000000000
      +5000000000000000
      
      at Object.assertBNEqual [as bnEqual] (test/utils/index.js:348:10)
      at Context.<anonymous> (test/contracts/EtherWrapper.js:146:12)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  3) Contract: EtherWrapper
       totalIssuedSynths
         when mint(1 sETH) is called
           fees escrowed = 0.005:

      AssertionError: expected '20000000000000000' to equal '5000000000000000'
      + expected - actual

      -20000000000000000
      +5000000000000000
      
      at Object.assertBNEqual [as bnEqual] (test/utils/index.js:348:10)
      at Context.<anonymous> (test/contracts/EtherWrapper.js:173:12)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  4) Contract: EtherWrapper
       totalIssuedSynths
         when mint(1 sETH) is called
           then burn(`reserves + fees` WETH) is called
             fees escrowed = 0.01:

      AssertionError: expected '20500000000000000' to equal '10000000000000000'
      + expected - actual

      -20500000000000000
      +10000000000000000
      
      at Object.assertBNEqual [as bnEqual] (test/utils/index.js:348:10)
      at Context.<anonymous> (test/contracts/EtherWrapper.js:191:13)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  5) Contract: EtherWrapper
       totalIssuedSynths
         when mint(1 sETH) is called
           then burn(`reserves + fees` WETH) is called
             then distributeFees is called
               total issued sUSD = $15:

      AssertionError: expected '30750000000000000000' to equal '15000000000000000000'
      + expected - actual

      -30750000000000000000
      +15000000000000000000
      
      at Object.assertBNEqual [as bnEqual] (test/utils/index.js:348:10)
      at Context.<anonymous> (test/contracts/EtherWrapper.js:202:14)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  6) Contract: SynthetixState
       lastDebtLedgerEntry()
         should correctly report lastDebtLedgerEntry:
     AssertionError: expected 'Transaction reverted without a reason' to include 'invalid opcode'
      at Object.assertInvalidOpcode [as invalidOpcode] (test/utils/index.js:497:11)
      at Context.<anonymous> (test/contracts/SynthetixState.js:166:4)

**Comment by Spacesai1or** [comment]
Ran tests using `web3` `1.5.3` and `1.6.1-rc.3` and all tests passed
image

**Review by nazarhussain — APPROVED** [review]

**Review by luu-alex — APPROVED** [review]

**Pull request merged**
