### PR TITLE
node installation using nvm

### PR DESCRIPTION
**Pull request by heyitsarpit**
Previous node installation instructions only targeted ubuntu based distribution.

### CODE REVIEW

**Review by nivida — APPROVED** [review]
Could you please resolve the conflicts? :)

**Comment by heyitsarpit** [comment]
Resolved conflicts in Readme.md

**Comment by heyitsarpit** [comment]
Thanks for merging the changes, but I'm confused, why are these changes not reflected on the ReadMe.md on the repo page?

**Comment by nivida** [comment]
Closed because the latest maintenance release was 0.20.7.

**Pull request closed without merging**
