### PR TITLE
Fix transactionRoot -> transactionsRoot in BlockHeader

### LINKED ISSUE #4871: Mismatched interface
https://github.com/ChainSafe/web3.js/blob/505b833b0952b231ef2728c752d6667c9ed0f858/packages/web3-eth/types/index.d.ts#L404

The actual key described in the protocol is `transactionsRoot` with a `s`.
See: https://eth.wiki/json-rpc/API#eth_getlogs

### PR DESCRIPTION
**Pull request by OscBacon**
## Description

Fix transactionRoot -> transactionsRoot in BlockHeader

Fixes #4871

## Type of change

- Bug fix (non-breaking change which fixes an issue)

Note: only changing the interface

### CODE REVIEW

**Comment by OscBacon** [comment]
@nikoulai εδώ είναι!

**Comment by OscBacon** [comment]
Also note, I ran a quick `grep -r` and there's no reference in the repo to transaction(s)Root :)

**Review by ghost — APPROVED** [review]
Encountered the same problem. Would have made the same change. 👍

**Comment by ghost** [comment]
@OscBacon I encountered the same problem. Thanks for creating this PR. Would really like this merged 👍

**Comment by OscBacon** [comment]
No problem @vcheeney !
@nikoulai, could you please give the second thumbs up?

**Review by nazarhussain — CHANGES_REQUESTED** [review]
Please add entry to CHANGELOG.md

**Review by avkos — APPROVED** [review]
Please add comments to CHANGELOG.md

**Comment by OscBacon** [comment]
@avkos ? where in the file? and with or without a version tag?

**Comment by nikoulai** [comment]
@OscBacon Hi,
you will find CHANGELOG.md at the root of the repo.  You can mention your change under 1.7.5 with a reference to the issue.   Take as example the other comments.

**Comment by OscBacon** [comment]
@nikoulai Done! Please merge whenever you can!

**Review by nikoulai — APPROVED** [review]

**Comment by nikoulai** [comment]
@OscBacon Looks good.

Have to wait for changes to be approved. 
cc @nazarhussain

**Review by jdevcs — APPROVED** [review]

**Review by nazarhussain — APPROVED** [review]

**Comment by OscBacon** [comment]
Hey @nazarhussain, @jdevcs, @nikoulai: could one of you authorize the merge now please? :)

**Comment by jdevcs** [comment]
Merged via https://github.com/ChainSafe/web3.js/pull/5197

**Pull request merged**
