### PR TITLE
isHex: '0x' prefix changed to be optional

### PR DESCRIPTION
**Pull request by chatch**
added unit tests: utils.isHex.js
added all cases documented in web3-utils.rst - most were breaking but now pass

### CODE REVIEW

**Comment by chatch** [comment]
ok so this breaks a bunch of code that is expecting the isHex call to fail if there is no '0x' prefix.  one example: utils.soliditySha3.

so maybe it's the web3-utils.rst doc that should change rather then this function.

**Comment by frozeman** [comment]
Could you please point me to examples in the doc where it states hex should be without prefix?

**Comment by chatch** [comment]
https://github.com/ethereum/web3.js/blob/1.0/docs/web3-utils.rst#ishex

web3.utils.isHex('c1912');

**Comment by frozeman** [comment]
I added the `web3.utils.isHexStrict` function which expects `0x` and it being a string, and `isHex` is now more flexible and adhers to the docs. This is potentially a breaking change, for apps who relied on 'isHex'

**Comment by frozeman** [comment]
Thanks for your finding!

**Pull request closed without merging**
