### PR TITLE
1.0

### PR DESCRIPTION
**Pull request by frozeman**
- [x] Removes the old filter api completely and adds the new subscription API
- [x] Adds new contract object
- [x] Adds new documentation: http://web3js.readthedocs.io/en/1.0/
- [ ] Refactors web3 to be more modular
- [ ] Promisifies all functions
- [ ] Removes properties and allow only functions

### CODE REVIEW

**Comment by debris** [comment]
What is the current status of new subscription API in official ethereum implementations (go / cpp / python) ? I think this pr should wait until after majority of them supports it.

**Comment by frozeman** [comment]
There is still a lot todo for the 1.0 refactor of web3.js. So don't worry about time.

Currently its only go supporting subscriptions. Oythong an cpp will follow, at some point.

You can find the specs here: https://hackpad.com/RPC-interface-VDul0tsDu1t

**Comment by harshjv** [comment]
@frozenman need any hand in promisification?

**Comment by atifnimran** [comment]
a55e7a7baeabc4691c313964b94cdbf0d4540eaf

**Comment by atifnimran** [comment]
Ok

**Comment by atifnimran** [comment]
Okay thanks

**Pull request merged**
