### PR TITLE
Improve clarity of HttpProvider keepAlive value

### PR DESCRIPTION
**Pull request by prestwich**
Don't use a ternary statement on a boolean statement to resolve truthiness. Just double-negate it

## Description

Please include a summary of the change and be sure you follow the contributions rules we do provide [here](./CONTRIBUTIONS.md)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran ```npm run dtslint``` with success and extended the tests and types if necessary.
- [ ] I ran ```npm run test:unit``` with success.
- [ ] I have executed ``npm run test:cov`` and my test cases do cover all lines and branches of the added code.
- [ ] I ran ```npm run build-all``` and tested the resulting file/'s from  ```dist``` folder in a browser.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [ ] I have tested my code on the live network.

### CODE REVIEW

**Comment by prestwich** [comment]
https://twitter.com/gnidan/status/1248339020574265345

**Comment by prestwich** [comment]
The ideal version of this may be `const keepAlive = options.keepAlive !== false;` but I'm too annoyed by JS to keep thinking about it :D

**Comment by ryanio** [comment]
> The ideal version of this may be `const keepAlive = options.keepAlive !== false;` but I'm too annoyed by JS to keep thinking about it :D

That seems clear and straight-forward to me if you want to update the PR to that :)

Thanks @gnidan for your feedback about the default behavior. @prestwich it might be helpful to others in the future too if you want to add a small comment in the source there (about the default behavior of keepAlive).

**Comment by prestwich** [comment]
Updated the PR, added a comment, and squashed to a single commit

**Review by ryanio — DISMISSED** [review]
LGTM! thanks :)

Edit: actually sorry one last thing, could you add an entry in the changelog noting the update?

**Comment by cgewecke** [comment]
Updated the changelog in a7c6156

**Review by nivida — DISMISSED** [review]

**Review by cgewecke — APPROVED** [review]
LGTM

**Pull request merged**
