### PR TITLE
Add typings for the web3 contract methods

### PR DESCRIPTION
**Pull request by tbhaxor**
## Description

This PR will add the typings for the contract methods [call](https://web3js.readthedocs.io/en/v1.2.11/web3-eth-contract.html#methods-mymethod-call), [send](https://web3js.readthedocs.io/en/v1.2.11/web3-eth-contract.html#methods-mymethod-send), [encodeABI](https://web3js.readthedocs.io/en/v1.2.11/web3-eth-contract.html#methods-mymethod-encodeabi) and [estimateGas](https://web3js.readthedocs.io/en/v1.2.11/web3-eth-contract.html#methods-mymethod-estimategas) including all the  overloads.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have added documentation for the fields.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [x] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [x] I ran `npm run test:unit` with success.
- [x] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [x] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

### CODE REVIEW

**Comment by tbhaxor** [comment]
Hey, I am not sure about the failed test case. Could you help in fixing the code?

**Comment by jdevcs** [comment]
@tbhaxor Thanks for your contributions. 
It will be best to wait for full types support in [Web3.js 4.x](https://github.com/ChainSafe/web3.js/tree/4.x) its completely being written in ts. Contributions in 4.x ( adding missing items, features, reviews, suggestions ) are also welcome if you have time.

**Review by jdevcs — COMMENTED** [review]
@tbhaxor Thanks for your contributions. 
It will be best to wait for full types support in [Web3.js 4.x](https://github.com/ChainSafe/web3.js/tree/4.x) its completely being written in ts. Contributions in 4.x ( [adding missing items, features, reviews, suggestions](https://github.com/ChainSafe/web3.js/blob/4.x/packages/web3-eth-contract/src/types.ts) ) are also welcome if you have time.

**Comment by tbhaxor** [comment]
Hey @jdevcs Thanks for your review. I have question. 

In 4.x tree, do I still have to open the PR for 1.x branch or is there any typo in the [CONTRIBUTIONS.md](https://github.com/ChainSafe/web3.js/blob/4.x/CONTRIBUTIONS.md)

**Comment by jdevcs** [comment]
> Hey @jdevcs Thanks for your review. I have question.
> 
> In 4.x tree, do I still have to open the PR for 1.x branch or is there any typo in the [CONTRIBUTIONS.md](https://github.com/ChainSafe/web3.js/blob/4.x/CONTRIBUTIONS.md)

We will update these documents for 4.x . You should open PR for 4.x branch, if you want to contribute in that. Many Thanks

**Comment by nazarhussain** [comment]
@tbhaxor As @jdevcs suggested please open PR against 4.x branch. I am closing this PR in that context.

**Pull request closed without merging**
