### PR TITLE
+ add personal API support

### PR DESCRIPTION
**Pull request by almindor**
Adds personal API support to use. Might need some security warnings to use only via IPC provider.

### CODE REVIEW

**Comment by frozeman** [comment]
Thanks for the PR, but we have on purpose not included any admin API in web3 by default, we have first to discuss on how we want to do this. (e.g. separate module, or shipped with web3)

**Comment by almindor** [comment]
OK, how about exposing the setupParameters and setupMethods so people can add their own into your library without modifying the original code? That'd solve it for my use for not.

**Comment by frozeman** [comment]
We have a semi official method called web3._extend(). See here for an example: https://github.com/ethereum/mist/blob/master/modules/preloader/web3Admin.js

**Comment by almindor** [comment]
Ah I see, thanks for the info. I'll use that for the time being.

**Pull request closed without merging**
