### PR TITLE
1.8.2

### PR DESCRIPTION
**Pull request by jdevcs**
### Changed

- Updated Webpack 4 to Webpack 5, more details at (#5629)
- `crypto-browserify` module is now used only in webpack builds for polyfilling browsers (#5629)
- Updated `ethereumjs-util` to `7.1.5` (#5629)
- Updated `lerna` 4 to version 6 (#5680) 
- Bump utils 0.12.0 to 0.12.5 (#5691)

### Fixed

-  Fixed types for `web3.utils._jsonInterfaceMethodToString` (#5550)
-  Fixed Next.js builds failing on Node.js v16, Abortcontroller added if it doesn't exist globally (#5601)
-  Builds fixed by updating all typescript versions to 4.1 (#5675) 

### Removed

- `clean-webpack-plugin` has been removed from dev-dependencies (#5629)

### Added

- `https-browserify`, `process`, `stream-browserify`, `stream-http`, `crypto-browserify` added to dev-dependencies for polyfilling (#5629)
- Add `readable-stream` to dev-dependancies for webpack (#5629) 

### Security
-  `npm audit fix` for libraries update (#5726)

### CODE REVIEW

**Comment by jdevcs** [comment]
As part of the RC process, following test installations are performed in other projects and running their tests to see if everything.  
+ installs properly
+ builds
+ tests pass

(This list will be actively edited) 

| Project | Desc | Status | 
| ------ | ----- | ----- |
| [oz-test-helpers][1] | Test utils. Subset of their suite is web3 contracts |   |
| [synthetix][2] | ~1000 units |    |


[1]: https://github.com/OpenZeppelin/openzeppelin-test-helpers
[2]: https://github.com/Synthetixio/synthetix

**Comment by luu-alex** [comment]
When running synthetix, I got a few errors
```
```
edit:

ISSUE RESOLVED ✅

**Comment by luu-alex** [comment]
Openzeppelin tests are passing ✅

**Comment by avkos** [comment]
synthetix test results

```
 4435 passing (1h)
  71 pending
  1 failing

  1) Contract: SupplySchedule
       functions and modifiers
         Given inflation amount of 800,000 - mintable supply
           should calculate the mintable supply as 0 within 1st week of inflation start date:
     Error: Time parameter (Wed Mar 06 2019 23:00:00 GMT-0500 (Eastern Standard Time)) is less than now Wed Mar 06 2019 23:11:08 GMT-0500 (Eastern Standard Time). You can only fast forward to times in the future.
      at fastForwardTo (test/utils/index.js:111:10)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Context.<anonymous> (test/contracts/SupplySchedule.js:205:5)

```

@openzeppelin/test-helpers finished with errors:

```
 275 passing (55s)
  3 failing

  1) expectRevert
       expectRevert
         rejects a revert with incorrect expected reason:

      AssertionError: expected 'VM Exception while processing transac…' to equal 'Call to revert'
      + expected - actual

      -VM Exception while processing transaction: revert Call to revert
      +Call to revert
      
      at Context.<anonymous> (test/src/expectRevert.test.js:34:35)

  2) expectRevert
       assertion
         rejects an outOfGas:
     AssertionError: expect.fail()
      at assertFailure (test/helpers/assertFailure.js:9:10)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Context.<anonymous> (test/src/expectRevert.test.js:123:7)

  3) expectRevert
       outOfGas
         accepts an outOfGas:

      Wrong kind of exception received
      + expected - actual

      -Transaction: 0x30de5aa6fcc2811d6a7407af251c16b423e14efe5219ebfd895a273de802c567 exited with an error (status 0) after consuming all gas.
      -     Please check that the transaction:
      -     - satisfies all conditions set by Solidity `assert` statements.
      -     - has enough gas to execute the full transaction.
      -     - does not trigger an invalid opcode by other means (ex: accessing an array out of bounds).
      +out of gas
      
      at expectException (src/expectRevert.js:20:30)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Context.<anonymous> (test/src/expectRevert.test.js:153:7)


```

**Comment by luu-alex** [comment]
I just checked and the all failing testcases I have mentioned have been reported by me since a year ago. I don't believe anything has changed.

**Comment by jdevcs** [comment]
> I just checked and the all failing testcases I have mentioned have been reported by me since a year ago. I don't believe anything has changed.

Thanks @luu-alex  , @avkos and @Muhammad-Altabba https://github.com/web3/web3.js/issues/5760

**Comment by jdevcs** [comment]
We will include https://github.com/web3/web3.js/issues/5752 in this release if there are any code changes required , discussed in web3 team meeting.

**Comment by jdevcs** [comment]
There are no code changes required for fixing #5752 in https://github.com/web3/web3.js/pull/5779 , only test code is changed so we will include/merge this PR in next release.

**Review by nikoulai — APPROVED** [review]

**Review by luu-alex — APPROVED** [review]

**Review by Fqc301033 — COMMENTED** [review]
1

**Pull request merged**
