### PR TITLE
Fix 6611 uncaught type error calling a contract's function with insufficient funds on Polygon

### PR DESCRIPTION
**Pull request by nicos99**
## Description

Add a security in the the callback function of _"web3-core-methode / buildCall / send"_ in case there is no error raison data (as it can be seen for insufficient funds on Pologon PoS) to avoid throwing _"TypeError: (intermediate value).data is undefined"_ exception that can't be caught in user side.

Add a new unit test case about this to ensure non-regression.

Fixes issue #6611

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I ran `npm run lint` with success and extended the tests and types if necessary. --> Increased the function's cyclomatic complexity that was already too high.
- [x] I ran `npm run test:unit` with success. --> still 2 failing tests about re-connect
- [x] I ran `npm run test:coverage` and my test cases cover all the lines and branches of the added code. --> _Missing script: "test:coverage"_. I tried `npm run test:cov` but I don't know how to interpret the result
- [x] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [x] I have tested my code on the live network. --> only on Polygon.
- [x] I have updated the `CHANGELOG.md` file in the root folder.
- [ ] I have linked Issue(s) with this PR in "Linked Issues" menu.

### CODE REVIEW

**Comment by nicos99** [comment]
Hello, can-you please review this PR ? Maybe starting with you @Muhammad-Altabba  ? Thanks 😉

**Comment by jdevcs** [comment]
@nicos99 could you check 4.x for this error , and use that?

**Comment by nicos99** [comment]
> @nicos99 could you check 4.x for this error , and use that?

@jdevcs There is no issue with 4.x (see discussion with @Muhammad-Altabba in #6611). if I understand correctly my proposed fix will not be merged because there is no desire to release a new 1.x version, correct?

**Comment by jdevcs** [comment]
> > @nicos99 could you check 4.x for this error , and use that?
> 
> @jdevcs There is no issue with 4.x (see discussion with @Muhammad-Altabba in #6611). if I understand correctly my proposed fix will not be merged because there is no desire to release a new 1.x version, correct?

Yes, 1.x will soon retire and its on min support, I'll suggest to migrate to 4.x, and if you need any help in migration let us know. plus share if there is any 4.x feedback for feature requests or bug reports.

**Comment by nicos99** [comment]
so let's forget my work...

**Pull request closed without merging**
