### PR TITLE
fix: fix utils.hexToBytes

### PR DESCRIPTION
**Pull request by Keith-CY**
```
const utils = require('./web3.js/packages/web3-utils/src/index')
const value = "0x21e19e0c9bab2400000"
const b = utils.hexToBytes(value)
const h = utils.bytesToHex(b)
// before fix
console.log(value) // 0x21e19e0c9bab2400000
console.log(h)     // 0x21e19e0c9bab24000000
// after fix
console.log(value) //0x21e19e0c9bab2400000
console.log(h)     //0x21e19e0c9bab2400000
```

### CODE REVIEW

**Comment by nivida** [comment]
If you would like to get this released in the version beta.38 then please do these changes against the ethereumProvider branch (#2000). If not then could you please later update this PR or open a new one?

**Comment by Keith-CY** [comment]
@nivida updated

**Comment by nivida** [comment]
@Keith-CY Sorry, but could you be that nice and resolve these conflicts for me? :)

**Comment by Keith-CY** [comment]
@nivida sorry for that, new commit proposed https://github.com/ethereum/web3.js/pull/2207

**Pull request closed without merging**
