### PR TITLE
Completed hardhat/web3v4 tutorial

### PR DESCRIPTION
**Pull request by bobeu**
Tutorial completed!

### CODE REVIEW

**Comment by SantiagoDevRel** [comment]
Great job🎉! LGTM

**Comment by bobeu** [comment]
> Great job🎉! LGTM

Thank you @SantiagoDevRel 
I saw the changes you made. Awesome! Has the PR merged?

**Comment by SantiagoDevRel** [comment]
No, It'll be reviewed/approved by the devs and after you get 2 approvals you can squash and merge (it might take a couple of days) @bobeu

**Review by avkos — APPROVED** [review]

**Review by jdevcs — APPROVED** [review]
lgtm

**Comment by SantiagoDevRel** [comment]
Thanks @bobeu , merged!

**Comment by bobeu** [comment]
> Thanks @bobeu , merged!

Thank you @SantiagoDevRel . Shoutout to all the devs.

**Pull request merged**
