### PR TITLE
fixes issue when number can only safely store up to 53 bits

### PR DESCRIPTION
**Pull request by fonov**
## Description

fixes issue when number can only safely store up to 53 bits

https://github.com/ethereum/web3.js/issues/3745

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [x] I ran `npm run test:unit` with success.
- [x] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [x] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [x] I have tested my code on the live network.
- [x] I have checked the Deploy Preview and it looks correct.

### CODE REVIEW

**Review by BryanLaura — APPROVED** [review]

**Comment by Spacesai1or** [comment]
Thank you for opening a PR for this! After discussing this with the team, this would be a breaking change for the library and doesn't make sense to do it in this way for now. To achieve similar functionality without a breaking change, would require an overwriting functionality that will exist using the plugin system we have planned for `1.4.x`, but there is not definite timeline for the feature yet

I'm curious to know if this was a one-off issue for you for [this](https://bscscan.com/tx/0xe0db32759810271eec05326a4c96fbb42a185139134e16b4581f77456df226a9) transaction, or is this something you've faced multiple times? It's just extremely unusual to set such a high `gasLimit`

**Comment by fonov** [comment]
Hello @spacesailor24. I often see this `gasLimit` 

<details>
  <summary>Similar transactions with hight `gasLimit`</summary>
  
  https://bscscan.com/tx/0x442496852e205278cc6b8fc0c3f5a93579a2330a67b037aef1329f13aff97aae
  https://bscscan.com/tx/0x4245075a7f3490d7845af268f73879e5a4a329d129fdaad238e1d5304b8591f6
  https://bscscan.com/tx/0x2ec2b2a0697c074c707e0b8380bbc2535154338381ed4491f32d0ce390af7fa5
</details>

Right now i used `patch-package` for fixed package locally

**Comment by Spacesai1or** [comment]
Thank you for the reply, I'm happy to hear you've found a work around. As mentioned above, we most likely won't be merging this any time soon, but we will keep this in mind for the next major version update

**Comment by lucaspiressimao** [comment]
this could help https://github.com/ChainSafe/web3.js/issues/3936#issuecomment-797342613

**Pull request closed without merging**
