### PR TITLE
Format repo, add new rules

### PR DESCRIPTION
**Pull request by luu-alex**
## Description

- changed .eslintrc.js - on push, test files ignore 	'@typescript-eslint/no-unsafe-call' and import/no-unresolved
for all ts files - ignore default-param-last rule.
This will allow us to git push without running into errors that are not a problem for the library.
- before commits, changed files will be formatted proeprly
- formatted all files.

Please include a summary of the changes and be sure to follow our [Contribution Guidelines](https://github.com/web3/web3.js/blob/4.x/.github/CONTRIBUTING.md).

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run lint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:coverage` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [ ] I have linked Issue(s) with this PR in "Linked Issues" menu.

### CODE REVIEW

**Review by avkos — APPROVED** [review]

**Review by jdevcs — COMMENTED** [review]
This code formatting in a large size will significantly improve readability and ease maintenance by creating a consistent style. However, a major drawback is the loss of historical context, when a substantial number of lines are altered for formatting, it obscures the history of actual functional changes, making it challenging to understand the evolution of the codebase. Additionally, tools like git blame may become hard to use, as they will highlight formatting changes instead of the original authorship of the logic, complicating the ability to trace who made specific contributions to the code.

**Comment by luu-alex** [comment]
@jdevcs  The tradeoffs you highlighted are valuable to note. I believe eventaully we will need to format this library and once we do we can have a working order of code formatting going forward, as the rules I created will always format the library to standard. I think the to look back on the actual git blame we can take a look at the previous git commits within github.
If you do not believe this is the time to format the library, we should have a consideration of when this should happen as I believe we will find real value having a consistent library for formatting.

**Review by jdevcs — APPROVED** [review]
As we discussed in team call, pls make sure there is no code change in this PR except for config of (pre commit hook for formatting), thanks

**Comment by jdevcs** [comment]
@luu-alex merge this PR for avoiding merge conflicts, as its massively touching each file.

**Pull request merged**
