### PR TITLE
Force `toBlock` not being set when calling myContract.events.<eventName> or myContract.events.allEvents

### LINKED ISSUE #3207: Undesired behaviour and unexpected error when `toBlock` is passed to `myContract.events.<eventName>` or `myContract.events.allEvents`
### Intro

Right now if you want to use `myContract.events.<eventName>` or `myContract.events.allEvents` with the option `toBlock`, **which is not in the documentation**, different from `latest`. The call ends up in an undesired behaviour.

If you set `fromBlock` different from `latest`, a [`eth_getLogs` call will be done](https://github.com/ethereum/web3.js/blob/1.x/packages/web3-core-subscriptions/src/subscription.js#L221) to get the past events from `fromBlock` to `latest` without using `toBlock` -> Almost ok!. But later, `fromBlock` is [removed from the options](https://github.com/ethereum/web3.js/blob/1.x/packages/web3-core-subscriptions/src/subscription.js#L246) and a subscription is made with `{ fromBlock: undefined, toBlock: 100}`.  Based on the [subscribe implementation](https://github.com/ethereum/go-ethereum/blob/d42ce0f2c1b52e26cce475e411d97165fb975577/eth/filters/filter_system.go#L200) of _go-ethereum_, if `fromBlock === null` (bacically, if it is not set), will set `fromBLock` as `later`.

This will finally check `fromBlock: 'latest'` and `toBlock: 100` returning, obviously, [invalid from and to block combination: from > to](https://github.com/ethereum/go-ethereum/blob/d42ce0f2c1b52e26cce475e411d97165fb975577/eth/filters/filter_system.go#L231)

#### Expected behavior

Throw an error saying that `toBlock` is not a valid option.

#### Actual behavior

Error with `invalid from and to block combination: from > to` which is not an error from web3. But a  [go-ethereum](https://github.com/ethereum/go-ethereum/blob/d42ce0f2c1b52e26cce475e411d97165fb975577/eth/filters/filter_system.go#L231) one

#### Steps to reproduce the behavior

1. Call `myContract.events.MyEvent({ fromBlock: 0,  toBlock: 'latest' })` or `myContract.events.allEvents({ fromBlock: 0,  toBlock: '100' })`

#### Versions
Web3.js 1.X

Thanks @fmiras for the heads up.

### PR DESCRIPTION
**Pull request by nachomazzara**
## Description

Throw if `toBlock` is set when calling  `myContract.events.<eventName>` or `myContract.events.allEvents`

Fixes #3207

## Type of change

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected). If it is being called with `toBlock: 'latest'`

### CODE REVIEW

**Comment by nachomazzara** [comment]
See [this commint](https://github.com/ethereum/web3.js/pull/3208/commits/ac5f90bcafd82b25acf802d544e316f6658226d5) to better understand the change. 

The files had a wrong format based on the .editorconfig rules.

**Comment by wbt** [comment]
Looks like those automated tests hung.

**Comment by nachomazzara** [comment]
Do we want it? I can resolve the conflicts

**Comment by ryanio** [comment]
@nachomazzara that would be awesome, thank you

**Comment by ryanio** [comment]
@nachomazzara when you get a chance to update the branch, could you leave out any lint/format changes for now? just so we have a clean diff of just the most relevant changes.

it looks good though and i hope to include this in v1.2.10

**Comment by nachomazzara** [comment]
Closed By #3567

**Comment by nachomazzara** [comment]
@ryanio Github gots crazy and I needed to create a new PR https://github.com/ethereum/web3.js/pull/3567

**Comment by ryanio** [comment]
@nachomazzara no problem, thanks!

**Pull request closed without merging**
