### PR TITLE
firefox test

### PR DESCRIPTION
**Pull request by avkos**
## Description

Please include a summary of the changes and be sure to follow our [Contribution Guidelines](../blob/1.x/CONTRIBUTIONS.md).

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist for 1.x:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` with success.
- [ ] I have tested the built `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

## Checklist for 4.x:

- [ ] I have selected the correct 4.x base branch.
- [ ] Within the description, the feature or issue is discussed in detail or an issue is linked.   
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added any required tests for the changes I made 
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `yarn` successfully
- [ ] I ran `yarn lint` successfully
- [ ] I ran `yarn build:web` successfully
- [ ] I ran `yarn test:unit` successfully
- [ ] I ran `yarn test:integration` successfully
- [ ] I ran `compile:contracts` successfully
- [ ] I have tested my code.
- [ ] I have updated the corresponding `CHANGELOG.md` file in the packages I have edited.

### CODE REVIEW

**Comment by luu-alex** [comment]
Nice!

**Review by luu-alex — APPROVED** [review]

**Comment by Spacesai1or** [comment]
We should still update the `CHANGELOG.md` for this, no? Also does this fix need to be applied to `1.x`?

**Comment by luu-alex** [comment]
@spacesailor24  yup we'll need a PR for 1.x too

**Comment by Muhammad-Altabba** [comment]
Thanks for the solution :+1: 

And could you please elaborate on the solution? Is it something hacky because of unsolved issue in github actions? Could you please reference it? So, we can revert back this trick once they resolve that.

**Review by nikoulai — APPROVED** [review]

**Comment by avkos** [comment]
> Thanks for the solution 👍
> 
> And could you please elaborate on the solution? Is it something hacky because of unsolved issue in github actions? Could you please reference it? So, we can revert back this trick once they resolve that.

For an unknown reason, GithubActions do not have preinstalled firefox. So this fix just installs firefox. Only for the e2e firefox test. It takes 11s. I think we do not need to remove this fix in the future.

**Review by Muhammad-Altabba — APPROVED** [review]

**Pull request merged**
