### PR TITLE
Porting personal.importRawKey, personal.sign, personal.ecRecover from go-ethereum to web3.js

### PR DESCRIPTION
**Pull request by peculiarity**

### CODE REVIEW

**Comment by kumavis** [comment]
Looks good to me - we are supporting `personal_sign` and `personal_ecRecover` in MetaMask

**Comment by peculiarity** [comment]
@frozeman

**Comment by flyswatter** [comment]
> Looks good to me - we are supporting personal_sign and personal_ecRecover in MetaMask

Well, we *will* be supporting them later today.

**Comment by flyswatter** [comment]
Any idea when we can expect this on the main release?

**Comment by peculiarity** [comment]
I don't think anyone maintain this project..

**Comment by flyswatter** [comment]
@frozeman does, I thought.

**Comment by flyswatter** [comment]
I'm currently drafting a blog post about this new feature in MetaMask, it would be great to not have to have a note about how web3 hasn't implemented it yet.

**Comment by peculiarity** [comment]
At least if it's not maintained anymore, we can have a fork and start maintaining it.

**Comment by flyswatter** [comment]
I think Fabian is on a vacation or something (based on his commit history), I'm sure he'll be back soon.

**Comment by frozeman** [comment]
Yeah, sorry for the delay. i was on vacation. Merged a bunch now..

**Comment by peculiarity** [comment]
@frozeman cheers

**Comment by kuabhish** [comment]
Is it done?

**Pull request merged**
