### PR TITLE
Add pre-sort to batch requests

### LINKED ISSUE #4250: BatchRequest assumes JSON RPC requests are returned in order
#### Expected behavior
The response to a batch JSON RPC is not enforced to be in order (according to [the spec](https://www.jsonrpc.org/specification#batch)). Despite most endpoints following this convention, some (e.g. [Erigon](https://github.com/ledgerwatch/erigon/issues/2540)) do not.

This means that results can be misparsed, or worse, silently corrupted despite the response being valid.

For example if we batched the following calls from [G-UNI FLOAT/USDC contract](https://etherscan.io/address/0x4f38892c16bfbb4f4f7424eefaa9767f4e922073#readProxyContract):
- `getUnderlyingBalances(uint256,uint256)`
- `totalSupply(uint256)`

We can receive the response:
```
[
  {
    "jsonrpc": "2.0",
    "id": 2,
    "result": "0x0000000000000000000000000000000000000000000000058002c3cbfcb15f17"
  },
  {
    "jsonrpc": "2.0",
    "id": 1,
    "result": "0x000000000000000000000000000000000000000000000000000001dee1b1ea2a00000000000000000000000000000000000000000000c419a8b582118ad911b6"
  }
]
```

Which is valid and should decode to:
- (amount0Current, amount1Current) = 2056780900906, 926057156010074212733366
- totalSupply = 101457870636241215255

#### Actual behavior
In actuality, the response for `totalSupply` is attempted to be decoded as a tuple.

```
index.js:1 G-UNI USDC/FLOAT:getUnderlyingBalances.call Error: data out-of-bounds (length=32, offset=64, code=BUFFER_OVERRUN, version=abi/5.0.7)
    at Logger.makeError (index.ts:213)
    at Logger.throwError (index.ts:225)
    at Reader._peekBytes (abstract-coder.ts:182)
    at Reader.readBytes (abstract-coder.ts:196)
    at Reader.readValue (abstract-coder.ts:203)
    at NumberCoder.decode (number.ts:44)
    at array.ts:108
    at Array.forEach (<anonymous>)
    at unpack (array.ts:89)
    at TupleCoder.decode (tuple.ts:27)
    at AbiCoder.decode (abi-coder.ts:113)
    at ABICoder.push../node_modules/web3-eth-contract/node_modules/web3-eth-abi/lib/index.js.ABICoder.decodeParametersWith (index.js:303)
    at ABICoder.push../node_modules/web3-eth-contract/node_modules/web3-eth-abi/lib/index.js.ABICoder.decodeParameters (index.js:284)
    at push../node_modules/web3-eth-contract/lib/index.js.Contract._decodeMethodReturn (index.js:469)
    at batch.js:58
    at Array.forEach (<anonymous>)
    at batch.js:49
    at index.js:186
    at XMLHttpRequest.request.onreadystatechange (index.js:98)
```

#### Environment
yarn 1.22.4
```
web3-eth-contract@1.5.1, web3-eth-contract@^1.3.1:
  version "1.5.1"
  resolved "https://registry.yarnpkg.com/web3-eth-contract/-/web3-eth-contract-1.5.1.tgz#4c59abe3e575920e83e8f8c1bc0bf8a18f975623"
  integrity sha512-LRzFnogxeZagxHVpJ9cDK5Y8oQFUNtNL8s5w4IjvZ/JDoBQXPJuwhySwjftL3Hlk3znziMFqAH6snoxjvHnoag==
  dependencies:
    "@types/bn.js" "^4.11.5"
    web3-core "1.5.1"
    web3-core-helpers "1.5.1"
    web3-core-method "1.5.1"
    web3-core-promievent "1.5.1"
    web3-core-subscriptions "1.5.1"
    web3-eth-abi "1.5.1"
    web3-utils "1.5.1"
```

### PR DESCRIPTION
**Pull request by floatcoder**
## Description

Fixes #4250 

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [x] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

### CODE REVIEW

**Comment by luu-alex** [comment]
Hey sorry for the slow response, thank you for making this PR. If you could make 1-2 test cases this branch would be ready to merged asap. Otherwise I can make testcases when i can get around

**Comment by philknows** [comment]
Hi @floatcoder, just bumping above if you have any test cases. Thanks!

**Comment by nazarhussain** [comment]
@floatcoder Hi, Did you get chance to look into this thread? If you can rebase and add couple of test case for the code changes that will be great.

**Comment by nazarhussain** [comment]
@floatcoder Unfortunately we have to close this PR to get other PR merged to close the issue #4250 to include it in upcoming release.

**Comment by floatcoder** [comment]
> @floatcoder Unfortunately we have to close this PR to get other PR merged to close the issue #4250 to include it in upcoming release.

No worries! Missed the bump and have been using a patched work around - will be great to see it in an upcoming release.

**Pull request closed without merging**
