### PR TITLE
Replace Buffer with uint8array

### PR DESCRIPTION
**Pull request by mpetrunic**
## Description

Alternative to #6005 

Replaces all usage of Buffer with Uint8Array.
Pros:
- even smaller build without the need for polyfill
- if we don't do it now it needs to wait for 5.x
Cons:
- some tests are falling and I don't have time to investigate those as I'm going on a vacation
- break some API

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist for 1.x:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` with success.
- [ ] I have tested the built `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

## Checklist for 4.x:

- [ ] I have selected the correct 4.x base branch.
- [ ] Within the description, the feature or issue is discussed in detail or an issue is linked.   
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added any required tests for the changes I made 
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `yarn` successfully
- [ ] I ran `yarn lint` successfully
- [ ] I ran `yarn build:web` successfully
- [ ] I ran `yarn test:unit` successfully
- [ ] I ran `yarn test:integration` successfully
- [ ] I ran `compile:contracts` successfully
- [ ] I have tested my code.
- [ ] I have updated the corresponding `CHANGELOG.md` file in the packages I have edited.

### CODE REVIEW

**Comment by luu-alex** [comment]
This is a breaking change but I think replacing buffer is the forward, we don't want to be reliant on polyfills so there isn't complications with browser apps. If we decide to move forward, since marin is going on vacation I can take over the PR or go to another team member.

If we want browser apps to be working for next RC, we can merge #6005 for a temporary fix so users wont be facing [browser issues](https://github.com/web3/web3.js/issues/5907#issuecomment-1503699806). Then we can work on removing buffers completely.

**Comment by Spacesai1or** [comment]
I would agree that the less config the end user has to do, the better

If this replaces #6005, then we should copy over the removal of `@types/node`

**Comment by mpetrunic** [comment]
> I would agree that the less config the end user has to do, the better
> 
> If this replaces #6005, then we should copy over the removal of `@types/node`

Yeah sorry about that, it was very old branch that I rebased on top of ethereumjs branch and the commits are a bit mangled. If you want to pursue this PR, I would suggest creating new branch out of 4.x and cherry-picking the last two commits onto the new branch

**Review by jdevcs — COMMENTED** [review]
+1
 Replacing buffer with uint8arry change in current time as we can include breaking changes and it will help end users for webpacking.

**Comment by avkos** [comment]
+1 we need to do this. I think we need to create an issue to finish these changes if we don't have it yet.

**Comment by luu-alex** [comment]
@avkos  #6026 i have picked it up today 👍

**Comment by avkos** [comment]
@luu-alex Please close this issue when you finish #6026

**Comment by jdevcs** [comment]
Changes of this PR were merged via https://github.com/web3/web3.js/pull/6033

**Pull request closed without merging**
