### PR TITLE
unit names per White Paper

### PR DESCRIPTION
**Pull request by ethers**
A very early version of the White Paper (Dec 10 2014) already clarified / simplified unit names.
https://github.com/ethereum/wiki/wiki/White-Paper/502e0e01355a42c8e6f5463c49cce496ae423179

### CODE REVIEW

**Comment by frozeman** [comment]
These unit names are just possibilities you can use when converting wei. They are not returned a names itself anywhere, so having more doesn't hurt.

@alexvandesande you want to give your opinion on that, as you add even more :)

**Comment by alexvandesande** [comment]
Having support for unit names is very different than suggesting them in the user interface. While I strongly advise all Ðapp programmers to only use ether and at most one other, we should support all of them on the web3 object.

Actually, the reason I added milliethers and microethers was a push to slowly move away from personality names and use standard SI units. Effigies are to be considered nicknames: finney can be treated as a nickname of the milliether, like an american might call the 5 dollar bill a "Lincoln".

I am in favor of moving away from all these units, but I'm against this pull request.

**Comment by ethers** [comment]
SI units seem fine as they are standard and self-explanatory.  The reason for removing some of the effigies even though we don't show them in the UI, is others may build UIs with effigies that are only mentioned in this code, and not part of any other Ethereum literature.

@alexvandesande What do you mean by "I am in favor of moving away from all these units" ?  Remove all effigies?  Or remove the SI units too?

**Comment by alexvandesande** [comment]
@ethers I am in favor of discouraging Ðapp developers from using other
units that are not Ether. Finney (milliether) may or may not be a useful
unit when discussing micropayments or gas prices, let's see if the
community adopts it. Wei is useful for debating protocol issues.

Having said that, I'm against this Pull Request. We should support it on
the web3.js object, but discourage it's use.

On Fri, Jun 19, 2015 at 5:00 AM, ethers <notifications@github.com> wrote:

> SI units seem fine as they are standard and self-explanatory. The reason
> for removing some of the effigies even though we don't show them in the UI,
> is others may build UIs with effigies that are only mentioned in this code,
> and not part of any other Ethereum literature.
>
> @alexvandesande <https://github.com/alexvandesande> What do you mean by
> "I am in favor of moving away from all these units" ? Remove all effigies?
> Or remove the SI units too?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ethereum/web3.js/pull/240#issuecomment-113420587>.
>



-- 

Alex Van de Sande
UX Designer

**Comment by ethers** [comment]
I think I agree about discouraging units that are not Ether.  One relatively visible place we could start with is Alethzero, replace szabo with microether and finney with milliether.

To recap, this PR does keep/support finney and szabo in the web3.js object.  The PR simply removes ada, babbage, shannon, einstein (the first 3 were removed promptly in the 2nd version of Vitalik's whitepaper; I don't recall where einstein came from).  I don't see much good reason to "support" nicknames that are not referenced anywhere, no one is probably going to use, makes web3.js longer and slightly more difficult to understand.

**Comment by frozeman** [comment]
I actually agree

**Comment by frozeman** [comment]
Thanks for your PR, but i think we keep the names for compatibility reasons. Many use them already.

**Comment by ethers** [comment]
https://github.com/ethereum/EIPs/issues/33

**Comment by ethers** [comment]
Revisiting in ethereum/EIPs#33

**Comment by frozeman** [comment]
@alexvandesande looks fine to me, @ethers can you resolve the merge conflicts? rebase on develop

**Comment by alexvandesande** [comment]
I've solved the conflicts and added that as this PR: https://github.com/ethereum/web3.js/pull/399

**Comment by frozeman** [comment]
@alexvandesande this is now in right? so we can close this.

**Comment by alexvandesande** [comment]
Github automatically closes PRs when it detects commits have gone in elsewhere

**Pull request merged**
