### PR TITLE
Fix web3-types import

### LINKED ISSUE #6589: Cannot find module 'web3-types/src/eth_types' or its corresponding type declarations.
I'm getting the titular error from this line:

https://github.com/web3/web3.js/blob/8e3e67628ebc90ffe6b86ec054874cb6bb7bac31/packages/web3-rpc-methods/src/eth_rpc_methods.ts#L31C44-L31C58

Everything works okay if I change that line to
```typescript
import { Eip712TypedData } from 'web3-types';
```

#### Expected behavior
`npx tsc` runs okay

#### Actual behavior
build fails

#### Steps to reproduce the behavior
Source code that crashes during typescript build
```typescript
import Web3 from 'web3';
const web3 = new Web3(new Web3.providers.HttpProvider("https://polygon-mainnet.infura.io/v3/" + process.env.INFURA_API_KEY))
```

`npx tsc`

#### Logs
```bash
$ npx tsc
node_modules/web3-rpc-methods/lib/types/eth_rpc_methods.d.ts:3:33 - error TS2307: Cannot find module 'web3-types/src/eth_types' or its corresponding type declarations.

3 import { Eip712TypedData } from 'web3-types/src/eth_types';
```

#### Environment
node: 20.9.0

package.json dependencies:
```javascript
{
  "engines": {
    "node": ">= 20.9.0"
  },
  "devDependencies": {
    "@types/jest": "^29.5.8",
    "@types/node": "^20.9",
    "@typescript-eslint/eslint-plugin": "^6.10",
    "@typescript-eslint/parser": "^6.10",
    "eslint": "^8.53",
    "eslint-config-prettier": "~9.0",
    "eslint-plugin-jest": "^27.6",
    "jest": "^29.7.0",
    "prettier": "~3.0",
    "rimraf": "~5.0",
    "ts-api-utils": "~1.0",
    "ts-jest": "~29.1",
    "typescript": "^5.2.2"
  },
  "dependencies": {
    "tslib": "~2.6",
    "web3": "^4.2.2",
    "web3-types": "^1.3.1"
  }
}
```

and tsconfig.json
```javascript
{
  "compilerOptions": {
    "target": "es2022",
    "module": "node16",
    "lib": ["ES2022"],
    "moduleResolution": "node16",
    "rootDir": ".",
    "outDir": "build",
    "allowSyntheticDefaultImports": true,
    "importHelpers": true,
    "alwaysStrict": true,
    "sourceMap": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitAny": false,
    "noImplicitThis": false,
    "strictNullChecks": false
  },
  "include": ["src/**/*", "__tests__/**/*"]
}

```

### PR DESCRIPTION
**Pull request by dangarbri**
## Description

Fix import

Fixes #6589 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:
I did not do most of the things below because I don't have a dev environment set up for this...

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run lint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:coverage` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [x] I have linked Issue(s) with this PR in "Linked Issues" menu.

### CODE REVIEW

**Review by avkos — APPROVED** [review]

**Review by avkos — CHANGES_REQUESTED** [review]
Thanks for your contribution. with your fix, it will be two `web3-types` imports. it will be better to move the `Eip712TypedData` import to the previous import

```ts
import {
	Address,
	BlockNumberOrTag,
	Filter,
	HexString32Bytes,
	HexString8Bytes,
	HexStringBytes,
	TransactionCallAPI,
	TransactionWithSenderAPI,
	Uint,
	Uint256,
	Web3EthExecutionAPI,
        Eip712TypedData,
} from 'web3-types';
```

**Comment by dangarbri** [comment]
That makes sense. I didn't even look that closely to see that there was already a 'web3-types' import

**Review by avkos — APPROVED** [review]

**Comment by dangarbri** [comment]
I updated the PR

**Review by Muhammad-Altabba — COMMENTED** [review]
Thanks @dangarbri 
Could you also, please, update the CHANGELOG.md at packages/web3-rpc-methods to inform about the issues fixed in this MR?

**Comment by dangarbri** [comment]
I'll be able to update it later today.

**Review by Muhammad-Altabba — APPROVED** [review]
Thanks @dangarbri for your contribution.
I updated the CHANGELOG.md file.

**Comment by dangarbri** [comment]
Thanks, sorry I didn't get around to it.

**Pull request merged**
