### PR TITLE
Solution for Meteor server side

### PR DESCRIPTION
**Pull request by logvik**
Fixed problem with Web3 on server side Meteor.js. For example, you want to observe changes from blockchain and save some data in Mongo.db, but current implementation will down with the error as below.
`
TypeError: XHR2 is not a function
	at [object Object].HttpProvider.prepareRequest (packages\ethereum_web3.js:4315:15)
	at [object Object].HttpProvider.sendAsync (packages\ethereum_web3.js:4364:22)
	at [object Object].RequestManager.sendAsync (packages\ethereum_web3.js:6369:19)
	at Eth.send (packages\ethereum_web3.js:5080:42)
	at [object Object].SolidityFunction.call (packages\ethereum_web3.js:4110:15)
	at [object Object].SolidityFunction.execute (packages\ethereum_web3.js:4230:22)
`

### CODE REVIEW

**Comment by frozeman** [comment]
as it doesn't pass the tests its not an option, maybe try using `global.Meteor` and `window.Meteor`

**Comment by RamiroMoreira** [comment]
I'm getting this error when runing web3 server side. Is there a workaround? thanks

**Comment by logvik** [comment]
Problem explains below, my small added snippets don't influence whole code. I don't have time to test more right now, maybe need just merge with more higher version and all...
```
/home/travis/build/ethereum/web3.js/test/node/app.js:3
console.log(web3.version.api);
                        ^
TypeError: Cannot read property 'api' of undefined
    at Object.<anonymous> (/home/travis/build/ethereum/web3.js/test/node/app.js:3:25)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:118:18)
    at node.js:952:3
Done. Your build exited with 1.
```

**Comment by fedecryto** [comment]
Hi @logvik , did you find any solution? Different approach?
Thanks!

**Comment by logvik** [comment]
Sorry for a delaying. I have done some adaptation for commands on Window OS. I think they are isomorphic now. Please, someone, check on others OS, I don't have possibility right now to do this.

**Comment by nivida** [comment]
Closed because the latest maintenance release was 0.20.7.

**Pull request closed without merging**
