### PR TITLE
Problem deleting account when checksummed address is equal to lowercase address

### LINKED ISSUE #5049: Problem deleting account when checksummed address is equal to lowercase address
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you add an account to a wallet, it creates:

- An index;
- A checksummed address;
- A lowercase address.

So you can access using any of those keys.

When you want to remove an account it does the same process, but when you have a checksummed that is equal to lowercase, the line (681) that access the lowercase address will throw an exception because it doesn't exists anymore.

`Uncaught TypeError TypeError: Cannot set properties of undefined (setting 'privateKey')`

### Expected Behavior

No error.

### Steps to Reproduce

```js
const Accounts = require('web3-eth-accounts')

const accounts = new Accounts()
// add an account address that lowercase and checksummed are equal : 0x92b7254537e2890f728187988b829b28a01333ce
accounts.wallet.add('0xaa237230fc60e46175256cbc931852514364089a9f4e5b59b5217483b2df4df7') // not used pvt key, don't worry
// remove account with index 0
accounts.wallet.remove(0)
```

https://github.com/ChainSafe/web3.js/blob/2c0324af2da467ee1acb72452f20000e916e4306/packages/web3-eth-accounts/src/index.js#L673-L693

### Web3.js Version

1.7.3

### Environment

- Operating System: Windows 10 Pro
- Browser: None
- Node.js Version: v16.13.2
- NPM Version: 8.1.2

### Anything Else?

_No response_

### PR DESCRIPTION
**Pull request by andreistefanwork**
…lowercase are equal #5049

## Description

Please include a summary of the changes and be sure to follow our [Contribution Guidelines](../blob/1.x/CONTRIBUTIONS.md).

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [x] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [x] I ran `npm run build` with success.
- [x] I have tested the built `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [x] I have updated the `CHANGELOG.md` file in the root folder.

### CODE REVIEW

**Review by nazarhussain — APPROVED** [review]

**Comment by nazarhussain** [comment]
@andreistefanwork  Please add an entry to `CHANGELOG.md` rest LGTM.

**Review by avkos — APPROVED** [review]

**Comment by andreistefanwork** [comment]
@nazarhussain Thanks for checking it out, entry added in `CHANGELOG.md`

**Comment by andreistefanwork** [comment]
but I added it under 1.7.4, and it needs to be in 1.7.5, just like this other PR: https://github.com/ChainSafe/web3.js/pull/5048

I think I'll wait for a resolution on https://github.com/ChainSafe/web3.js/pull/5048, and eventually rebase on 1.x after 1.7.5 entry will be part of `CHANGELOG.md`

**Review by pietro-lopes — APPROVED** [review]

**Review by jdevcs — APPROVED** [review]

**Comment by jdevcs** [comment]
Merged via https://github.com/ChainSafe/web3.js/pull/5202

**Pull request merged**
