### PR TITLE
Fix buggy `BlockHeader` ts interface

### LINKED ISSUE #4517: Buggy `BlockHeader` interface
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The name of the `receiptRoot` property of the `BlockHeader` class is not correct.

wiki:
https://eth.wiki/json-rpc/API#:~:text=of%20the%20block.-,receiptsRoot,-%3A

Related issue:
ethereum/go-ethereum#3084

### Expected Behavior

we should use `receiptsRoot` instead of `receiptRoot`

```
export interface BlockHeader {
    number: number;
    hash: string;
    parentHash: string;
    nonce: string;
    sha3Uncles: string;
    logsBloom: string;
    transactionRoot: string;
    stateRoot: string;
    receiptsRoot: string;
    miner: string;
    extraData: string;
    gasLimit: number;
    gasUsed: number;
    timestamp: number | string;
    baseFeePerGas?: number;
}

```

### Steps to Reproduce

just call `web3.eth.getBlock()` and check the returned object

### Web3.js Version

1.5.3

### Environment

_No response_

### Anything Else?

_No response_

### PR DESCRIPTION
**Pull request by karim-en**
## Description
The name of the `receiptRoot` property is not correct and we should use `receiptsRoot` instead.

wiki:
https://eth.wiki/json-rpc/API#:~:text=of%20the%20block.-,receiptsRoot,-%3A

# Related Issue
Resolve #4517
https://github.com/ethereum/go-ethereum/issues/3084

## Type of change
- [+] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by nazarhussain — CHANGES_REQUESTED** [review]
@karim-en  Thanks for the contribution, I am running the CI jobs on this PR to see if something related is broken. 

Meanwhile can you please look into these two tests and see if these are related to change. 

https://github.com/ChainSafe/web3.js/blob/ab27807a6c2726331ba5ec1b3cef2b830f71264c/test/eth.subscribe.js#L32

https://github.com/ChainSafe/web3.js/blob/ab27807a6c2726331ba5ec1b3cef2b830f71264c/test/eth.subscribe.js#L51

I would also suggest that you create an a bug issue on web3 repo and then link your PR to that issue.

**Comment by nazarhussain** [comment]
@karim-en Did you get a chance to look into above message?

**Comment by karim-en** [comment]
> @karim-en Did you get a chance to look into above message?

Oh, thanks for bumping me, I missed your message, I am going to check that

**Comment by nazarhussain** [comment]
@karim-en We look forward for your update on this PR so we can merge it.

**Comment by karim-en** [comment]
> @karim-en We look forward for your update on this PR so we can merge it.

Done. sorry for the delay.

**Review by nazarhussain — APPROVED** [review]

**Comment by Spacesai1or** [comment]
Taking over PR to update `CHANGELOG.md`

**Pull request merged**
