### PR TITLE
Fix broken gulp build

### PR DESCRIPTION
**Pull request by joshstevens19**
Hi i forked your repo and was going to start fixing some bugs but i seen the `gulp` build had been broken. This is because you had `>=3.9.0` in the `package.json` which forced version `4` to be downloaded (which is a must due to some high warning version `3.9` had.)

I took it on myself to fix the `gulpfile.js` to run with version 4.0. It now runs again and is all fixed. Hopefully this will be my first PR of many. Please accept and merge in so others do not have this problem.

Thanks
Josh

### CODE REVIEW

**Comment by nivida** [comment]
Unfortunately, I have to close this PR because of the PR2000. We will no longer use gulp to bundle an transpile the web3.js lib.

**Comment by joshstevens19** [comment]
Ok is it not worth removing the gulpfile and dependencies from the project to avoid confusion

**Comment by nivida** [comment]
This will happen on the end of december when the PR 2000 will be merged in to the 1.0 branch :)

**Comment by nivida** [comment]
Ou I just noticed this PR is against the develop branch (0.20.x) I will reopen it and check it today or tomorrow and merge it I apologize for the confusion.

**Comment by joshstevens19** [comment]
No worries, thanks 👍

**Review by nivida — APPROVED** [review]

**Pull request merged**
