### PR TITLE
1.x: Fix EIP-1193 provider subscriptions

### LINKED ISSUE #3651: RequestManager depends on deprecated event when used with MetaMask
Refs: https://github.com/ethereum/web3.js/blob/1.x/packages/web3-core-requestmanager/src/index.js#L101-L108

`web3-core-requestmanager` depends on the provider `data` event, and makes assumptions about its state. I'm not sure if this even was ever intended for consumer usage in the misty past, but by now, it's superfluous.

For MetaMask providers (`ethereum.isMetaMask && typeof ethereum.request === 'function'`), please use the EIP-1193 `message` event, described in our docs: https://docs.metamask.io/guide/ethereum-provider.html#message

The `message` event emits with an object of the form `{ method: string, data: any }`. For `method === 'eth_subscription'`, the result is given as `data.result`.

### PR DESCRIPTION
**Pull request by rekmarks**
Fixes #3651 

Implements subscription support per [EIP-1193](https://eips.ethereum.org/EIPS/eip-1193#subscriptions).

Should be tested manually by maintainers with current MetaMask (^9.0.0) on Firefox.

### CODE REVIEW

**Comment by frankiebee** [comment]
Cool thanks for this will take a look at this!

**Comment by rekmarks** [comment]
FYI: I'm receiving reports that using `patch-package` with this PR fixes the issue.

**Review by GregTheGreek — APPROVED** [review]
LGTM

**Review by Spacesai1or — APPROVED** [review]
Installed this patch locally and tested using Firefox and MetaMask v9.0.1

**Review by frankiebee — APPROVED** [review]
purely from a code stand point this looks good!

**Pull request merged**
