### PR TITLE
Add tx hash for sign transaction es6

### PR DESCRIPTION
**Pull request by OFRBG**
Implements PR #2151 for the ES6 branch and includes #2199.

OG by @nujabes403.

### CODE REVIEW

**Comment by nivida** [comment]
Will check it and merge it before the ethereumProvider get released. Thanks for your efforts!

**Comment by nujabes403** [comment]
👍

**Review by nivida — CHANGES_REQUESTED** [review]
Could you extend the types and the documentation too? Probably it's easier to create a new PR.

**Comment by nujabes403** [comment]
@nivida @OFRBG Please take a look. 🙂 #2694

**Pull request closed without merging**
