### PR TITLE
Release 1.3.4-rc.2

### PR DESCRIPTION
**Pull request by Spacesai1or**
This release contains bug fixes, updates dependencies (including 4 security vulnerabilities), adds deprecation notice for `web3-bzz`, and updates the Typescript types for `web3-eth2-core` and `web3-eth2-beaconchain`

### Changed

- Fixed mutation of inputs to encoding and decoding functions (#3748)
- Fix default value for `fromBlock` option for `logs` subscriptions (defaults to `latest`) (#3883)
- ethjs-signer test (#3876)
- Rename `web3-eth2-base` to `web3-eth2-core` and `web3-eth2-beacon` to `web3-eth2-beaconchain` (#3833)
- Bump `ts-node` from version `^8.10.2` to `^9.0.0` (#3856)
- Ran `npm audit fix` which fixed 4 vulnerabilities (#3856)
- Correct `web3-eth2-beaconchain` type declarations (#3859) and (#3865)
- Move interfaces `IBaseAPISchema` and `IBaseAPIMethodSchema` to `index.d.ts` for `web3-eth2-core` (#3878)
- Update dependencies for `web3-eth2-core` (#3878)

### Removed

- Remove `notImplemented` flag from ETH2 Beacon Chain package methods schema (#3861)
- Removes `IETH2BeaconChain` interface in favor of exporting a class type: `ETH2BeaconChain` (#3878)
- Remove `index.d.ts` files in favor of `types.ts` for `web3-eth2-core` and `web3-eth2-beaconchain` (#3878)
- `schema.ts` from `web3-eth2-core` (#3878)
- `dtslint` npm command from `web3-eth2-core` and `web3-eth2-beaconchain` as `index.d.ts` files were removed (#3878)

### Added

- Add `ETH2Core` class export to `index.d.ts` for `web3-eth2-core` (#3878)
- Deprecation of bzz warning (#3872)

### CODE REVIEW

**Review by GregTheGreek — COMMENTED** [review]
~LGTM will start the npm release~ 
Build didn't work

**Review by GregTheGreek — COMMENTED** [review]
RC LGTM

**Comment by Spacesai1or** [comment]
Ran using `1.3.4-rc.1`

Replicating the steps mentioned in [previous releases](https://github.com/ethereum/web3.js/pull/3633#issuecomment-656217052)

As part of the RC process, am doing some test installations in other projects and running their tests to see if everything.  
+ installs properly
+ builds
+ tests pass

(This list will be actively edited) 

| Project | Desc | Status | 
| ------ | ----- | ----- |
| [oz-test-helpers][1] | Test utils. Subset of their suite is web3 contracts | ✔️  |
| [synthetix][2] | ~1000 units | ❌ |

[1]: https://github.com/OpenZeppelin/openzeppelin-test-helpers
[2]: https://github.com/Synthetixio/synthetix

Synthetic tests failed with same `JavaScript heap out of memory` as last release:

```javascript
  Contract: Exchange Rates
    when integrating with modern contracts
      ✓ only expected functions should be mutative
      constructor
        ✓ should set constructor params on deployment (107ms)
        ✓ two different currencies in same array should mean that the second one overrides (125ms)
        ✓ should revert when number of currency keys > new rates length on create (97ms)
        ✓ should limit to 32 bytes if currency key > 32 bytes on create (115ms)
        ✓ shouldn't be able to set exchange rate to 0 on create (98ms)

<--- Last few GCs --->

[26170:0x4426ef0]   697444 ms: Scavenge 1346.2 (1395.4) -> 1345.2 (1395.4) MB, 2.9 / 0.0 ms  (average mu = 0.187, current mu = 0.130) allocation failure 
[26170:0x4426ef0]   697455 ms: Scavenge 1352.7 (1402.0) -> 1351.7 (1402.0) MB, 3.5 / 0.0 ms  (average mu = 0.187, current mu = 0.130) allocation failure 
[26170:0x4426ef0]   697464 ms: Scavenge 1358.3 (1407.7) -> 1357.4 (1407.7) MB, 3.4 / 0.0 ms  (average mu = 0.187, current mu = 0.130) allocation failure 


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3bd63389e6e9 <JSObject>
    0: builtin exit frame: concat(this=0x234376382799 <JSArray[82432]>,0x234376382df1 <JSArray[32]>,0x234376382799 <JSArray[82432]>)

    1: MSTORE(aka MSTORE) [0x171942ab16f9] [/home/anon/tmp/synthetix/node_modules/@nomiclabs/ethereumjs-vm/dist/evm/opFns.js:~445] [pc=0x3a2909f701a8](this=0x330780d022b1 <null>,runState=0x2450cad13189 <Object map = 0xabd67fee731>)
    2: runStep [0x171942a9bcd9] ...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x8fa090 node::Abort() [/home/anon/.nvm/versions/node/v10.19.0/bin/node]
 2: 0x8fa0dc  [/home/anon/.nvm/versions/node/v10.19.0/bin/node]
 3: 0xb0052e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/home/anon/.nvm/versions/node/v10.19.0/bin/node]
 4: 0xb00764 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/home/anon/.nvm/versions/node/v10.19.0/bin/node]
 5: 0xef4c72  [/home/anon/.nvm/versions/node/v10.19.0/bin/node]
 6: 0xef4d78 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/home/anon/.nvm/versions/node/v10.19.0/bin/node]
 7: 0xf00e52 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/home/anon/.nvm/versions/node/v10.19.0/bin/node]
 8: 0xf01784 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/home/anon/.nvm/versions/node/v10.19.0/bin/node]
 9: 0xf043f1 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/home/anon/.nvm/versions/node/v10.19.0/bin/node]
10: 0xecd4e6 v8::internal::Factory::AllocateRawArray(int, v8::internal::PretenureFlag) [/home/anon/.nvm/versions/node/v10.19.0/bin/node]
11: 0xecdd6a v8::internal::Factory::NewFixedArrayWithFiller(v8::internal::Heap::RootListIndex, int, v8::internal::Object*, v8::internal::PretenureFlag) [/home/anon/.nvm/versions/node/v10.19.0/bin/node]
12: 0xeda751 v8::internal::Factory::NewJSArrayStorage(v8::internal::Handle<v8::internal::JSArray>, int, int, v8::internal::ArrayStorageAllocationMode) [/home/anon/.nvm/versions/node/v10.19.0/bin/node]
13: 0xedaa4c v8::internal::Factory::NewJSArray(v8::internal::ElementsKind, int, int, v8::internal::ArrayStorageAllocationMode, v8::internal::PretenureFlag) [/home/anon/.nvm/versions/node/v10.19.0/bin/node]
14: 0xe93e81 v8::internal::ElementsAccessor::Concat(v8::internal::Isolate*, v8::internal::Arguments*, unsigned int, unsigned int) [/home/anon/.nvm/versions/node/v10.19.0/bin/node]
15: 0xb8fcc9  [/home/anon/.nvm/versions/node/v10.19.0/bin/node]
16: 0xb993c8 v8::internal::Builtin_ArrayConcat(int, v8::internal::Object**, v8::internal::Isolate*) [/home/anon/.nvm/versions/node/v10.19.0/bin/node]
17: 0x3a290535bf7d 
Aborted (core dumped)
error Command failed with exit code 134.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Spacesai1or** [comment]
Ran using `1.3.4-rc.2`

Replicating the steps mentioned in [previous releases](https://github.com/ethereum/web3.js/pull/3633#issuecomment-656217052)

As part of the RC process, am doing some test installations in other projects and running their tests to see if everything.  
+ installs properly
+ builds
+ tests pass

(This list will be actively edited) 

| Project | Desc | Status | 
| ------ | ----- | ----- |
| [oz-test-helpers][1] | Test utils. Subset of their suite is web3 contracts | ✔️  |
| [synthetix][2] | ~1000 units | ❌ |

[1]: https://github.com/OpenZeppelin/openzeppelin-test-helpers
[2]: https://github.com/Synthetixio/synthetix

Synthetic tests failed with same `JavaScript heap out of memory` as last release:

```javascript
  Contract: Exchange Rates
    when integrating with modern contracts
      ✓ only expected functions should be mutative
      constructor
        ✓ should set constructor params on deployment (419ms)
        ✓ two different currencies in same array should mean that the second one overrides (159ms)
        ✓ should revert when number of currency keys > new rates length on create (109ms)
        ✓ should limit to 32 bytes if currency key > 32 bytes on create (123ms)
        ✓ shouldn't be able to set exchange rate to 0 on create (109ms)

<--- Last few GCs --->

[10670:0x34cdef0]   698038 ms: Scavenge 1345.9 (1397.1) -> 1344.9 (1397.1) MB, 2.4 / 0.0 ms  (average mu = 0.176, current mu = 0.130) allocation failure 
[10670:0x34cdef0]   698047 ms: Scavenge 1352.2 (1403.5) -> 1351.2 (1403.5) MB, 2.7 / 0.0 ms  (average mu = 0.176, current mu = 0.130) allocation failure 
[10670:0x34cdef0]   698055 ms: Scavenge 1357.9 (1409.3) -> 1356.9 (1409.3) MB, 2.4 / 0.0 ms  (average mu = 0.176, current mu = 0.130) allocation failure 


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x090565e1e6e9 <JSObject>
    0: builtin exit frame: concat(this=0x0fd892782271 <JSArray[83168]>,0x0fd892782929 <JSArray[32]>,0x0fd892782271 <JSArray[83168]>)

    1: MSTORE(aka MSTORE) [0xccc7979ac69] [/home/anon/tmp/synthetix/node_modules/@nomiclabs/ethereumjs-vm/dist/evm/opFns.js:~445] [pc=0x2d6205dc9da8](this=0x0904365822b1 <null>,runState=0x2c130d4d8331 <Object map = 0x16881acb98e1>)
    2: runStep [0xccc79786601] [...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x8fa090 node::Abort() [/home/anon/.nvm/versions/node/v10.19.0/bin/node]
 2: 0x8fa0dc  [/home/anon/.nvm/versions/node/v10.19.0/bin/node]
 3: 0xb0052e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/home/anon/.nvm/versions/node/v10.19.0/bin/node]
 4: 0xb00764 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/home/anon/.nvm/versions/node/v10.19.0/bin/node]
 5: 0xef4c72  [/home/anon/.nvm/versions/node/v10.19.0/bin/node]
 6: 0xef4d78 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/home/anon/.nvm/versions/node/v10.19.0/bin/node]
 7: 0xf00e52 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/home/anon/.nvm/versions/node/v10.19.0/bin/node]
 8: 0xf01784 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/home/anon/.nvm/versions/node/v10.19.0/bin/node]
 9: 0xf043f1 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/home/anon/.nvm/versions/node/v10.19.0/bin/node]
10: 0xecd4e6 v8::internal::Factory::AllocateRawArray(int, v8::internal::PretenureFlag) [/home/anon/.nvm/versions/node/v10.19.0/bin/node]
11: 0xecdd6a v8::internal::Factory::NewFixedArrayWithFiller(v8::internal::Heap::RootListIndex, int, v8::internal::Object*, v8::internal::PretenureFlag) [/home/anon/.nvm/versions/node/v10.19.0/bin/node]
12: 0xeda751 v8::internal::Factory::NewJSArrayStorage(v8::internal::Handle<v8::internal::JSArray>, int, int, v8::internal::ArrayStorageAllocationMode) [/home/anon/.nvm/versions/node/v10.19.0/bin/node]
13: 0xedaa4c v8::internal::Factory::NewJSArray(v8::internal::ElementsKind, int, int, v8::internal::ArrayStorageAllocationMode, v8::internal::PretenureFlag) [/home/anon/.nvm/versions/node/v10.19.0/bin/node]
14: 0xe93e81 v8::internal::ElementsAccessor::Concat(v8::internal::Isolate*, v8::internal::Arguments*, unsigned int, unsigned int) [/home/anon/.nvm/versions/node/v10.19.0/bin/node]
15: 0xb8fcc9  [/home/anon/.nvm/versions/node/v10.19.0/bin/node]
16: 0xb993c8 v8::internal::Builtin_ArrayConcat(int, v8::internal::Object**, v8::internal::Isolate*) [/home/anon/.nvm/versions/node/v10.19.0/bin/node]
17: 0x2d62011dbf7d 
Aborted (core dumped)
error Command failed with exit code 134.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Review by frankiebee — APPROVED** [review]
🎉

**Review by koosy79 — COMMENTED** [review]
Ok

**Pull request merged**
