### PR TITLE
Account signing fix

### PR DESCRIPTION
**Pull request by frozeman**
This should fix the transaction signing for custom network IDs. Please test.

### CODE REVIEW

**Comment by naddison36** [comment]
I would like to test this as I'm trying to sign locally before sending raw transaction to a remote node. What's the best way to get npm to install from this accountSigningFix branch?

**Comment by frozeman** [comment]
Use in your package json the the git branch rather than the version number: https://stackoverflow.com/questions/39732397/install-specific-branch-from-github-using-npm

**Comment by naddison36** [comment]
@frozeman I tried adding `"web3": "git://github.com/ethereum/web3.js#accountSigningFix"` to my package.json but I got the following error
```
npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/nick/.nvm/versions/node/v6.11.4/bin/node" "/Users/nick/.nvm/versions/node/v6.11.4/bin/npm" "update"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! web3@1.0.0-beta.23 postinstall: `lerna bootstrap`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the web3@1.0.0-beta.23 postinstall script 'lerna bootstrap'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the web3 package,
npm ERR! not with npm itself.
```
The latest version of the 1.0 branch installs fine `"web3": "1.0.0-beta.23"`

 I seem to be missing something when installing from a branch. Does the branch need to be built?

**Comment by frozeman** [comment]
I updated the eth-lib version to 0.2.5 please re-test.

@naddison36 It should build fine, please check the npm-log, or lerna log for details on your side.

**Comment by naddison36** [comment]
I'm still getting the same error. I've even tried the nuclear option of deleting my node_modules folder and npm cache.

This is the error in `npm-debug.log`
```
50149 verbose lifecycle web3@1.0.0-beta.23~postinstall: PATH: /Users/nick/.nvm/versions/node/v6.11.4/lib/node_modules/npm/bin/node-gyp-bin:/Users/nicholasaddison/Documents/workspaces/open-bank-token/node_modules/web3/node_modules/.bin:/Users/nick/Documents/workspaces/open-bank-token/node_modules/.bin:/Users/nick/.nvm/versions/node/v6.11.4/bin:/Users/nick/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
50150 verbose lifecycle web3@1.0.0-beta.23~postinstall: CWD: /Users/nick/Documents/workspaces/open-bank-token/node_modules/web3
50151 silly lifecycle web3@1.0.0-beta.23~postinstall: Args: [ '-c', 'lerna bootstrap' ]
50152 info lifecycle web3@1.0.0-beta.23~postinstall: Failed to exec postinstall script
50153 verbose unlock done using /Users/nick/.npm/_locks/staging-0ee530199745d5d9.lock for /Users/nick/Documents/workspaces/open-bank-token/node_modules/.staging
50154 silly rollbackFailedOptional Starting
50155 silly rollbackFailedOptional Finishing
50156 silly runTopLevelLifecycles Finishing
50157 silly install printInstalled
50158 verbose stack Error: web3@1.0.0-beta.23 postinstall: `lerna bootstrap`
50158 verbose stack spawn ENOENT
50158 verbose stack     at ChildProcess.<anonymous> (/Users/nick/.nvm/versions/node/v6.11.4/lib/node_modules/npm/lib/utils/spawn.js:33:16)
50158 verbose stack     at emitTwo (events.js:106:13)
50158 verbose stack     at ChildProcess.emit (events.js:191:7)
50158 verbose stack     at maybeClose (internal/child_process.js:920:16)
50158 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
50159 verbose pkgid web3@1.0.0-beta.23
```

I don't know where the lerna log is kept

**Comment by frozeman** [comment]
Could you try installing `lerna` globally before?

**Pull request merged**
