### PR TITLE
v1.7.2

### PR DESCRIPTION
**Pull request by jdevcs**
### Changed
-  Remove deprecated `close` event listener (#4825) (#4839)

### Security
-  `npm audit fix` to update libraries (#4860)

### Fixed
-  Fix jsonrpc payload and response types (#4743) (#4761)
-  Allowed more flexibility in typing the overly constrained `provider.disconnect` function (#4833)

### CODE REVIEW

**Comment by jdevcs** [comment]
As part of the RC process, following test installations are performed in other projects and running their tests to see if everything.  
+ installs properly
+ builds
+ tests pass

(This list will be actively edited) 

| Project | Desc | Status | 
| ------ | ----- | ----- |
| [oz-test-helpers][1] | Test utils. Subset of their suite is web3 contracts | ✅ |
| [synthetix][2] | ~1000 units | ✅  |


[1]: https://github.com/OpenZeppelin/openzeppelin-test-helpers
[2]: https://github.com/Synthetixio/synthetix

**Review by luu-alex — APPROVED** [review]

**Review by nikoulai — APPROVED** [review]

**Review by avkos — APPROVED** [review]

**Review by nazarhussain — APPROVED** [review]

**Comment by jdevcs** [comment]
eth2 test was failing with latest lighthouse docker image  

```
FAIL test/schemaMethods.test.ts
  ● getBlockAttestations

    expect(received).toMatchObject(expected)

    Matcher error: received value must be a non-null object

    Received has value: undefined

      270 |
      271 |     const response = await eth2BeaconChain.getBlockAttestations(routeParameters)
    > 272 |     expect(response[0]).toMatchObject(expectedResponse)
          |                         ^
      273 | })
      274 |
      275 | /**

      at _callee14$ (test/schemaMethods.test.ts:272:25)
      at tryCatch (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:294:22)
      at Generator.next (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:119:21)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)

PASS test/constructor.test.ts

Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 failed, 1 skipped, 21 passed, 23 total
Snapshots:   0 total
Time:        2.437 s
```

This test is passing with lighthouse v2.1.5

**Comment by jdevcs** [comment]
lighthouse v2.2.0 https://github.com/sigp/lighthouse/issues/3147

**Comment by jdevcs** [comment]
Closing this PR without merging to 1.x as there was issue in 1.7.2 release.
[1.7.3](https://github.com/ChainSafe/web3.js/pull/4925) was branched off from 1.7.2 and it have fix of build issue, so will merge 1.7.3 into 1.x .

**Pull request closed without merging**
