### PR TITLE
Syntax error Fix in docs

### PR DESCRIPTION
**Pull request by sacgrover**
## Description
 This PR will fix a lot of syntax errors in docs

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [x] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [x] I ran `npm run test:unit` with success.
- [x] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [x] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

### CODE REVIEW

**Comment by sacgrover** [comment]
@GregTheGreek @spacesailor24 Could you please review this PR?

**Comment by GregTheGreek** [comment]
@sacgrover good eye, but the docs are technically correct, let me try and explain.

The notation `function(param [, param])` where the `,` comes after the `[` denotes that a parameter is optional. You can see a similar example with the node.js [buffer package](https://nodejs.org/api/buffer.html#buffer_static_method_buffer_alloc_size_fill_encoding)


For example:
```
web3.utils.soliditySha3(param1 [, param2, ...])
```
Tells the user that at a minimum you need `param1` supplied for the function to operate correctly. 

Does that make sense?

**Comment by sacgrover** [comment]
@GregTheGreek Yes, it does.  My Bad!! I wasn't aware of this syntax :p Thank You for the explanation.

**Comment by GregTheGreek** [comment]
@sacgrover  Pleasure to help :)

**Pull request closed without merging**
