### PR TITLE
Fix Link to Contributing Guide

### LINKED ISSUE #7266: Invalid contribution link. resulting in a 404 error
Migration Guide
[Migration Guide from Web3.js 1.x to 4.x](https://docs.web3js.org/guides/web3_upgrade_guide/x/) Breaking changes are listed in migration guide and its first step for migrating from Web3.js 1.x to 4.x. If there is any question or discussion feel free to ask in [Discord](https://discord.gg/yjyvFRP), and in case of any bug or new feature request [open issue](https://github.com/web3/web3.js/issues/new) or create a pull request for [contributions](https://github.com/web3/web3.js/blob/4.x/CONTRIBUTIONS.md).

Steps before creating an issue: 

1. I've read the documentation.
2. I've tried googling or asking my question on stackoverflow.
3. I've tried searching this repository for similar issues.

-->

#### Steps to reproduce the behavior

1. [First step]
2. [Second step]
3. [and so on...]

### PR DESCRIPTION
**Pull request by danforbes**
Closes #7266

### CODE REVIEW

**Comment by luu-alex** [comment]
can you also add these changes to the PR https://github.com/web3/web3.js/pull/7275

**Comment by danforbes** [comment]
Closing in favor of #7275

**Comment by danforbes** [comment]
Reopening after discussion with @luu-alex

**Comment by danforbes** [comment]
Closing in favor of #7283

**Pull request closed without merging**
